// AUTO-GENERATED by packages/api-codegen/generate-scopes.js — DO NOT EDIT.
// Regenerate with `pnpm generate` after changing which scopes a token can carry.
//
// Source: app/openapi.yaml, the x-kaiten-scopes list of its bearerAuth scheme.
// The API derives that list from pkg/scope (scope.OrganizationScopes): every
// scope an organization credential can carry is here, including those a service
// in front of the Core API enforces (webhooks, by the webhooks service), so a
// scope added to the backend reaches the token picker with no change on this
// side.

export const API_SCOPE_RESOURCES = [
  'addons',
  'billing',
  'components',
  'customers',
  'deployment_zones',
  'entitlements',
  'feature_flags',
  'instances',
  'licenses',
  'metadata_fields',
  'notifications',
  'organizations',
  'publishable_keys',
  'releases',
  'tokens',
  'voucher_redemptions',
  'vouchers',
  'webhooks',
] as const;

export type ApiScopeResource = (typeof API_SCOPE_RESOURCES)[number];

export const API_SCOPE_PERMISSIONS = ['read', 'write'] as const;

export type ApiScopePermission = (typeof API_SCOPE_PERMISSIONS)[number];

export const API_SCOPES = [
  'read:addons',
  'read:billing',
  'read:components',
  'read:customers',
  'read:deployment_zones',
  'read:entitlements',
  'read:feature_flags',
  'read:instances',
  'read:licenses',
  'read:metadata_fields',
  'read:notifications',
  'read:organizations',
  'read:publishable_keys',
  'read:releases',
  'read:tokens',
  'read:voucher_redemptions',
  'read:vouchers',
  'read:webhooks',
  'write:addons',
  'write:billing',
  'write:components',
  'write:customers',
  'write:deployment_zones',
  'write:entitlements',
  'write:feature_flags',
  'write:instances',
  'write:licenses',
  'write:metadata_fields',
  'write:notifications',
  'write:organizations',
  'write:publishable_keys',
  'write:releases',
  'write:tokens',
  'write:voucher_redemptions',
  'write:vouchers',
  'write:webhooks',
] as const;

export type ApiScope = (typeof API_SCOPES)[number];
