// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: component.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addComponentToRelease = `-- name: AddComponentToRelease :exec
INSERT INTO component_release (component_id, release_id, organization_id)
VALUES ($1, $2, $3)
`

type AddComponentToReleaseParams struct {
	ComponentID    uuid.UUID `json:"component_id"`
	ReleaseID      uuid.UUID `json:"release_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) AddComponentToRelease(ctx context.Context, arg AddComponentToReleaseParams) error {
	_, err := q.db.Exec(ctx, addComponentToRelease, arg.ComponentID, arg.ReleaseID, arg.OrganizationID)
	return err
}

const copyComponentsFromRelease = `-- name: CopyComponentsFromRelease :exec
INSERT INTO component_release (component_id, release_id, organization_id)
SELECT cr.component_id, $1, cr.organization_id
FROM component_release cr
WHERE cr.release_id = $2
  AND cr.organization_id = $3
`

type CopyComponentsFromReleaseParams struct {
	NewReleaseID    uuid.UUID `json:"new_release_id"`
	SourceReleaseID uuid.UUID `json:"source_release_id"`
	OrganizationID  uuid.UUID `json:"organization_id"`
}

func (q *Queries) CopyComponentsFromRelease(ctx context.Context, arg CopyComponentsFromReleaseParams) error {
	_, err := q.db.Exec(ctx, copyComponentsFromRelease, arg.NewReleaseID, arg.SourceReleaseID, arg.OrganizationID)
	return err
}

const countReleaseLinksByComponentID = `-- name: CountReleaseLinksByComponentID :one
SELECT COUNT(*)::bigint
FROM component_release cr
WHERE cr.component_id = $1
  AND cr.organization_id = $2
`

type CountReleaseLinksByComponentIDParams struct {
	ComponentID    uuid.UUID `json:"component_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) CountReleaseLinksByComponentID(ctx context.Context, arg CountReleaseLinksByComponentIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReleaseLinksByComponentID, arg.ComponentID, arg.OrganizationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createComponent = `-- name: CreateComponent :one
WITH inserted AS (
  INSERT INTO component (name, version, slug, description, previous_component_id, created_by_id, organization_id)
  SELECT $1, $2, $3, $4, $5, uo.user_id, uo.organization_id
  FROM user_on_organization uo
  WHERE uo.organization_id = $6
    AND uo.user_id = $7
    AND uo.deleted_at IS NULL
  RETURNING id, previous_component_id, name, version, slug, description, created_at, created_by_id, organization_id
)
SELECT inserted.id, inserted.previous_component_id, inserted.name, inserted.version, inserted.slug, inserted.description, inserted.created_at, inserted.created_by_id, inserted.organization_id,
       creator.name AS created_by_name
FROM inserted
  INNER JOIN "user" creator ON inserted.created_by_id = creator.id
`

type CreateComponentParams struct {
	Name                string     `json:"name"`
	Version             string     `json:"version"`
	Slug                string     `json:"slug"`
	Description         *string    `json:"description"`
	PreviousComponentID *uuid.UUID `json:"previous_component_id"`
	OrganizationID      uuid.UUID  `json:"organization_id"`
	UserID              uuid.UUID  `json:"user_id"`
}

type CreateComponentRow struct {
	ID                  uuid.UUID        `json:"id"`
	PreviousComponentID *uuid.UUID       `json:"previous_component_id"`
	Name                string           `json:"name"`
	Version             string           `json:"version"`
	Slug                string           `json:"slug"`
	Description         *string          `json:"description"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	CreatedByID         uuid.UUID        `json:"created_by_id"`
	OrganizationID      uuid.UUID        `json:"organization_id"`
	CreatedByName       string           `json:"created_by_name"`
}

func (q *Queries) CreateComponent(ctx context.Context, arg CreateComponentParams) (CreateComponentRow, error) {
	row := q.db.QueryRow(ctx, createComponent,
		arg.Name,
		arg.Version,
		arg.Slug,
		arg.Description,
		arg.PreviousComponentID,
		arg.OrganizationID,
		arg.UserID,
	)
	var i CreateComponentRow
	err := row.Scan(
		&i.ID,
		&i.PreviousComponentID,
		&i.Name,
		&i.Version,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.OrganizationID,
		&i.CreatedByName,
	)
	return i, err
}

const deleteComponentBySlug = `-- name: DeleteComponentBySlug :one
WITH deleted AS (
  DELETE FROM component c
  WHERE c.slug = $1
    AND c.organization_id = $2
  RETURNING id, previous_component_id, name, version, slug, description, created_at, created_by_id, organization_id
)
SELECT deleted.id, deleted.previous_component_id, deleted.name, deleted.version, deleted.slug, deleted.description, deleted.created_at, deleted.created_by_id, deleted.organization_id,
       creator.name AS created_by_name
FROM deleted
  INNER JOIN "user" creator ON deleted.created_by_id = creator.id
`

type DeleteComponentBySlugParams struct {
	Slug           string    `json:"slug"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type DeleteComponentBySlugRow struct {
	ID                  uuid.UUID        `json:"id"`
	PreviousComponentID *uuid.UUID       `json:"previous_component_id"`
	Name                string           `json:"name"`
	Version             string           `json:"version"`
	Slug                string           `json:"slug"`
	Description         *string          `json:"description"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	CreatedByID         uuid.UUID        `json:"created_by_id"`
	OrganizationID      uuid.UUID        `json:"organization_id"`
	CreatedByName       string           `json:"created_by_name"`
}

func (q *Queries) DeleteComponentBySlug(ctx context.Context, arg DeleteComponentBySlugParams) (DeleteComponentBySlugRow, error) {
	row := q.db.QueryRow(ctx, deleteComponentBySlug, arg.Slug, arg.OrganizationID)
	var i DeleteComponentBySlugRow
	err := row.Scan(
		&i.ID,
		&i.PreviousComponentID,
		&i.Name,
		&i.Version,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.OrganizationID,
		&i.CreatedByName,
	)
	return i, err
}

const deleteOrphanComponents = `-- name: DeleteOrphanComponents :exec
DELETE FROM component c
WHERE c.organization_id = $1
  AND NOT EXISTS (
    SELECT 1 FROM component_release cr
    WHERE cr.component_id = c.id
  )
`

func (q *Queries) DeleteOrphanComponents(ctx context.Context, organizationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrphanComponents, organizationID)
	return err
}

const getComponentByID = `-- name: GetComponentByID :one
SELECT c.id, c.previous_component_id, c.name, c.version, c.slug, c.description, c.created_at, c.created_by_id, c.organization_id,
       creator.name AS created_by_name
FROM component c
  INNER JOIN "user" creator ON c.created_by_id = creator.id
WHERE c.id = $1
  AND c.organization_id = $2
`

type GetComponentByIDParams struct {
	ComponentID    uuid.UUID `json:"component_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type GetComponentByIDRow struct {
	ID                  uuid.UUID        `json:"id"`
	PreviousComponentID *uuid.UUID       `json:"previous_component_id"`
	Name                string           `json:"name"`
	Version             string           `json:"version"`
	Slug                string           `json:"slug"`
	Description         *string          `json:"description"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	CreatedByID         uuid.UUID        `json:"created_by_id"`
	OrganizationID      uuid.UUID        `json:"organization_id"`
	CreatedByName       string           `json:"created_by_name"`
}

func (q *Queries) GetComponentByID(ctx context.Context, arg GetComponentByIDParams) (GetComponentByIDRow, error) {
	row := q.db.QueryRow(ctx, getComponentByID, arg.ComponentID, arg.OrganizationID)
	var i GetComponentByIDRow
	err := row.Scan(
		&i.ID,
		&i.PreviousComponentID,
		&i.Name,
		&i.Version,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.OrganizationID,
		&i.CreatedByName,
	)
	return i, err
}

const getComponentBySlug = `-- name: GetComponentBySlug :one
SELECT c.id, c.previous_component_id, c.name, c.version, c.slug, c.description, c.created_at, c.created_by_id, c.organization_id,
       creator.name AS created_by_name
FROM component c
  INNER JOIN "user" creator ON c.created_by_id = creator.id
WHERE c.slug = $1
  AND c.organization_id = $2
`

type GetComponentBySlugParams struct {
	Slug           string    `json:"slug"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type GetComponentBySlugRow struct {
	ID                  uuid.UUID        `json:"id"`
	PreviousComponentID *uuid.UUID       `json:"previous_component_id"`
	Name                string           `json:"name"`
	Version             string           `json:"version"`
	Slug                string           `json:"slug"`
	Description         *string          `json:"description"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	CreatedByID         uuid.UUID        `json:"created_by_id"`
	OrganizationID      uuid.UUID        `json:"organization_id"`
	CreatedByName       string           `json:"created_by_name"`
}

func (q *Queries) GetComponentBySlug(ctx context.Context, arg GetComponentBySlugParams) (GetComponentBySlugRow, error) {
	row := q.db.QueryRow(ctx, getComponentBySlug, arg.Slug, arg.OrganizationID)
	var i GetComponentBySlugRow
	err := row.Scan(
		&i.ID,
		&i.PreviousComponentID,
		&i.Name,
		&i.Version,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.OrganizationID,
		&i.CreatedByName,
	)
	return i, err
}

const getComponents = `-- name: GetComponents :many
SELECT c.id, c.previous_component_id, c.name, c.version, c.slug, c.description, c.created_at, c.created_by_id, c.organization_id,
       creator.name AS created_by_name
FROM component c
  INNER JOIN "user" creator ON c.created_by_id = creator.id
WHERE c.organization_id = $1
  AND (
    $2::timestamp IS NULL
    OR (c.created_at, c.id) < ($2::timestamp, $3::uuid)
  )
ORDER BY c.created_at DESC, c.id DESC
LIMIT $4
`

type GetComponentsParams struct {
	OrganizationID  uuid.UUID        `json:"organization_id"`
	CursorCreatedAt pgtype.Timestamp `json:"cursor_created_at"`
	CursorID        *uuid.UUID       `json:"cursor_id"`
	LimitPlusOne    int32            `json:"limit_plus_one"`
}

type GetComponentsRow struct {
	ID                  uuid.UUID        `json:"id"`
	PreviousComponentID *uuid.UUID       `json:"previous_component_id"`
	Name                string           `json:"name"`
	Version             string           `json:"version"`
	Slug                string           `json:"slug"`
	Description         *string          `json:"description"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	CreatedByID         uuid.UUID        `json:"created_by_id"`
	OrganizationID      uuid.UUID        `json:"organization_id"`
	CreatedByName       string           `json:"created_by_name"`
}

// Cursor (keyset) pagination: ordered by created_at DESC, id DESC (id
// tie-breaks created_at, which is not guaranteed unique). This replaces
// the previous ORDER BY name ASC, version DESC, created_at DESC -- a
// mixed-direction, multi-column sort that isn't expressible as a single
// keyset comparison without a much more complex predicate; consistency
// with every other paginated endpoint's (created_at, id) convention was
// judged more valuable than preserving that incidental grouping, and no
// endpoint contract ever documented it as guaranteed. Pass
// limit_plus_one = requested limit + 1 so the caller can detect whether a
// further page exists without a separate COUNT query. On the first page,
// pass NULL for both cursor_created_at and cursor_id.
func (q *Queries) GetComponents(ctx context.Context, arg GetComponentsParams) ([]GetComponentsRow, error) {
	rows, err := q.db.Query(ctx, getComponents,
		arg.OrganizationID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitPlusOne,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetComponentsRow
	for rows.Next() {
		var i GetComponentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PreviousComponentID,
			&i.Name,
			&i.Version,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.CreatedByID,
			&i.OrganizationID,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getComponentsByReleaseID = `-- name: GetComponentsByReleaseID :many
SELECT c.id, c.previous_component_id, c.name, c.version, c.slug, c.description, c.created_at, c.created_by_id, c.organization_id,
       creator.name AS created_by_name
FROM component c
  INNER JOIN component_release cr ON cr.component_id = c.id
  INNER JOIN "user" creator ON c.created_by_id = creator.id
WHERE cr.release_id = $1
  AND cr.organization_id = $2
`

type GetComponentsByReleaseIDParams struct {
	ReleaseID      uuid.UUID `json:"release_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type GetComponentsByReleaseIDRow struct {
	ID                  uuid.UUID        `json:"id"`
	PreviousComponentID *uuid.UUID       `json:"previous_component_id"`
	Name                string           `json:"name"`
	Version             string           `json:"version"`
	Slug                string           `json:"slug"`
	Description         *string          `json:"description"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	CreatedByID         uuid.UUID        `json:"created_by_id"`
	OrganizationID      uuid.UUID        `json:"organization_id"`
	CreatedByName       string           `json:"created_by_name"`
}

func (q *Queries) GetComponentsByReleaseID(ctx context.Context, arg GetComponentsByReleaseIDParams) ([]GetComponentsByReleaseIDRow, error) {
	rows, err := q.db.Query(ctx, getComponentsByReleaseID, arg.ReleaseID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetComponentsByReleaseIDRow
	for rows.Next() {
		var i GetComponentsByReleaseIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PreviousComponentID,
			&i.Name,
			&i.Version,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.CreatedByID,
			&i.OrganizationID,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrphanComponentIDs = `-- name: GetOrphanComponentIDs :many
SELECT c.id
FROM component c
WHERE c.organization_id = $1
  AND NOT EXISTS (
    SELECT 1 FROM component_release cr
    WHERE cr.component_id = c.id
  )
`

func (q *Queries) GetOrphanComponentIDs(ctx context.Context, organizationID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getOrphanComponentIDs, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllComponentsFromRelease = `-- name: RemoveAllComponentsFromRelease :exec
DELETE FROM component_release
WHERE release_id = $1
  AND organization_id = $2
`

type RemoveAllComponentsFromReleaseParams struct {
	ReleaseID      uuid.UUID `json:"release_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) RemoveAllComponentsFromRelease(ctx context.Context, arg RemoveAllComponentsFromReleaseParams) error {
	_, err := q.db.Exec(ctx, removeAllComponentsFromRelease, arg.ReleaseID, arg.OrganizationID)
	return err
}

const removeComponentFromRelease = `-- name: RemoveComponentFromRelease :exec
DELETE FROM component_release
WHERE component_id = $1
  AND release_id = $2
  AND organization_id = $3
`

type RemoveComponentFromReleaseParams struct {
	ComponentID    uuid.UUID `json:"component_id"`
	ReleaseID      uuid.UUID `json:"release_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) RemoveComponentFromRelease(ctx context.Context, arg RemoveComponentFromReleaseParams) error {
	_, err := q.db.Exec(ctx, removeComponentFromRelease, arg.ComponentID, arg.ReleaseID, arg.OrganizationID)
	return err
}

const updateComponent = `-- name: UpdateComponent :one
UPDATE component
SET name = COALESCE($1, name),
    version = COALESCE($2, version),
    slug = COALESCE($3, slug),
    description = COALESCE($4, description)
WHERE id = $5
  AND organization_id = $6
RETURNING id, previous_component_id, name, version, slug, description, created_at, created_by_id, organization_id
`

type UpdateComponentParams struct {
	NewName        *string   `json:"new_name"`
	NewVersion     *string   `json:"new_version"`
	NewSlug        *string   `json:"new_slug"`
	NewDescription *string   `json:"new_description"`
	ComponentID    uuid.UUID `json:"component_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) UpdateComponent(ctx context.Context, arg UpdateComponentParams) (Component, error) {
	row := q.db.QueryRow(ctx, updateComponent,
		arg.NewName,
		arg.NewVersion,
		arg.NewSlug,
		arg.NewDescription,
		arg.ComponentID,
		arg.OrganizationID,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.PreviousComponentID,
		&i.Name,
		&i.Version,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.OrganizationID,
	)
	return i, err
}
