// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
)

type FeatureFlag struct {
	ID             uuid.UUID `json:"id"`
	Type           string    `json:"type"`
	Variants       []byte    `json:"variants"`
	TargetingRules []byte    `json:"targeting_rules"`
	Name           string    `json:"name"`
	Description    *string   `json:"description"`
	Slug           string    `json:"slug"`
	Metadata       []byte    `json:"metadata"`
	Enabled        bool      `json:"enabled"`
	EventName      string    `json:"event_name"`
	OrganizationID uuid.UUID `json:"organization_id"`
	DefaultVariant []byte    `json:"default_variant"`
}
