// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
)

type AddonOverrideBehavior string

const (
	AddonOverrideBehaviorADD      AddonOverrideBehavior = "ADD"
	AddonOverrideBehaviorOVERRIDE AddonOverrideBehavior = "OVERRIDE"
	AddonOverrideBehaviorMAX      AddonOverrideBehavior = "MAX"
)

func (e *AddonOverrideBehavior) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AddonOverrideBehavior(s)
	case string:
		*e = AddonOverrideBehavior(s)
	default:
		return fmt.Errorf("unsupported scan type for AddonOverrideBehavior: %T", src)
	}
	return nil
}

type NullAddonOverrideBehavior struct {
	AddonOverrideBehavior AddonOverrideBehavior `json:"addon_override_behavior"`
	Valid                 bool                  `json:"valid"` // Valid is true if AddonOverrideBehavior is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAddonOverrideBehavior) Scan(value interface{}) error {
	if value == nil {
		ns.AddonOverrideBehavior, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AddonOverrideBehavior.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAddonOverrideBehavior) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AddonOverrideBehavior), nil
}

type BillingModel string

const (
	BillingModelFLATFEE    BillingModel = "FLAT_FEE"
	BillingModelUSAGEBASED BillingModel = "USAGE_BASED"
	BillingModelOVERAGE    BillingModel = "OVERAGE"
)

func (e *BillingModel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingModel(s)
	case string:
		*e = BillingModel(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingModel: %T", src)
	}
	return nil
}

type NullBillingModel struct {
	BillingModel BillingModel `json:"billing_model"`
	Valid        bool         `json:"valid"` // Valid is true if BillingModel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingModel) Scan(value interface{}) error {
	if value == nil {
		ns.BillingModel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingModel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingModel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingModel), nil
}

type BillingPeriod string

const (
	BillingPeriodMONTHLY    BillingPeriod = "MONTHLY"
	BillingPeriodQUARTERLY  BillingPeriod = "QUARTERLY"
	BillingPeriodSEMIANNUAL BillingPeriod = "SEMI_ANNUAL"
	BillingPeriodANNUAL     BillingPeriod = "ANNUAL"
)

func (e *BillingPeriod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingPeriod(s)
	case string:
		*e = BillingPeriod(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingPeriod: %T", src)
	}
	return nil
}

type NullBillingPeriod struct {
	BillingPeriod BillingPeriod `json:"billing_period"`
	Valid         bool          `json:"valid"` // Valid is true if BillingPeriod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingPeriod) Scan(value interface{}) error {
	if value == nil {
		ns.BillingPeriod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingPeriod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingPeriod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingPeriod), nil
}

type BillingTiming string

const (
	BillingTimingADVANCE BillingTiming = "ADVANCE"
	BillingTimingARREARS BillingTiming = "ARREARS"
)

func (e *BillingTiming) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingTiming(s)
	case string:
		*e = BillingTiming(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingTiming: %T", src)
	}
	return nil
}

type NullBillingTiming struct {
	BillingTiming BillingTiming `json:"billing_timing"`
	Valid         bool          `json:"valid"` // Valid is true if BillingTiming is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingTiming) Scan(value interface{}) error {
	if value == nil {
		ns.BillingTiming, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingTiming.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingTiming) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingTiming), nil
}

type EntitlementType string

const (
	EntitlementTypeBOOLEAN        EntitlementType = "BOOLEAN"
	EntitlementTypeNUMBER         EntitlementType = "NUMBER"
	EntitlementTypeCONFIG         EntitlementType = "CONFIG"
	EntitlementTypeNUMBERAICREDIT EntitlementType = "NUMBER_AI_CREDIT"
)

func (e *EntitlementType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntitlementType(s)
	case string:
		*e = EntitlementType(s)
	default:
		return fmt.Errorf("unsupported scan type for EntitlementType: %T", src)
	}
	return nil
}

type NullEntitlementType struct {
	EntitlementType EntitlementType `json:"entitlement_type"`
	Valid           bool            `json:"valid"` // Valid is true if EntitlementType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntitlementType) Scan(value interface{}) error {
	if value == nil {
		ns.EntitlementType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntitlementType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntitlementType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntitlementType), nil
}

type LicenseLifecycleState string

const (
	LicenseLifecycleStateDRAFT     LicenseLifecycleState = "DRAFT"
	LicenseLifecycleStatePUBLISHED LicenseLifecycleState = "PUBLISHED"
	LicenseLifecycleStateARCHIVED  LicenseLifecycleState = "ARCHIVED"
)

func (e *LicenseLifecycleState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LicenseLifecycleState(s)
	case string:
		*e = LicenseLifecycleState(s)
	default:
		return fmt.Errorf("unsupported scan type for LicenseLifecycleState: %T", src)
	}
	return nil
}

type NullLicenseLifecycleState struct {
	LicenseLifecycleState LicenseLifecycleState `json:"license_lifecycle_state"`
	Valid                 bool                  `json:"valid"` // Valid is true if LicenseLifecycleState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLicenseLifecycleState) Scan(value interface{}) error {
	if value == nil {
		ns.LicenseLifecycleState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LicenseLifecycleState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLicenseLifecycleState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LicenseLifecycleState), nil
}

type PricingType string

const (
	PricingTypeFREE   PricingType = "FREE"
	PricingTypePAID   PricingType = "PAID"
	PricingTypeCUSTOM PricingType = "CUSTOM"
)

func (e *PricingType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PricingType(s)
	case string:
		*e = PricingType(s)
	default:
		return fmt.Errorf("unsupported scan type for PricingType: %T", src)
	}
	return nil
}

type NullPricingType struct {
	PricingType PricingType `json:"pricing_type"`
	Valid       bool        `json:"valid"` // Valid is true if PricingType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPricingType) Scan(value interface{}) error {
	if value == nil {
		ns.PricingType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PricingType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPricingType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PricingType), nil
}
