// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AggregationMethod string

const (
	AggregationMethodSUM     AggregationMethod = "SUM"
	AggregationMethodCOUNT   AggregationMethod = "COUNT"
	AggregationMethodAVERAGE AggregationMethod = "AVERAGE"
	AggregationMethodMAX     AggregationMethod = "MAX"
	AggregationMethodMIN     AggregationMethod = "MIN"
	AggregationMethodLATEST  AggregationMethod = "LATEST"
)

func (e *AggregationMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AggregationMethod(s)
	case string:
		*e = AggregationMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for AggregationMethod: %T", src)
	}
	return nil
}

type NullAggregationMethod struct {
	AggregationMethod AggregationMethod `json:"aggregation_method"`
	Valid             bool              `json:"valid"` // Valid is true if AggregationMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAggregationMethod) Scan(value interface{}) error {
	if value == nil {
		ns.AggregationMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AggregationMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAggregationMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AggregationMethod), nil
}

type EntitlementResetAnchor string

const (
	EntitlementResetAnchorCALENDAR     EntitlementResetAnchor = "CALENDAR"
	EntitlementResetAnchorLICENSESTART EntitlementResetAnchor = "LICENSE_START"
)

func (e *EntitlementResetAnchor) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntitlementResetAnchor(s)
	case string:
		*e = EntitlementResetAnchor(s)
	default:
		return fmt.Errorf("unsupported scan type for EntitlementResetAnchor: %T", src)
	}
	return nil
}

type NullEntitlementResetAnchor struct {
	EntitlementResetAnchor EntitlementResetAnchor `json:"entitlement_reset_anchor"`
	Valid                  bool                   `json:"valid"` // Valid is true if EntitlementResetAnchor is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntitlementResetAnchor) Scan(value interface{}) error {
	if value == nil {
		ns.EntitlementResetAnchor, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntitlementResetAnchor.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntitlementResetAnchor) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntitlementResetAnchor), nil
}

type EntitlementResetPeriod string

const (
	EntitlementResetPeriodHOUR  EntitlementResetPeriod = "HOUR"
	EntitlementResetPeriodDAY   EntitlementResetPeriod = "DAY"
	EntitlementResetPeriodWEEK  EntitlementResetPeriod = "WEEK"
	EntitlementResetPeriodMONTH EntitlementResetPeriod = "MONTH"
	EntitlementResetPeriodYEAR  EntitlementResetPeriod = "YEAR"
)

func (e *EntitlementResetPeriod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntitlementResetPeriod(s)
	case string:
		*e = EntitlementResetPeriod(s)
	default:
		return fmt.Errorf("unsupported scan type for EntitlementResetPeriod: %T", src)
	}
	return nil
}

type NullEntitlementResetPeriod struct {
	EntitlementResetPeriod EntitlementResetPeriod `json:"entitlement_reset_period"`
	Valid                  bool                   `json:"valid"` // Valid is true if EntitlementResetPeriod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntitlementResetPeriod) Scan(value interface{}) error {
	if value == nil {
		ns.EntitlementResetPeriod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntitlementResetPeriod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntitlementResetPeriod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntitlementResetPeriod), nil
}

type EntitlementType string

const (
	EntitlementTypeBOOLEAN        EntitlementType = "BOOLEAN"
	EntitlementTypeNUMBER         EntitlementType = "NUMBER"
	EntitlementTypeCONFIG         EntitlementType = "CONFIG"
	EntitlementTypeNUMBERAICREDIT EntitlementType = "NUMBER_AI_CREDIT"
)

func (e *EntitlementType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntitlementType(s)
	case string:
		*e = EntitlementType(s)
	default:
		return fmt.Errorf("unsupported scan type for EntitlementType: %T", src)
	}
	return nil
}

type NullEntitlementType struct {
	EntitlementType EntitlementType `json:"entitlement_type"`
	Valid           bool            `json:"valid"` // Valid is true if EntitlementType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntitlementType) Scan(value interface{}) error {
	if value == nil {
		ns.EntitlementType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntitlementType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntitlementType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntitlementType), nil
}

type Entitlement struct {
	ID                      uuid.UUID               `json:"id"`
	Name                    string                  `json:"name"`
	Slug                    string                  `json:"slug"`
	Description             *string                 `json:"description"`
	Type                    EntitlementType         `json:"type"`
	AggregationMethod       *AggregationMethod      `json:"aggregation_method"`
	OrganizationID          uuid.UUID               `json:"organization_id"`
	Icon                    *string                 `json:"icon"`
	UnitSingular            *string                 `json:"unit_singular"`
	UnitPlural              *string                 `json:"unit_plural"`
	SaleUnitSingular        *string                 `json:"sale_unit_singular"`
	SaleUnitPlural          *string                 `json:"sale_unit_plural"`
	SaleUnitFactor          *float64                `json:"sale_unit_factor"`
	UserFacing              bool                    `json:"user_facing"`
	DisplayOrder            int32                   `json:"display_order"`
	WarningThresholdPercent int16                   `json:"warning_threshold_percent"`
	ResetPeriod             *EntitlementResetPeriod `json:"reset_period"`
	ResetAnchor             *EntitlementResetAnchor `json:"reset_anchor"`
	CreatedAt               pgtype.Timestamp        `json:"created_at"`
	UpdatedAt               pgtype.Timestamp        `json:"updated_at"`
}

type EntitlementGroup struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Description    *string   `json:"description"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type EntitlementGroupMembership struct {
	EntitlementGroupID uuid.UUID `json:"entitlement_group_id"`
	EntitlementID      uuid.UUID `json:"entitlement_id"`
	OrganizationID     uuid.UUID `json:"organization_id"`
}
