// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment_zone.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDeploymentZone = `-- name: CreateDeploymentZone :one
WITH inserted AS (
  INSERT INTO deployment_zone (name, slug, description, type, metadata, created_at, created_by_id, updated_at, updated_by_id,
                               organization_id)
  SELECT $1,
         $2,
         $3,
         $4,
         $5,
         now(),
         uo.user_id,
         now(),
         uo.user_id,
         uo.organization_id
  FROM user_on_organization uo
  WHERE uo.organization_id = $6
    AND uo.user_id = $7
    AND uo.deleted_at IS NULL
  RETURNING id, name, slug, type, metadata, description, created_at, created_by_id, updated_at, updated_by_id, organization_id
)
SELECT inserted.id, inserted.name, inserted.slug, inserted.type, inserted.metadata, inserted.description, inserted.created_at, inserted.created_by_id, inserted.updated_at, inserted.updated_by_id, inserted.organization_id,
       creator.name AS created_by_name,
       updater.name AS updated_by_name
FROM inserted
  INNER JOIN "user" creator ON inserted.created_by_id = creator.id
  INNER JOIN "user" updater ON inserted.updated_by_id = updater.id
`

type CreateDeploymentZoneParams struct {
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Description    string    `json:"description"`
	Type           string    `json:"type"`
	Metadata       []byte    `json:"metadata"`
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

type CreateDeploymentZoneRow struct {
	ID             uuid.UUID        `json:"id"`
	Name           string           `json:"name"`
	Slug           string           `json:"slug"`
	Type           string           `json:"type"`
	Metadata       []byte           `json:"metadata"`
	Description    string           `json:"description"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	CreatedByID    uuid.UUID        `json:"created_by_id"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	UpdatedByID    uuid.UUID        `json:"updated_by_id"`
	OrganizationID uuid.UUID        `json:"organization_id"`
	CreatedByName  string           `json:"created_by_name"`
	UpdatedByName  string           `json:"updated_by_name"`
}

func (q *Queries) CreateDeploymentZone(ctx context.Context, arg CreateDeploymentZoneParams) (CreateDeploymentZoneRow, error) {
	row := q.db.QueryRow(ctx, createDeploymentZone,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Type,
		arg.Metadata,
		arg.OrganizationID,
		arg.UserID,
	)
	var i CreateDeploymentZoneRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.Metadata,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.UpdatedAt,
		&i.UpdatedByID,
		&i.OrganizationID,
		&i.CreatedByName,
		&i.UpdatedByName,
	)
	return i, err
}

const deleteDeploymentZone = `-- name: DeleteDeploymentZone :one
WITH deleted AS (
  DELETE FROM deployment_zone dz
  WHERE dz.id = $1
    AND dz.organization_id = $2
  RETURNING dz.id, dz.name, dz.slug, dz.type, dz.metadata, dz.description, dz.created_at, dz.created_by_id, dz.updated_at, dz.updated_by_id, dz.organization_id
)
SELECT deleted.id, deleted.name, deleted.slug, deleted.type, deleted.metadata, deleted.description, deleted.created_at, deleted.created_by_id, deleted.updated_at, deleted.updated_by_id, deleted.organization_id,
       creator.name AS created_by_name,
       updater.name AS updated_by_name
FROM deleted
  INNER JOIN "user" creator ON deleted.created_by_id = creator.id
  INNER JOIN "user" updater ON deleted.updated_by_id = updater.id
`

type DeleteDeploymentZoneParams struct {
	DeploymentZoneID uuid.UUID `json:"deployment_zone_id"`
	OrganizationID   uuid.UUID `json:"organization_id"`
}

type DeleteDeploymentZoneRow struct {
	ID             uuid.UUID        `json:"id"`
	Name           string           `json:"name"`
	Slug           string           `json:"slug"`
	Type           string           `json:"type"`
	Metadata       []byte           `json:"metadata"`
	Description    string           `json:"description"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	CreatedByID    uuid.UUID        `json:"created_by_id"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	UpdatedByID    uuid.UUID        `json:"updated_by_id"`
	OrganizationID uuid.UUID        `json:"organization_id"`
	CreatedByName  string           `json:"created_by_name"`
	UpdatedByName  string           `json:"updated_by_name"`
}

func (q *Queries) DeleteDeploymentZone(ctx context.Context, arg DeleteDeploymentZoneParams) (DeleteDeploymentZoneRow, error) {
	row := q.db.QueryRow(ctx, deleteDeploymentZone, arg.DeploymentZoneID, arg.OrganizationID)
	var i DeleteDeploymentZoneRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.Metadata,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.UpdatedAt,
		&i.UpdatedByID,
		&i.OrganizationID,
		&i.CreatedByName,
		&i.UpdatedByName,
	)
	return i, err
}

const deleteDeploymentZoneBySlug = `-- name: DeleteDeploymentZoneBySlug :one
WITH deleted AS (
  DELETE FROM deployment_zone dz
  WHERE dz.slug = $1
    AND dz.organization_id = $2
  RETURNING dz.id, dz.name, dz.slug, dz.type, dz.metadata, dz.description, dz.created_at, dz.created_by_id, dz.updated_at, dz.updated_by_id, dz.organization_id
)
SELECT deleted.id, deleted.name, deleted.slug, deleted.type, deleted.metadata, deleted.description, deleted.created_at, deleted.created_by_id, deleted.updated_at, deleted.updated_by_id, deleted.organization_id,
       creator.name AS created_by_name,
       updater.name AS updated_by_name
FROM deleted
  INNER JOIN "user" creator ON deleted.created_by_id = creator.id
  INNER JOIN "user" updater ON deleted.updated_by_id = updater.id
`

type DeleteDeploymentZoneBySlugParams struct {
	Slug           string    `json:"slug"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type DeleteDeploymentZoneBySlugRow struct {
	ID             uuid.UUID        `json:"id"`
	Name           string           `json:"name"`
	Slug           string           `json:"slug"`
	Type           string           `json:"type"`
	Metadata       []byte           `json:"metadata"`
	Description    string           `json:"description"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	CreatedByID    uuid.UUID        `json:"created_by_id"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	UpdatedByID    uuid.UUID        `json:"updated_by_id"`
	OrganizationID uuid.UUID        `json:"organization_id"`
	CreatedByName  string           `json:"created_by_name"`
	UpdatedByName  string           `json:"updated_by_name"`
}

func (q *Queries) DeleteDeploymentZoneBySlug(ctx context.Context, arg DeleteDeploymentZoneBySlugParams) (DeleteDeploymentZoneBySlugRow, error) {
	row := q.db.QueryRow(ctx, deleteDeploymentZoneBySlug, arg.Slug, arg.OrganizationID)
	var i DeleteDeploymentZoneBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.Metadata,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.UpdatedAt,
		&i.UpdatedByID,
		&i.OrganizationID,
		&i.CreatedByName,
		&i.UpdatedByName,
	)
	return i, err
}

const getDeploymentZones = `-- name: GetDeploymentZones :many
SELECT dz.id,
       dz.name,
       dz.slug,
       dz.description,
       dz.type,
       dz.metadata,
       dz.created_by_id,
       creator.name AS created_by_name,
       dz.created_at,
       dz.updated_by_id,
       updater.name AS updated_by_name,
       dz.updated_at,
       dz.organization_id,
       latest_deployment.release_id
FROM deployment_zone dz
  INNER JOIN "user" creator ON dz.created_by_id = creator.id
  INNER JOIN "user" updater ON dz.updated_by_id = updater.id
  LEFT JOIN LATERAL (
    SELECT d.release_id
    FROM deployment d
    WHERE d.deployment_zone_id = dz.id
      AND d.organization_id = dz.organization_id
    ORDER BY d.created_at DESC, d.seq DESC
    LIMIT 1
  ) AS latest_deployment ON TRUE
WHERE dz.organization_id = $1
`

type GetDeploymentZonesRow struct {
	ID             uuid.UUID        `json:"id"`
	Name           string           `json:"name"`
	Slug           string           `json:"slug"`
	Description    string           `json:"description"`
	Type           string           `json:"type"`
	Metadata       []byte           `json:"metadata"`
	CreatedByID    uuid.UUID        `json:"created_by_id"`
	CreatedByName  string           `json:"created_by_name"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedByID    uuid.UUID        `json:"updated_by_id"`
	UpdatedByName  string           `json:"updated_by_name"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	OrganizationID uuid.UUID        `json:"organization_id"`
	ReleaseID      uuid.UUID        `json:"release_id"`
}

// Unbounded on purpose: also used by metadatafields/dryrunmetadatafield,
// which must validate a candidate JSON schema against every deployment
// zone in the organization, not just one page.
// GetDeploymentZonesByCursor (below) is the cursor-paginated variant for
// the list-facing caller (REST getdeploymentzones).
func (q *Queries) GetDeploymentZones(ctx context.Context, organizationID uuid.UUID) ([]GetDeploymentZonesRow, error) {
	rows, err := q.db.Query(ctx, getDeploymentZones, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeploymentZonesRow
	for rows.Next() {
		var i GetDeploymentZonesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.Metadata,
			&i.CreatedByID,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedByID,
			&i.UpdatedByName,
			&i.UpdatedAt,
			&i.OrganizationID,
			&i.ReleaseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeploymentZonesByCursor = `-- name: GetDeploymentZonesByCursor :many
SELECT dz.id,
       dz.name,
       dz.slug,
       dz.description,
       dz.type,
       dz.metadata,
       dz.created_by_id,
       creator.name AS created_by_name,
       dz.created_at,
       dz.updated_by_id,
       updater.name AS updated_by_name,
       dz.updated_at,
       dz.organization_id,
       latest_deployment.release_id
FROM deployment_zone dz
  INNER JOIN "user" creator ON dz.created_by_id = creator.id
  INNER JOIN "user" updater ON dz.updated_by_id = updater.id
  LEFT JOIN LATERAL (
    SELECT d.release_id
    FROM deployment d
    WHERE d.deployment_zone_id = dz.id
      AND d.organization_id = dz.organization_id
    ORDER BY d.created_at DESC, d.seq DESC
    LIMIT 1
  ) AS latest_deployment ON TRUE
WHERE dz.organization_id = $1
  AND (
    $2::timestamp IS NULL
    OR (dz.created_at, dz.id) < ($2::timestamp, $3::uuid)
  )
ORDER BY dz.created_at DESC, dz.id DESC
LIMIT $4
`

type GetDeploymentZonesByCursorParams struct {
	OrganizationID  uuid.UUID        `json:"organization_id"`
	CursorCreatedAt pgtype.Timestamp `json:"cursor_created_at"`
	CursorID        *uuid.UUID       `json:"cursor_id"`
	LimitPlusOne    int32            `json:"limit_plus_one"`
}

type GetDeploymentZonesByCursorRow struct {
	ID             uuid.UUID        `json:"id"`
	Name           string           `json:"name"`
	Slug           string           `json:"slug"`
	Description    string           `json:"description"`
	Type           string           `json:"type"`
	Metadata       []byte           `json:"metadata"`
	CreatedByID    uuid.UUID        `json:"created_by_id"`
	CreatedByName  string           `json:"created_by_name"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedByID    uuid.UUID        `json:"updated_by_id"`
	UpdatedByName  string           `json:"updated_by_name"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	OrganizationID uuid.UUID        `json:"organization_id"`
	ReleaseID      uuid.UUID        `json:"release_id"`
}

// Cursor (keyset) pagination: ordered by created_at DESC, id DESC (id
// tie-breaks created_at, which is not guaranteed unique). Pass
// limit_plus_one = requested limit + 1 so the caller can detect whether a
// further page exists without a separate COUNT query. On the first page,
// pass NULL for both cursor_created_at and cursor_id.
func (q *Queries) GetDeploymentZonesByCursor(ctx context.Context, arg GetDeploymentZonesByCursorParams) ([]GetDeploymentZonesByCursorRow, error) {
	rows, err := q.db.Query(ctx, getDeploymentZonesByCursor,
		arg.OrganizationID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitPlusOne,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeploymentZonesByCursorRow
	for rows.Next() {
		var i GetDeploymentZonesByCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.Metadata,
			&i.CreatedByID,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedByID,
			&i.UpdatedByName,
			&i.UpdatedAt,
			&i.OrganizationID,
			&i.ReleaseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeploymentZonesByIDs = `-- name: GetDeploymentZonesByIDs :many
SELECT dz.id,
       dz.name,
       dz.slug,
       dz.description,
       dz.type,
       dz.metadata,
       dz.created_by_id,
       creator.name AS created_by_name,
       dz.created_at,
       dz.updated_by_id,
       updater.name AS updated_by_name,
       dz.updated_at,
       dz.organization_id,
       latest_deployment.release_id
FROM deployment_zone dz
  INNER JOIN "user" creator ON dz.created_by_id = creator.id
  INNER JOIN "user" updater ON dz.updated_by_id = updater.id
  LEFT JOIN LATERAL (
    SELECT d.release_id
    FROM deployment d
    WHERE d.deployment_zone_id = dz.id
      AND d.organization_id = dz.organization_id
    ORDER BY d.created_at DESC, d.seq DESC
    LIMIT 1
  ) AS latest_deployment ON TRUE
WHERE dz.organization_id = $1
  AND dz.id = ANY ($2::uuid[])
`

type GetDeploymentZonesByIDsParams struct {
	OrganizationID    uuid.UUID   `json:"organization_id"`
	DeploymentZoneIds []uuid.UUID `json:"deployment_zone_ids"`
}

type GetDeploymentZonesByIDsRow struct {
	ID             uuid.UUID        `json:"id"`
	Name           string           `json:"name"`
	Slug           string           `json:"slug"`
	Description    string           `json:"description"`
	Type           string           `json:"type"`
	Metadata       []byte           `json:"metadata"`
	CreatedByID    uuid.UUID        `json:"created_by_id"`
	CreatedByName  string           `json:"created_by_name"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedByID    uuid.UUID        `json:"updated_by_id"`
	UpdatedByName  string           `json:"updated_by_name"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	OrganizationID uuid.UUID        `json:"organization_id"`
	ReleaseID      uuid.UUID        `json:"release_id"`
}

func (q *Queries) GetDeploymentZonesByIDs(ctx context.Context, arg GetDeploymentZonesByIDsParams) ([]GetDeploymentZonesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getDeploymentZonesByIDs, arg.OrganizationID, arg.DeploymentZoneIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeploymentZonesByIDsRow
	for rows.Next() {
		var i GetDeploymentZonesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.Metadata,
			&i.CreatedByID,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedByID,
			&i.UpdatedByName,
			&i.UpdatedAt,
			&i.OrganizationID,
			&i.ReleaseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeploymentZonesByReleaseIDs = `-- name: GetDeploymentZonesByReleaseIDs :many
SELECT DISTINCT ON (d.release_id, dz.id)
       d.release_id,
       dz.id,
       dz.name,
       dz.slug,
       dz.description,
       dz.type,
       dz.metadata,
       dz.created_by_id,
       creator.name AS created_by_name,
       dz.created_at,
       dz.updated_by_id,
       updater.name AS updated_by_name,
       dz.updated_at,
       dz.organization_id,
       current_deployment.release_id AS current_release_id
FROM deployment d
  INNER JOIN deployment_zone dz ON dz.id = d.deployment_zone_id
  INNER JOIN "user" creator ON dz.created_by_id = creator.id
  INNER JOIN "user" updater ON dz.updated_by_id = updater.id
  LEFT JOIN LATERAL (
    SELECT latest.release_id
    FROM deployment latest
    WHERE latest.organization_id = d.organization_id
      AND latest.deployment_zone_id = dz.id
    ORDER BY latest.created_at DESC, latest.seq DESC
    LIMIT 1
  ) AS current_deployment ON TRUE
WHERE d.organization_id = $1
  AND d.release_id = ANY ($2::uuid[])
ORDER BY d.release_id, dz.id, d.created_at DESC
`

type GetDeploymentZonesByReleaseIDsParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	ReleaseIds     []uuid.UUID `json:"release_ids"`
}

type GetDeploymentZonesByReleaseIDsRow struct {
	ReleaseID        uuid.UUID        `json:"release_id"`
	ID               uuid.UUID        `json:"id"`
	Name             string           `json:"name"`
	Slug             string           `json:"slug"`
	Description      string           `json:"description"`
	Type             string           `json:"type"`
	Metadata         []byte           `json:"metadata"`
	CreatedByID      uuid.UUID        `json:"created_by_id"`
	CreatedByName    string           `json:"created_by_name"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedByID      uuid.UUID        `json:"updated_by_id"`
	UpdatedByName    string           `json:"updated_by_name"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	OrganizationID   uuid.UUID        `json:"organization_id"`
	CurrentReleaseID uuid.UUID        `json:"current_release_id"`
}

func (q *Queries) GetDeploymentZonesByReleaseIDs(ctx context.Context, arg GetDeploymentZonesByReleaseIDsParams) ([]GetDeploymentZonesByReleaseIDsRow, error) {
	rows, err := q.db.Query(ctx, getDeploymentZonesByReleaseIDs, arg.OrganizationID, arg.ReleaseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeploymentZonesByReleaseIDsRow
	for rows.Next() {
		var i GetDeploymentZonesByReleaseIDsRow
		if err := rows.Scan(
			&i.ReleaseID,
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.Metadata,
			&i.CreatedByID,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedByID,
			&i.UpdatedByName,
			&i.UpdatedAt,
			&i.OrganizationID,
			&i.CurrentReleaseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOneDeploymentZone = `-- name: GetOneDeploymentZone :one
SELECT dz.id,
       dz.name,
       dz.slug,
       dz.description,
       dz.type,
       dz.metadata,
       dz.created_by_id,
       creator.name AS created_by_name,
       dz.created_at,
       dz.updated_by_id,
       updater.name AS updated_by_name,
       dz.updated_at,
       dz.organization_id,
       latest_deployment.release_id
FROM deployment_zone dz
  INNER JOIN "user" creator ON dz.created_by_id = creator.id
  INNER JOIN "user" updater ON dz.updated_by_id = updater.id
  LEFT JOIN LATERAL (
    SELECT d.release_id
    FROM deployment d
    WHERE d.deployment_zone_id = dz.id
      AND d.organization_id = dz.organization_id
    ORDER BY d.created_at DESC, d.seq DESC
    LIMIT 1
  ) AS latest_deployment ON TRUE
WHERE dz.organization_id = $1
  AND dz.id = $2
`

type GetOneDeploymentZoneParams struct {
	OrganizationID   uuid.UUID `json:"organization_id"`
	DeploymentZoneID uuid.UUID `json:"deployment_zone_id"`
}

type GetOneDeploymentZoneRow struct {
	ID             uuid.UUID        `json:"id"`
	Name           string           `json:"name"`
	Slug           string           `json:"slug"`
	Description    string           `json:"description"`
	Type           string           `json:"type"`
	Metadata       []byte           `json:"metadata"`
	CreatedByID    uuid.UUID        `json:"created_by_id"`
	CreatedByName  string           `json:"created_by_name"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedByID    uuid.UUID        `json:"updated_by_id"`
	UpdatedByName  string           `json:"updated_by_name"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	OrganizationID uuid.UUID        `json:"organization_id"`
	ReleaseID      uuid.UUID        `json:"release_id"`
}

func (q *Queries) GetOneDeploymentZone(ctx context.Context, arg GetOneDeploymentZoneParams) (GetOneDeploymentZoneRow, error) {
	row := q.db.QueryRow(ctx, getOneDeploymentZone, arg.OrganizationID, arg.DeploymentZoneID)
	var i GetOneDeploymentZoneRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Type,
		&i.Metadata,
		&i.CreatedByID,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedByID,
		&i.UpdatedByName,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.ReleaseID,
	)
	return i, err
}

const getOneDeploymentZoneBySlug = `-- name: GetOneDeploymentZoneBySlug :one
SELECT dz.id,
       dz.name,
       dz.slug,
       dz.description,
       dz.type,
       dz.metadata,
       dz.created_by_id,
       creator.name AS created_by_name,
       dz.created_at,
       dz.updated_by_id,
       updater.name AS updated_by_name,
       dz.updated_at,
       dz.organization_id,
       latest_deployment.release_id
FROM deployment_zone dz
  INNER JOIN "user" creator ON dz.created_by_id = creator.id
  INNER JOIN "user" updater ON dz.updated_by_id = updater.id
  LEFT JOIN LATERAL (
    SELECT d.release_id
    FROM deployment d
    WHERE d.deployment_zone_id = dz.id
      AND d.organization_id = dz.organization_id
    ORDER BY d.created_at DESC, d.seq DESC
    LIMIT 1
  ) AS latest_deployment ON TRUE
WHERE dz.organization_id = $1
  AND dz.slug = $2
`

type GetOneDeploymentZoneBySlugParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Slug           string    `json:"slug"`
}

type GetOneDeploymentZoneBySlugRow struct {
	ID             uuid.UUID        `json:"id"`
	Name           string           `json:"name"`
	Slug           string           `json:"slug"`
	Description    string           `json:"description"`
	Type           string           `json:"type"`
	Metadata       []byte           `json:"metadata"`
	CreatedByID    uuid.UUID        `json:"created_by_id"`
	CreatedByName  string           `json:"created_by_name"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedByID    uuid.UUID        `json:"updated_by_id"`
	UpdatedByName  string           `json:"updated_by_name"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	OrganizationID uuid.UUID        `json:"organization_id"`
	ReleaseID      uuid.UUID        `json:"release_id"`
}

func (q *Queries) GetOneDeploymentZoneBySlug(ctx context.Context, arg GetOneDeploymentZoneBySlugParams) (GetOneDeploymentZoneBySlugRow, error) {
	row := q.db.QueryRow(ctx, getOneDeploymentZoneBySlug, arg.OrganizationID, arg.Slug)
	var i GetOneDeploymentZoneBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Type,
		&i.Metadata,
		&i.CreatedByID,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedByID,
		&i.UpdatedByName,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.ReleaseID,
	)
	return i, err
}

const updateDeploymentZone = `-- name: UpdateDeploymentZone :one
WITH updated AS (
  UPDATE deployment_zone dz
  SET name = $1,
      description = $2,
      type = $3,
      metadata = $4,
      updated_by_id = uo.user_id,
      updated_at = now()
  FROM user_on_organization uo
  WHERE uo.organization_id = $5
    AND uo.user_id = $6
    AND uo.deleted_at IS NULL
    AND dz.organization_id = uo.organization_id
    AND dz.id = $7
  RETURNING dz.id, dz.name, dz.slug, dz.type, dz.metadata, dz.description, dz.created_at, dz.created_by_id, dz.updated_at, dz.updated_by_id, dz.organization_id
)
SELECT updated.id, updated.name, updated.slug, updated.type, updated.metadata, updated.description, updated.created_at, updated.created_by_id, updated.updated_at, updated.updated_by_id, updated.organization_id,
       creator.name AS created_by_name,
       updater.name AS updated_by_name
FROM updated
  INNER JOIN "user" creator ON updated.created_by_id = creator.id
  INNER JOIN "user" updater ON updated.updated_by_id = updater.id
`

type UpdateDeploymentZoneParams struct {
	Name             string    `json:"name"`
	Description      string    `json:"description"`
	Type             string    `json:"type"`
	Metadata         []byte    `json:"metadata"`
	OrganizationID   uuid.UUID `json:"organization_id"`
	UserID           uuid.UUID `json:"user_id"`
	DeploymentZoneID uuid.UUID `json:"deployment_zone_id"`
}

type UpdateDeploymentZoneRow struct {
	ID             uuid.UUID        `json:"id"`
	Name           string           `json:"name"`
	Slug           string           `json:"slug"`
	Type           string           `json:"type"`
	Metadata       []byte           `json:"metadata"`
	Description    string           `json:"description"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	CreatedByID    uuid.UUID        `json:"created_by_id"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	UpdatedByID    uuid.UUID        `json:"updated_by_id"`
	OrganizationID uuid.UUID        `json:"organization_id"`
	CreatedByName  string           `json:"created_by_name"`
	UpdatedByName  string           `json:"updated_by_name"`
}

func (q *Queries) UpdateDeploymentZone(ctx context.Context, arg UpdateDeploymentZoneParams) (UpdateDeploymentZoneRow, error) {
	row := q.db.QueryRow(ctx, updateDeploymentZone,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Metadata,
		arg.OrganizationID,
		arg.UserID,
		arg.DeploymentZoneID,
	)
	var i UpdateDeploymentZoneRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.Metadata,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.UpdatedAt,
		&i.UpdatedByID,
		&i.OrganizationID,
		&i.CreatedByName,
		&i.UpdatedByName,
	)
	return i, err
}

const updateDeploymentZoneBySlug = `-- name: UpdateDeploymentZoneBySlug :one
WITH updated AS (
  UPDATE deployment_zone dz
  SET name = $1,
      description = $2,
      type = $3,
      metadata = $4,
      updated_by_id = uo.user_id,
      updated_at = now()
  FROM user_on_organization uo
  WHERE uo.organization_id = $5
    AND uo.user_id = $6
    AND uo.deleted_at IS NULL
    AND dz.organization_id = uo.organization_id
    AND dz.slug = $7
  RETURNING dz.id, dz.name, dz.slug, dz.type, dz.metadata, dz.description, dz.created_at, dz.created_by_id, dz.updated_at, dz.updated_by_id, dz.organization_id
)
SELECT updated.id, updated.name, updated.slug, updated.type, updated.metadata, updated.description, updated.created_at, updated.created_by_id, updated.updated_at, updated.updated_by_id, updated.organization_id,
       creator.name AS created_by_name,
       updater.name AS updated_by_name
FROM updated
  INNER JOIN "user" creator ON updated.created_by_id = creator.id
  INNER JOIN "user" updater ON updated.updated_by_id = updater.id
`

type UpdateDeploymentZoneBySlugParams struct {
	Name           string    `json:"name"`
	Description    string    `json:"description"`
	Type           string    `json:"type"`
	Metadata       []byte    `json:"metadata"`
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Slug           string    `json:"slug"`
}

type UpdateDeploymentZoneBySlugRow struct {
	ID             uuid.UUID        `json:"id"`
	Name           string           `json:"name"`
	Slug           string           `json:"slug"`
	Type           string           `json:"type"`
	Metadata       []byte           `json:"metadata"`
	Description    string           `json:"description"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	CreatedByID    uuid.UUID        `json:"created_by_id"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	UpdatedByID    uuid.UUID        `json:"updated_by_id"`
	OrganizationID uuid.UUID        `json:"organization_id"`
	CreatedByName  string           `json:"created_by_name"`
	UpdatedByName  string           `json:"updated_by_name"`
}

func (q *Queries) UpdateDeploymentZoneBySlug(ctx context.Context, arg UpdateDeploymentZoneBySlugParams) (UpdateDeploymentZoneBySlugRow, error) {
	row := q.db.QueryRow(ctx, updateDeploymentZoneBySlug,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Metadata,
		arg.OrganizationID,
		arg.UserID,
		arg.Slug,
	)
	var i UpdateDeploymentZoneBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.Metadata,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.UpdatedAt,
		&i.UpdatedByID,
		&i.OrganizationID,
		&i.CreatedByName,
		&i.UpdatedByName,
	)
	return i, err
}
