// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDeployment = `-- name: CreateDeployment :one
WITH inserted AS (
  INSERT INTO deployment (deployment_zone_id, release_id, created_by_id, organization_id)
  SELECT $1, $2, uo.user_id, uo.organization_id
  FROM user_on_organization uo
  WHERE uo.organization_id = $3
         AND uo.user_id = $4
         AND uo.deleted_at IS NULL
  RETURNING deployment_zone_id, release_id, created_at, created_by_id, organization_id, id, seq
)
SELECT inserted.id, inserted.deployment_zone_id, inserted.release_id, inserted.created_by_id,
       creator.name AS created_by_name,
       inserted.created_at, inserted.organization_id
FROM inserted
  INNER JOIN "user" creator ON inserted.created_by_id = creator.id
`

type CreateDeploymentParams struct {
	DeploymentZoneID uuid.UUID `json:"deployment_zone_id"`
	ReleaseID        uuid.UUID `json:"release_id"`
	OrganizationID   uuid.UUID `json:"organization_id"`
	UserID           uuid.UUID `json:"user_id"`
}

type CreateDeploymentRow struct {
	ID               uuid.UUID        `json:"id"`
	DeploymentZoneID uuid.UUID        `json:"deployment_zone_id"`
	ReleaseID        uuid.UUID        `json:"release_id"`
	CreatedByID      uuid.UUID        `json:"created_by_id"`
	CreatedByName    string           `json:"created_by_name"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	OrganizationID   uuid.UUID        `json:"organization_id"`
}

// Append-only: every deployment of a release to a zone is its own row, so
// re-deploying a release a zone already ran (a rollback) records a new event
// instead of colliding with the old one.
func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (CreateDeploymentRow, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.DeploymentZoneID,
		arg.ReleaseID,
		arg.OrganizationID,
		arg.UserID,
	)
	var i CreateDeploymentRow
	err := row.Scan(
		&i.ID,
		&i.DeploymentZoneID,
		&i.ReleaseID,
		&i.CreatedByID,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const getDeployments = `-- name: GetDeployments :many
SELECT d.id, d.deployment_zone_id, d.release_id, d.created_by_id,
       creator.name AS created_by_name,
       d.created_at, d.organization_id
FROM deployment d
  INNER JOIN "user" creator ON d.created_by_id = creator.id
WHERE d.organization_id = $1
  AND d.deployment_zone_id = $2
ORDER BY d.created_at DESC, d.seq DESC
`

type GetDeploymentsParams struct {
	OrganizationID   uuid.UUID `json:"organization_id"`
	DeploymentZoneID uuid.UUID `json:"deployment_zone_id"`
}

type GetDeploymentsRow struct {
	ID               uuid.UUID        `json:"id"`
	DeploymentZoneID uuid.UUID        `json:"deployment_zone_id"`
	ReleaseID        uuid.UUID        `json:"release_id"`
	CreatedByID      uuid.UUID        `json:"created_by_id"`
	CreatedByName    string           `json:"created_by_name"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	OrganizationID   uuid.UUID        `json:"organization_id"`
}

// The zone's deployment history, newest first.
func (q *Queries) GetDeployments(ctx context.Context, arg GetDeploymentsParams) ([]GetDeploymentsRow, error) {
	rows, err := q.db.Query(ctx, getDeployments, arg.OrganizationID, arg.DeploymentZoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeploymentsRow
	for rows.Next() {
		var i GetDeploymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentZoneID,
			&i.ReleaseID,
			&i.CreatedByID,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeploymentsByReleaseIDs = `-- name: GetDeploymentsByReleaseIDs :many
SELECT d.id,
       d.deployment_zone_id,
       d.release_id,
       d.created_by_id,
       creator.name AS created_by_name,
       d.created_at,
       d.organization_id
FROM deployment d
  INNER JOIN "user" creator ON d.created_by_id = creator.id
WHERE d.organization_id = $1
  AND d.release_id = ANY ($2::uuid[])
ORDER BY d.release_id, d.created_at DESC, d.seq DESC
`

type GetDeploymentsByReleaseIDsParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	ReleaseIds     []uuid.UUID `json:"release_ids"`
}

type GetDeploymentsByReleaseIDsRow struct {
	ID               uuid.UUID        `json:"id"`
	DeploymentZoneID uuid.UUID        `json:"deployment_zone_id"`
	ReleaseID        uuid.UUID        `json:"release_id"`
	CreatedByID      uuid.UUID        `json:"created_by_id"`
	CreatedByName    string           `json:"created_by_name"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	OrganizationID   uuid.UUID        `json:"organization_id"`
}

// Every deployment of each release, newest first: a release deployed twice to
// the same zone (rolled back to) appears once per deployment.
func (q *Queries) GetDeploymentsByReleaseIDs(ctx context.Context, arg GetDeploymentsByReleaseIDsParams) ([]GetDeploymentsByReleaseIDsRow, error) {
	rows, err := q.db.Query(ctx, getDeploymentsByReleaseIDs, arg.OrganizationID, arg.ReleaseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeploymentsByReleaseIDsRow
	for rows.Next() {
		var i GetDeploymentsByReleaseIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentZoneID,
			&i.ReleaseID,
			&i.CreatedByID,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
