// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AddonOverrideBehavior string

const (
	AddonOverrideBehaviorADD      AddonOverrideBehavior = "ADD"
	AddonOverrideBehaviorOVERRIDE AddonOverrideBehavior = "OVERRIDE"
	AddonOverrideBehaviorMAX      AddonOverrideBehavior = "MAX"
)

func (e *AddonOverrideBehavior) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AddonOverrideBehavior(s)
	case string:
		*e = AddonOverrideBehavior(s)
	default:
		return fmt.Errorf("unsupported scan type for AddonOverrideBehavior: %T", src)
	}
	return nil
}

type NullAddonOverrideBehavior struct {
	AddonOverrideBehavior AddonOverrideBehavior `json:"addon_override_behavior"`
	Valid                 bool                  `json:"valid"` // Valid is true if AddonOverrideBehavior is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAddonOverrideBehavior) Scan(value interface{}) error {
	if value == nil {
		ns.AddonOverrideBehavior, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AddonOverrideBehavior.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAddonOverrideBehavior) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AddonOverrideBehavior), nil
}

type AggregationMethod string

const (
	AggregationMethodSUM     AggregationMethod = "SUM"
	AggregationMethodCOUNT   AggregationMethod = "COUNT"
	AggregationMethodAVERAGE AggregationMethod = "AVERAGE"
	AggregationMethodMAX     AggregationMethod = "MAX"
	AggregationMethodMIN     AggregationMethod = "MIN"
	AggregationMethodLATEST  AggregationMethod = "LATEST"
)

func (e *AggregationMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AggregationMethod(s)
	case string:
		*e = AggregationMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for AggregationMethod: %T", src)
	}
	return nil
}

type NullAggregationMethod struct {
	AggregationMethod AggregationMethod `json:"aggregation_method"`
	Valid             bool              `json:"valid"` // Valid is true if AggregationMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAggregationMethod) Scan(value interface{}) error {
	if value == nil {
		ns.AggregationMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AggregationMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAggregationMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AggregationMethod), nil
}

type BillingModel string

const (
	BillingModelFLATFEE    BillingModel = "FLAT_FEE"
	BillingModelUSAGEBASED BillingModel = "USAGE_BASED"
	BillingModelOVERAGE    BillingModel = "OVERAGE"
)

func (e *BillingModel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingModel(s)
	case string:
		*e = BillingModel(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingModel: %T", src)
	}
	return nil
}

type NullBillingModel struct {
	BillingModel BillingModel `json:"billing_model"`
	Valid        bool         `json:"valid"` // Valid is true if BillingModel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingModel) Scan(value interface{}) error {
	if value == nil {
		ns.BillingModel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingModel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingModel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingModel), nil
}

type BillingPeriod string

const (
	BillingPeriodMONTHLY    BillingPeriod = "MONTHLY"
	BillingPeriodQUARTERLY  BillingPeriod = "QUARTERLY"
	BillingPeriodSEMIANNUAL BillingPeriod = "SEMI_ANNUAL"
	BillingPeriodANNUAL     BillingPeriod = "ANNUAL"
)

func (e *BillingPeriod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingPeriod(s)
	case string:
		*e = BillingPeriod(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingPeriod: %T", src)
	}
	return nil
}

type NullBillingPeriod struct {
	BillingPeriod BillingPeriod `json:"billing_period"`
	Valid         bool          `json:"valid"` // Valid is true if BillingPeriod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingPeriod) Scan(value interface{}) error {
	if value == nil {
		ns.BillingPeriod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingPeriod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingPeriod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingPeriod), nil
}

type BillingTiming string

const (
	BillingTimingADVANCE BillingTiming = "ADVANCE"
	BillingTimingARREARS BillingTiming = "ARREARS"
)

func (e *BillingTiming) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingTiming(s)
	case string:
		*e = BillingTiming(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingTiming: %T", src)
	}
	return nil
}

type NullBillingTiming struct {
	BillingTiming BillingTiming `json:"billing_timing"`
	Valid         bool          `json:"valid"` // Valid is true if BillingTiming is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingTiming) Scan(value interface{}) error {
	if value == nil {
		ns.BillingTiming, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingTiming.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingTiming) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingTiming), nil
}

type EntitlementResetPeriod string

const (
	EntitlementResetPeriodHOUR  EntitlementResetPeriod = "HOUR"
	EntitlementResetPeriodDAY   EntitlementResetPeriod = "DAY"
	EntitlementResetPeriodWEEK  EntitlementResetPeriod = "WEEK"
	EntitlementResetPeriodMONTH EntitlementResetPeriod = "MONTH"
	EntitlementResetPeriodYEAR  EntitlementResetPeriod = "YEAR"
)

func (e *EntitlementResetPeriod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntitlementResetPeriod(s)
	case string:
		*e = EntitlementResetPeriod(s)
	default:
		return fmt.Errorf("unsupported scan type for EntitlementResetPeriod: %T", src)
	}
	return nil
}

type NullEntitlementResetPeriod struct {
	EntitlementResetPeriod EntitlementResetPeriod `json:"entitlement_reset_period"`
	Valid                  bool                   `json:"valid"` // Valid is true if EntitlementResetPeriod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntitlementResetPeriod) Scan(value interface{}) error {
	if value == nil {
		ns.EntitlementResetPeriod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntitlementResetPeriod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntitlementResetPeriod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntitlementResetPeriod), nil
}

type EntitlementType string

const (
	EntitlementTypeBOOLEAN        EntitlementType = "BOOLEAN"
	EntitlementTypeNUMBER         EntitlementType = "NUMBER"
	EntitlementTypeCONFIG         EntitlementType = "CONFIG"
	EntitlementTypeNUMBERAICREDIT EntitlementType = "NUMBER_AI_CREDIT"
)

func (e *EntitlementType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntitlementType(s)
	case string:
		*e = EntitlementType(s)
	default:
		return fmt.Errorf("unsupported scan type for EntitlementType: %T", src)
	}
	return nil
}

type NullEntitlementType struct {
	EntitlementType EntitlementType `json:"entitlement_type"`
	Valid           bool            `json:"valid"` // Valid is true if EntitlementType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntitlementType) Scan(value interface{}) error {
	if value == nil {
		ns.EntitlementType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntitlementType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntitlementType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntitlementType), nil
}

type InstanceBillingStatus string

const (
	InstanceBillingStatusTRIAL    InstanceBillingStatus = "TRIAL"
	InstanceBillingStatusACTIVE   InstanceBillingStatus = "ACTIVE"
	InstanceBillingStatusPASTDUE  InstanceBillingStatus = "PAST_DUE"
	InstanceBillingStatusCANCELED InstanceBillingStatus = "CANCELED"
)

func (e *InstanceBillingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InstanceBillingStatus(s)
	case string:
		*e = InstanceBillingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InstanceBillingStatus: %T", src)
	}
	return nil
}

type NullInstanceBillingStatus struct {
	InstanceBillingStatus InstanceBillingStatus `json:"instance_billing_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if InstanceBillingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInstanceBillingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InstanceBillingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InstanceBillingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInstanceBillingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InstanceBillingStatus), nil
}

type LicenseLifecycleState string

const (
	LicenseLifecycleStateDRAFT     LicenseLifecycleState = "DRAFT"
	LicenseLifecycleStatePUBLISHED LicenseLifecycleState = "PUBLISHED"
	LicenseLifecycleStateARCHIVED  LicenseLifecycleState = "ARCHIVED"
)

func (e *LicenseLifecycleState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LicenseLifecycleState(s)
	case string:
		*e = LicenseLifecycleState(s)
	default:
		return fmt.Errorf("unsupported scan type for LicenseLifecycleState: %T", src)
	}
	return nil
}

type NullLicenseLifecycleState struct {
	LicenseLifecycleState LicenseLifecycleState `json:"license_lifecycle_state"`
	Valid                 bool                  `json:"valid"` // Valid is true if LicenseLifecycleState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLicenseLifecycleState) Scan(value interface{}) error {
	if value == nil {
		ns.LicenseLifecycleState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LicenseLifecycleState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLicenseLifecycleState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LicenseLifecycleState), nil
}

type PriceStatus string

const (
	PriceStatusACTIVE     PriceStatus = "ACTIVE"
	PriceStatusDEPRECATED PriceStatus = "DEPRECATED"
)

func (e *PriceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PriceStatus(s)
	case string:
		*e = PriceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PriceStatus: %T", src)
	}
	return nil
}

type NullPriceStatus struct {
	PriceStatus PriceStatus `json:"price_status"`
	Valid       bool        `json:"valid"` // Valid is true if PriceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPriceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PriceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PriceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPriceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PriceStatus), nil
}

type PricingType string

const (
	PricingTypeFREE   PricingType = "FREE"
	PricingTypePAID   PricingType = "PAID"
	PricingTypeCUSTOM PricingType = "CUSTOM"
)

func (e *PricingType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PricingType(s)
	case string:
		*e = PricingType(s)
	default:
		return fmt.Errorf("unsupported scan type for PricingType: %T", src)
	}
	return nil
}

type NullPricingType struct {
	PricingType PricingType `json:"pricing_type"`
	Valid       bool        `json:"valid"` // Valid is true if PricingType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPricingType) Scan(value interface{}) error {
	if value == nil {
		ns.PricingType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PricingType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPricingType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PricingType), nil
}

type Addon struct {
	ID             uuid.UUID             `json:"id"`
	OrganizationID uuid.UUID             `json:"organization_id"`
	FamilyID       uuid.UUID             `json:"family_id"`
	Name           string                `json:"name"`
	Slug           string                `json:"slug"`
	Description    string                `json:"description"`
	Version        int32                 `json:"version"`
	VersionName    *string               `json:"version_name"`
	IsDefault      bool                  `json:"is_default"`
	LifecycleState LicenseLifecycleState `json:"lifecycle_state"`
	PricingType    PricingType           `json:"pricing_type"`
	MaxQuantity    *int32                `json:"max_quantity"`
	CreatedAt      pgtype.Timestamp      `json:"created_at"`
	CreatedByID    uuid.UUID             `json:"created_by_id"`
	UpdatedAt      pgtype.Timestamp      `json:"updated_at"`
	UpdatedByID    uuid.UUID             `json:"updated_by_id"`
}

type AddonFamily struct {
	ID             uuid.UUID        `json:"id"`
	OrganizationID uuid.UUID        `json:"organization_id"`
	Slug           string           `json:"slug"`
	LastVersion    int32            `json:"last_version"`
	IsPublic       bool             `json:"is_public"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}
