apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq-pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: protocol
      value: "amqp"
    - name: hostname
      value: "rabbitmq"
    - name: username
      value: "admin"
    - name: password
      value: "admin"
    - name: durable
      value: true
    - name: deletedWhenUnused
      value: false
    - name: deliveryMode
      value: 2
    - name: prefetchCount
      value: 100
    - name: exchangeKind
      value: "fanout"
