// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Connector struct {
	Name           string           `json:"name"`
	Version        string           `json:"version"`
	SettingsSchema []byte           `json:"settings_schema"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	// Slug of the BOOLEAN entitlement an organization's license must grant before it may activate this connector. NULL means ungated.
	EntitlementSlug *string `json:"entitlement_slug"`
}

type OrganizationConnector struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	ConnectorName  string             `json:"connector_name"`
	ActivatedAt    pgtype.Timestamptz `json:"activated_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
