// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entitlement_usage.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptEntitlementUsage = `-- name: AcceptEntitlementUsage :one
INSERT INTO entitlement_usage (entitlement_id, instance_id, value, organization_id, period_start, report_seq)
VALUES ($1, $2, $3, $4, $5, 1)
ON CONFLICT (entitlement_id, instance_id)
  DO UPDATE SET value       = EXCLUDED.value,
                period_start = EXCLUDED.period_start,
                report_seq   = entitlement_usage.report_seq + 1
RETURNING report_seq
`

type AcceptEntitlementUsageParams struct {
	EntitlementID  uuid.UUID        `json:"entitlement_id"`
	InstanceID     uuid.UUID        `json:"instance_id"`
	Value          []byte           `json:"value"`
	OrganizationID uuid.UUID        `json:"organization_id"`
	PeriodStart    pgtype.Timestamp `json:"period_start"`
}

// Writes the counter of an ACCEPTED report and moves the pair's report_seq
// forward by one, returning it: the report_seq of the usage_ledger row the
// same transaction writes next. A pair's first report creates the row at 1.
// Runs under the pair's advisory lock, which is what keeps report_seq
// contiguous.
func (q *Queries) AcceptEntitlementUsage(ctx context.Context, arg AcceptEntitlementUsageParams) (int64, error) {
	row := q.db.QueryRow(ctx, acceptEntitlementUsage,
		arg.EntitlementID,
		arg.InstanceID,
		arg.Value,
		arg.OrganizationID,
		arg.PeriodStart,
	)
	var report_seq int64
	err := row.Scan(&report_seq)
	return report_seq, err
}

const getDatabaseNow = `-- name: GetDatabaseNow :one
SELECT date_trunc('milliseconds', clock_timestamp() AT TIME ZONE 'UTC')::timestamp(3) AS now
`

// The single time source for usage: never the application node's wall clock,
// so reads and reports on different replicas agree on "now". clock_timestamp()
// rather than now(): now() is frozen at the transaction's BEGIN, and a report
// reads this after waiting for its pair's lock. Truncated rather than cast:
// the ::timestamp(3) cast rounds, which moves 23:59:59.9996 into the next
// window. Every usage read uses this same expression.
func (q *Queries) GetDatabaseNow(ctx context.Context) (pgtype.Timestamp, error) {
	row := q.db.QueryRow(ctx, getDatabaseNow)
	var now pgtype.Timestamp
	err := row.Scan(&now)
	return now, err
}

const getEffectiveEntitlementLimit = `-- name: GetEffectiveEntitlementLimit :one
SELECT iee.value,
       iee.limit_cap_exceeded_overage_percent
FROM instance_effective_entitlement iee
WHERE iee.instance_id = $1
  AND iee.entitlement_id = $2
  AND iee.organization_id = $3
`

type GetEffectiveEntitlementLimitParams struct {
	InstanceID     uuid.UUID `json:"instance_id"`
	EntitlementID  uuid.UUID `json:"entitlement_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type GetEffectiveEntitlementLimitRow struct {
	Value                          []byte `json:"value"`
	LimitCapExceededOveragePercent *int16 `json:"limit_cap_exceeded_overage_percent"`
}

// The limit and overage policy a report is gated on: the instance's effective
// entitlement, read after StampReportInstant. No row means the instance is no
// longer granted the entitlement.
func (q *Queries) GetEffectiveEntitlementLimit(ctx context.Context, arg GetEffectiveEntitlementLimitParams) (GetEffectiveEntitlementLimitRow, error) {
	row := q.db.QueryRow(ctx, getEffectiveEntitlementLimit, arg.InstanceID, arg.EntitlementID, arg.OrganizationID)
	var i GetEffectiveEntitlementLimitRow
	err := row.Scan(&i.Value, &i.LimitCapExceededOveragePercent)
	return i, err
}

const getEntitlementContextBySlug = `-- name: GetEntitlementContextBySlug :one
SELECT
  i.id                AS instance_id,
  i.license_id,
  i.start_license_date,
  e.id                AS entitlement_id,
  e.slug              AS entitlement_slug,
  e.type              AS entitlement_type,
  e.aggregation_method,
  e.warning_threshold_percent,
  e.reset_period,
  e.reset_anchor,
  l.slug              AS license_slug
FROM instance i
JOIN entitlement e
  ON e.slug            = $1
 AND e.organization_id = $2
JOIN instance_effective_entitlement iee
  ON iee.instance_id    = i.id
 AND iee.entitlement_id = e.id
LEFT JOIN "license" l
  ON l.id = i.license_id
WHERE i.slug            = $3
  AND i.organization_id = $2
`

type GetEntitlementContextBySlugParams struct {
	EntitlementSlug string    `json:"entitlement_slug"`
	OrganizationID  uuid.UUID `json:"organization_id"`
	InstanceSlug    string    `json:"instance_slug"`
}

type GetEntitlementContextBySlugRow struct {
	InstanceID              uuid.UUID               `json:"instance_id"`
	LicenseID               uuid.UUID               `json:"license_id"`
	StartLicenseDate        pgtype.Timestamp        `json:"start_license_date"`
	EntitlementID           uuid.UUID               `json:"entitlement_id"`
	EntitlementSlug         string                  `json:"entitlement_slug"`
	EntitlementType         EntitlementType         `json:"entitlement_type"`
	AggregationMethod       *AggregationMethod      `json:"aggregation_method"`
	WarningThresholdPercent int16                   `json:"warning_threshold_percent"`
	ResetPeriod             *EntitlementResetPeriod `json:"reset_period"`
	ResetAnchor             *EntitlementResetAnchor `json:"reset_anchor"`
	LicenseSlug             *string                 `json:"license_slug"`
}

// Resolves instance/entitlement slugs and checks the instance is granted the
// entitlement, in a single round-trip. Returns IDs and metadata needed to then
// lock and update the usage row, including everything period.Current needs
// (reset_period/reset_anchor/start_license_date). Includes neither the usage
// value (GetEntitlementUsageContext, with FOR UPDATE) nor the limit
// (GetEffectiveEntitlementLimit): both are read under the pair's lock.
func (q *Queries) GetEntitlementContextBySlug(ctx context.Context, arg GetEntitlementContextBySlugParams) (GetEntitlementContextBySlugRow, error) {
	row := q.db.QueryRow(ctx, getEntitlementContextBySlug, arg.EntitlementSlug, arg.OrganizationID, arg.InstanceSlug)
	var i GetEntitlementContextBySlugRow
	err := row.Scan(
		&i.InstanceID,
		&i.LicenseID,
		&i.StartLicenseDate,
		&i.EntitlementID,
		&i.EntitlementSlug,
		&i.EntitlementType,
		&i.AggregationMethod,
		&i.WarningThresholdPercent,
		&i.ResetPeriod,
		&i.ResetAnchor,
		&i.LicenseSlug,
	)
	return i, err
}

const getEntitlementUsageContext = `-- name: GetEntitlementUsageContext :one
SELECT
  eu.value,
  eu.period_start
FROM entitlement_usage eu
WHERE eu.instance_id = $1
  AND eu.entitlement_id = $2
  AND eu.organization_id = $3
  FOR UPDATE OF eu
`

type GetEntitlementUsageContextParams struct {
	InstanceID     uuid.UUID `json:"instance_id"`
	EntitlementID  uuid.UUID `json:"entitlement_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type GetEntitlementUsageContextRow struct {
	Value       []byte           `json:"value"`
	PeriodStart pgtype.Timestamp `json:"period_start"`
}

// The pair's counter, row-locked. The report reads it under the pair's
// advisory lock; no row means the pair's first report.
func (q *Queries) GetEntitlementUsageContext(ctx context.Context, arg GetEntitlementUsageContextParams) (GetEntitlementUsageContextRow, error) {
	row := q.db.QueryRow(ctx, getEntitlementUsageContext, arg.InstanceID, arg.EntitlementID, arg.OrganizationID)
	var i GetEntitlementUsageContextRow
	err := row.Scan(&i.Value, &i.PeriodStart)
	return i, err
}

const getEntitlementUsageForInstance = `-- name: GetEntitlementUsageForInstance :one
SELECT eu.entitlement_id, eu.instance_id, eu.value, eu.period_start, eu.organization_id, i.license_id,
       e.slug AS entitlement_slug, l.slug AS license_slug
FROM entitlement_usage eu
       JOIN instance i ON eu.instance_id = i.id
       JOIN entitlement e ON eu.entitlement_id = e.id
       LEFT JOIN "license" l ON i.license_id = l.id
WHERE eu.instance_id = $1
  AND eu.organization_id = $2
  AND eu.entitlement_id = $3
`

type GetEntitlementUsageForInstanceParams struct {
	InstanceID     uuid.UUID `json:"instance_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	EntitlementID  uuid.UUID `json:"entitlement_id"`
}

type GetEntitlementUsageForInstanceRow struct {
	EntitlementID   uuid.UUID        `json:"entitlement_id"`
	InstanceID      uuid.UUID        `json:"instance_id"`
	Value           []byte           `json:"value"`
	PeriodStart     pgtype.Timestamp `json:"period_start"`
	OrganizationID  uuid.UUID        `json:"organization_id"`
	LicenseID       uuid.UUID        `json:"license_id"`
	EntitlementSlug string           `json:"entitlement_slug"`
	LicenseSlug     *string          `json:"license_slug"`
}

func (q *Queries) GetEntitlementUsageForInstance(ctx context.Context, arg GetEntitlementUsageForInstanceParams) (GetEntitlementUsageForInstanceRow, error) {
	row := q.db.QueryRow(ctx, getEntitlementUsageForInstance, arg.InstanceID, arg.OrganizationID, arg.EntitlementID)
	var i GetEntitlementUsageForInstanceRow
	err := row.Scan(
		&i.EntitlementID,
		&i.InstanceID,
		&i.Value,
		&i.PeriodStart,
		&i.OrganizationID,
		&i.LicenseID,
		&i.EntitlementSlug,
		&i.LicenseSlug,
	)
	return i, err
}

const getEntitlementUsageForInstanceOrDefault = `-- name: GetEntitlementUsageForInstanceOrDefault :one
SELECT
  i.id              AS instance_id,
  i.license_id      AS license_id,
  i.start_license_date,
  e.id              AS entitlement_id,
  iee.entitlement_id AS granted_entitlement_id,
  e.type            AS entitlement_type,
  e.reset_period,
  e.reset_anchor,
  iee.value         AS effective_value,
  iee.limit_cap_exceeded_overage_percent AS effective_overage_percent,
  iee.license_entitlement_id,
  iee.provenance,
  eu.value          AS usage_value,
  eu.period_start,
  e.slug            AS entitlement_slug,
  l.slug            AS license_slug,
  date_trunc('milliseconds', clock_timestamp() AT TIME ZONE 'UTC')::timestamp(3) AS now
FROM (VALUES (true)) AS sentinel(ok)
LEFT JOIN instance i
  ON i.slug            = $1
 AND i.organization_id = $2
LEFT JOIN entitlement e
  ON e.slug            = $3
 AND e.organization_id = $2
LEFT JOIN instance_effective_entitlement iee
  ON iee.instance_id    = i.id
 AND iee.entitlement_id = e.id
LEFT JOIN entitlement_usage eu
  ON eu.instance_id    = i.id
 AND eu.entitlement_id = e.id
 AND eu.organization_id = $2
LEFT JOIN "license" l
  ON l.id = i.license_id
`

type GetEntitlementUsageForInstanceOrDefaultParams struct {
	InstanceSlug    string    `json:"instance_slug"`
	OrganizationID  uuid.UUID `json:"organization_id"`
	EntitlementSlug string    `json:"entitlement_slug"`
}

type GetEntitlementUsageForInstanceOrDefaultRow struct {
	InstanceID              *uuid.UUID              `json:"instance_id"`
	LicenseID               *uuid.UUID              `json:"license_id"`
	StartLicenseDate        pgtype.Timestamp        `json:"start_license_date"`
	EntitlementID           *uuid.UUID              `json:"entitlement_id"`
	GrantedEntitlementID    *uuid.UUID              `json:"granted_entitlement_id"`
	EntitlementType         *EntitlementType        `json:"entitlement_type"`
	ResetPeriod             *EntitlementResetPeriod `json:"reset_period"`
	ResetAnchor             *EntitlementResetAnchor `json:"reset_anchor"`
	EffectiveValue          []byte                  `json:"effective_value"`
	EffectiveOveragePercent *int16                  `json:"effective_overage_percent"`
	LicenseEntitlementID    *uuid.UUID              `json:"license_entitlement_id"`
	Provenance              []byte                  `json:"provenance"`
	UsageValue              []byte                  `json:"usage_value"`
	PeriodStart             pgtype.Timestamp        `json:"period_start"`
	EntitlementSlug         *string                 `json:"entitlement_slug"`
	LicenseSlug             *string                 `json:"license_slug"`
	Now                     pgtype.Timestamp        `json:"now"`
}

// Returns one row always. Nullable fields are nil when the entity is not found;
// granted_entitlement_id is nil when the instance is not granted the
// entitlement.
// now is folded in here too, instead of a separate GetDatabaseNow
// round trip -- it does not depend on any of the LEFT JOINs below, so it is
// always populated even when the instance/entitlement/usage row is not found.
func (q *Queries) GetEntitlementUsageForInstanceOrDefault(ctx context.Context, arg GetEntitlementUsageForInstanceOrDefaultParams) (GetEntitlementUsageForInstanceOrDefaultRow, error) {
	row := q.db.QueryRow(ctx, getEntitlementUsageForInstanceOrDefault, arg.InstanceSlug, arg.OrganizationID, arg.EntitlementSlug)
	var i GetEntitlementUsageForInstanceOrDefaultRow
	err := row.Scan(
		&i.InstanceID,
		&i.LicenseID,
		&i.StartLicenseDate,
		&i.EntitlementID,
		&i.GrantedEntitlementID,
		&i.EntitlementType,
		&i.ResetPeriod,
		&i.ResetAnchor,
		&i.EffectiveValue,
		&i.EffectiveOveragePercent,
		&i.LicenseEntitlementID,
		&i.Provenance,
		&i.UsageValue,
		&i.PeriodStart,
		&i.EntitlementSlug,
		&i.LicenseSlug,
		&i.Now,
	)
	return i, err
}

const getEntitlementsUsageForInstanceWithFallback = `-- name: GetEntitlementsUsageForInstanceWithFallback :many
SELECT
  iee.entitlement_id,
  e.slug            AS entitlement_slug,
  e.type            AS entitlement_type,
  e.reset_period,
  e.reset_anchor,
  i.license_id,
  i.start_license_date,
  l.slug            AS license_slug,
  iee.value         AS effective_value,
  iee.limit_cap_exceeded_overage_percent AS effective_overage_percent,
  iee.license_entitlement_id,
  iee.provenance,
  eu.value          AS usage_value,
  eu.period_start,
  date_trunc('milliseconds', clock_timestamp() AT TIME ZONE 'UTC')::timestamp(3) AS now
FROM instance i
JOIN instance_effective_entitlement iee
  ON iee.instance_id = i.id
 AND iee.organization_id = $1
JOIN entitlement e
  ON e.id = iee.entitlement_id
LEFT JOIN "license" l
  ON l.id = i.license_id
LEFT JOIN entitlement_usage eu
  ON eu.instance_id = i.id
 AND eu.entitlement_id = iee.entitlement_id
 AND eu.organization_id = $1
WHERE i.id = $2
  AND i.organization_id = $1
`

type GetEntitlementsUsageForInstanceWithFallbackParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	InstanceID     uuid.UUID `json:"instance_id"`
}

type GetEntitlementsUsageForInstanceWithFallbackRow struct {
	EntitlementID           uuid.UUID               `json:"entitlement_id"`
	EntitlementSlug         string                  `json:"entitlement_slug"`
	EntitlementType         EntitlementType         `json:"entitlement_type"`
	ResetPeriod             *EntitlementResetPeriod `json:"reset_period"`
	ResetAnchor             *EntitlementResetAnchor `json:"reset_anchor"`
	LicenseID               uuid.UUID               `json:"license_id"`
	StartLicenseDate        pgtype.Timestamp        `json:"start_license_date"`
	LicenseSlug             *string                 `json:"license_slug"`
	EffectiveValue          []byte                  `json:"effective_value"`
	EffectiveOveragePercent *int16                  `json:"effective_overage_percent"`
	LicenseEntitlementID    *uuid.UUID              `json:"license_entitlement_id"`
	Provenance              []byte                  `json:"provenance"`
	UsageValue              []byte                  `json:"usage_value"`
	PeriodStart             pgtype.Timestamp        `json:"period_start"`
	Now                     pgtype.Timestamp        `json:"now"`
}

// One row per entitlement the instance is granted, read through
// instance_effective_entitlement like every other reader of an instance's
// entitlement value. now is the same database-time value on every returned
// row: folded into this query instead of a separate GetDatabaseNow round
// trip, since every row in one call already agrees on "now" by construction.
func (q *Queries) GetEntitlementsUsageForInstanceWithFallback(ctx context.Context, arg GetEntitlementsUsageForInstanceWithFallbackParams) ([]GetEntitlementsUsageForInstanceWithFallbackRow, error) {
	rows, err := q.db.Query(ctx, getEntitlementsUsageForInstanceWithFallback, arg.OrganizationID, arg.InstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntitlementsUsageForInstanceWithFallbackRow
	for rows.Next() {
		var i GetEntitlementsUsageForInstanceWithFallbackRow
		if err := rows.Scan(
			&i.EntitlementID,
			&i.EntitlementSlug,
			&i.EntitlementType,
			&i.ResetPeriod,
			&i.ResetAnchor,
			&i.LicenseID,
			&i.StartLicenseDate,
			&i.LicenseSlug,
			&i.EffectiveValue,
			&i.EffectiveOveragePercent,
			&i.LicenseEntitlementID,
			&i.Provenance,
			&i.UsageValue,
			&i.PeriodStart,
			&i.Now,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEntitlementUsage = `-- name: LockEntitlementUsage :exec
SELECT pg_advisory_xact_lock(hashtextextended(
  $1::uuid::text || ':' || $2::uuid::text,
  0
))
`

type LockEntitlementUsageParams struct {
	InstanceID    uuid.UUID `json:"instance_id"`
	EntitlementID uuid.UUID `json:"entitlement_id"`
}

// Serializes reports for one instance/entitlement pair even before its first
// entitlement_usage row exists. A row-level FOR UPDATE lock cannot cover that case.
func (q *Queries) LockEntitlementUsage(ctx context.Context, arg LockEntitlementUsageParams) error {
	_, err := q.db.Exec(ctx, lockEntitlementUsage, arg.InstanceID, arg.EntitlementID)
	return err
}

const reportEntitlementUsage = `-- name: ReportEntitlementUsage :exec
INSERT INTO entitlement_usage (entitlement_id, instance_id, value, organization_id, period_start)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (entitlement_id, instance_id)
  DO UPDATE SET value = EXCLUDED.value, period_start = EXCLUDED.period_start
RETURNING entitlement_id, instance_id, value, organization_id, period_start, report_seq
`

type ReportEntitlementUsageParams struct {
	EntitlementID  uuid.UUID        `json:"entitlement_id"`
	InstanceID     uuid.UUID        `json:"instance_id"`
	Value          []byte           `json:"value"`
	OrganizationID uuid.UUID        `json:"organization_id"`
	PeriodStart    pgtype.Timestamp `json:"period_start"`
}

// Writes the counter without counting a report: the rollover reset of the
// report path, which leaves report_seq where it is. An ACCEPTED report goes
// through AcceptEntitlementUsage instead. period_start is NULL for lifetime
// entitlements and the window's start for periodic ones.
func (q *Queries) ReportEntitlementUsage(ctx context.Context, arg ReportEntitlementUsageParams) error {
	_, err := q.db.Exec(ctx, reportEntitlementUsage,
		arg.EntitlementID,
		arg.InstanceID,
		arg.Value,
		arg.OrganizationID,
		arg.PeriodStart,
	)
	return err
}

const stampReportInstant = `-- name: StampReportInstant :one
SELECT c.now,
       set_config('kaiten.entitlement_effective_at', to_char(c.now, 'YYYY-MM-DD HH24:MI:SS.MS'), true)::text AS effective_at
FROM (SELECT date_trunc('milliseconds', clock_timestamp() AT TIME ZONE 'UTC')::timestamp(3) AS now) c
`

type StampReportInstantRow struct {
	Now         pgtype.Timestamp `json:"now"`
	EffectiveAt string           `json:"effective_at"`
}

// The instant a report is dated by: the usage clock (see GetDatabaseNow), read
// once the pair's lock is held. It also becomes the transaction's
// kaiten.entitlement_effective_at, so that instance_effective_entitlement,
// read next in the same transaction, is evaluated at that same millisecond.
// set_config is the parameterizable SET LOCAL; true scopes it to the
// transaction.
func (q *Queries) StampReportInstant(ctx context.Context) (StampReportInstantRow, error) {
	row := q.db.QueryRow(ctx, stampReportInstant)
	var i StampReportInstantRow
	err := row.Scan(&i.Now, &i.EffectiveAt)
	return i, err
}
