// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInstance = `-- name: CreateInstance :one
WITH inserted AS (
  INSERT INTO instance (created_by_id, updated_by_id, name, slug, description, customer_id, license_id,
                        deployment_zone_id, start_license_date, end_license_date, metadata, organization_id)
  SELECT uo.user_id,
         uo.user_id,
         $1,
         $2,
         $3,
         $4,
         $5,
         $6,
         $7,
         $8,
         $9::jsonb,
         uo.organization_id
  FROM user_on_organization uo
  WHERE uo.organization_id = $10
    AND uo.user_id = $11
    AND uo.deleted_at IS NULL
  RETURNING id, created_by_id, created_at, updated_by_id, updated_at, name, slug, description, customer_id, license_id, deployment_zone_id, start_license_date, end_license_date, metadata, organization_id, status, lifecycle_stage
)
SELECT inserted.id, inserted.created_by_id, inserted.created_at, inserted.updated_by_id, inserted.updated_at, inserted.name, inserted.slug, inserted.description, inserted.customer_id, inserted.license_id, inserted.deployment_zone_id, inserted.start_license_date, inserted.end_license_date, inserted.metadata, inserted.organization_id, inserted.status, inserted.lifecycle_stage,
       creator.name AS created_by_name,
       updater.name AS updated_by_name,
       l.slug AS license_slug,
       c.slug AS customer_slug,
       dz.slug AS deployment_zone_slug
FROM inserted
  INNER JOIN "user" creator ON inserted.created_by_id = creator.id
  INNER JOIN "user" updater ON inserted.updated_by_id = updater.id
  LEFT JOIN "license" l ON inserted.license_id = l.id
  LEFT JOIN "customer" c ON inserted.customer_id = c.id
  LEFT JOIN "deployment_zone" dz ON inserted.deployment_zone_id = dz.id
`

type CreateInstanceParams struct {
	Name             string           `json:"name"`
	Slug             string           `json:"slug"`
	Description      string           `json:"description"`
	CustomerID       uuid.UUID        `json:"customer_id"`
	LicenseID        uuid.UUID        `json:"license_id"`
	DeploymentZoneID *uuid.UUID       `json:"deployment_zone_id"`
	StartLicenseDate pgtype.Timestamp `json:"start_license_date"`
	EndLicenseDate   pgtype.Timestamp `json:"end_license_date"`
	Metadata         []byte           `json:"metadata"`
	OrganizationID   uuid.UUID        `json:"organization_id"`
	UserID           uuid.UUID        `json:"user_id"`
}

type CreateInstanceRow struct {
	ID                 uuid.UUID        `json:"id"`
	CreatedByID        uuid.UUID        `json:"created_by_id"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedByID        uuid.UUID        `json:"updated_by_id"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	Name               string           `json:"name"`
	Slug               string           `json:"slug"`
	Description        string           `json:"description"`
	CustomerID         uuid.UUID        `json:"customer_id"`
	LicenseID          uuid.UUID        `json:"license_id"`
	DeploymentZoneID   *uuid.UUID       `json:"deployment_zone_id"`
	StartLicenseDate   pgtype.Timestamp `json:"start_license_date"`
	EndLicenseDate     pgtype.Timestamp `json:"end_license_date"`
	Metadata           []byte           `json:"metadata"`
	OrganizationID     uuid.UUID        `json:"organization_id"`
	Status             InstanceStatus   `json:"status"`
	LifecycleStage     *string          `json:"lifecycle_stage"`
	CreatedByName      string           `json:"created_by_name"`
	UpdatedByName      string           `json:"updated_by_name"`
	LicenseSlug        *string          `json:"license_slug"`
	CustomerSlug       *string          `json:"customer_slug"`
	DeploymentZoneSlug *string          `json:"deployment_zone_slug"`
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (CreateInstanceRow, error) {
	row := q.db.QueryRow(ctx, createInstance,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.CustomerID,
		arg.LicenseID,
		arg.DeploymentZoneID,
		arg.StartLicenseDate,
		arg.EndLicenseDate,
		arg.Metadata,
		arg.OrganizationID,
		arg.UserID,
	)
	var i CreateInstanceRow
	err := row.Scan(
		&i.ID,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedByID,
		&i.UpdatedAt,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CustomerID,
		&i.LicenseID,
		&i.DeploymentZoneID,
		&i.StartLicenseDate,
		&i.EndLicenseDate,
		&i.Metadata,
		&i.OrganizationID,
		&i.Status,
		&i.LifecycleStage,
		&i.CreatedByName,
		&i.UpdatedByName,
		&i.LicenseSlug,
		&i.CustomerSlug,
		&i.DeploymentZoneSlug,
	)
	return i, err
}

const deleteInstance = `-- name: DeleteInstance :one
WITH deleted AS (
  DELETE FROM instance i
  USING user_on_organization uo
  WHERE uo.organization_id = $1
         AND uo.user_id = $2
         AND uo.deleted_at IS NULL
         AND i.organization_id = uo.organization_id
         AND i.slug = $3
  RETURNING i.id, i.created_by_id, i.created_at, i.updated_by_id, i.updated_at, i.name, i.slug, i.description, i.customer_id, i.license_id, i.deployment_zone_id, i.start_license_date, i.end_license_date, i.metadata, i.organization_id, i.status, i.lifecycle_stage
)
SELECT deleted.id, deleted.created_by_id, deleted.created_at, deleted.updated_by_id, deleted.updated_at, deleted.name, deleted.slug, deleted.description, deleted.customer_id, deleted.license_id, deleted.deployment_zone_id, deleted.start_license_date, deleted.end_license_date, deleted.metadata, deleted.organization_id, deleted.status, deleted.lifecycle_stage,
       creator.name AS created_by_name,
       updater.name AS updated_by_name,
       l.slug AS license_slug,
       c.slug AS customer_slug,
       dz.slug AS deployment_zone_slug
FROM deleted
  INNER JOIN "user" creator ON deleted.created_by_id = creator.id
  INNER JOIN "user" updater ON deleted.updated_by_id = updater.id
  LEFT JOIN "license" l ON deleted.license_id = l.id
  LEFT JOIN "customer" c ON deleted.customer_id = c.id
  LEFT JOIN "deployment_zone" dz ON deleted.deployment_zone_id = dz.id
`

type DeleteInstanceParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Slug           string    `json:"slug"`
}

type DeleteInstanceRow struct {
	ID                 uuid.UUID        `json:"id"`
	CreatedByID        uuid.UUID        `json:"created_by_id"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedByID        uuid.UUID        `json:"updated_by_id"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	Name               string           `json:"name"`
	Slug               string           `json:"slug"`
	Description        string           `json:"description"`
	CustomerID         uuid.UUID        `json:"customer_id"`
	LicenseID          uuid.UUID        `json:"license_id"`
	DeploymentZoneID   *uuid.UUID       `json:"deployment_zone_id"`
	StartLicenseDate   pgtype.Timestamp `json:"start_license_date"`
	EndLicenseDate     pgtype.Timestamp `json:"end_license_date"`
	Metadata           []byte           `json:"metadata"`
	OrganizationID     uuid.UUID        `json:"organization_id"`
	Status             InstanceStatus   `json:"status"`
	LifecycleStage     *string          `json:"lifecycle_stage"`
	CreatedByName      string           `json:"created_by_name"`
	UpdatedByName      string           `json:"updated_by_name"`
	LicenseSlug        *string          `json:"license_slug"`
	CustomerSlug       *string          `json:"customer_slug"`
	DeploymentZoneSlug *string          `json:"deployment_zone_slug"`
}

// Real, hard delete: the instance row and everything FK-cascaded from it
// (entitlement_usage, instance_integrations, feature_audit_trail's
// successor audit_trail via ON DELETE SET NULL) are gone for good and not
// recoverable -- the frontend guards this behind an explicit confirmation
// dialog because of exactly this (see instance-table-actions.tsx). There
// is no soft-delete counterpart: instance has no deleted_at column, so
// there is no trash to restore from and no include-deleted read.
func (q *Queries) DeleteInstance(ctx context.Context, arg DeleteInstanceParams) (DeleteInstanceRow, error) {
	row := q.db.QueryRow(ctx, deleteInstance, arg.OrganizationID, arg.UserID, arg.Slug)
	var i DeleteInstanceRow
	err := row.Scan(
		&i.ID,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedByID,
		&i.UpdatedAt,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CustomerID,
		&i.LicenseID,
		&i.DeploymentZoneID,
		&i.StartLicenseDate,
		&i.EndLicenseDate,
		&i.Metadata,
		&i.OrganizationID,
		&i.Status,
		&i.LifecycleStage,
		&i.CreatedByName,
		&i.UpdatedByName,
		&i.LicenseSlug,
		&i.CustomerSlug,
		&i.DeploymentZoneSlug,
	)
	return i, err
}

const editInstance = `-- name: EditInstance :one
WITH updated AS (
  UPDATE instance i
  SET updated_by_id = uo.user_id,
      updated_at = now(),
      name = $1,
      description = $2,
      customer_id = $3,
      license_id = $4,
      deployment_zone_id = $5,
      start_license_date = $6,
      end_license_date = $7,
      metadata = $8::jsonb,
      slug = COALESCE($9, i.slug)
  FROM user_on_organization uo
  WHERE uo.organization_id = $10
         AND uo.user_id = $11
         AND uo.deleted_at IS NULL
         AND i.organization_id = uo.organization_id
         AND i.slug = $12
  RETURNING i.id, i.created_by_id, i.created_at, i.updated_by_id, i.updated_at, i.name, i.slug, i.description, i.customer_id, i.license_id, i.deployment_zone_id, i.start_license_date, i.end_license_date, i.metadata, i.organization_id, i.status, i.lifecycle_stage
)
SELECT updated.id, updated.created_by_id, updated.created_at, updated.updated_by_id, updated.updated_at, updated.name, updated.slug, updated.description, updated.customer_id, updated.license_id, updated.deployment_zone_id, updated.start_license_date, updated.end_license_date, updated.metadata, updated.organization_id, updated.status, updated.lifecycle_stage,
       creator.name AS created_by_name,
       updater.name AS updated_by_name,
       l.slug AS license_slug,
       c.slug AS customer_slug,
       dz.slug AS deployment_zone_slug
FROM updated
  INNER JOIN "user" creator ON updated.created_by_id = creator.id
  INNER JOIN "user" updater ON updated.updated_by_id = updater.id
  LEFT JOIN "license" l ON updated.license_id = l.id
  LEFT JOIN "customer" c ON updated.customer_id = c.id
  LEFT JOIN "deployment_zone" dz ON updated.deployment_zone_id = dz.id
`

type EditInstanceParams struct {
	Name             string           `json:"name"`
	Description      string           `json:"description"`
	CustomerID       uuid.UUID        `json:"customer_id"`
	LicenseID        uuid.UUID        `json:"license_id"`
	DeploymentZoneID *uuid.UUID       `json:"deployment_zone_id"`
	StartLicenseDate pgtype.Timestamp `json:"start_license_date"`
	EndLicenseDate   pgtype.Timestamp `json:"end_license_date"`
	Metadata         []byte           `json:"metadata"`
	NewSlug          *string          `json:"new_slug"`
	OrganizationID   uuid.UUID        `json:"organization_id"`
	UserID           uuid.UUID        `json:"user_id"`
	Slug             string           `json:"slug"`
}

type EditInstanceRow struct {
	ID                 uuid.UUID        `json:"id"`
	CreatedByID        uuid.UUID        `json:"created_by_id"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedByID        uuid.UUID        `json:"updated_by_id"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	Name               string           `json:"name"`
	Slug               string           `json:"slug"`
	Description        string           `json:"description"`
	CustomerID         uuid.UUID        `json:"customer_id"`
	LicenseID          uuid.UUID        `json:"license_id"`
	DeploymentZoneID   *uuid.UUID       `json:"deployment_zone_id"`
	StartLicenseDate   pgtype.Timestamp `json:"start_license_date"`
	EndLicenseDate     pgtype.Timestamp `json:"end_license_date"`
	Metadata           []byte           `json:"metadata"`
	OrganizationID     uuid.UUID        `json:"organization_id"`
	Status             InstanceStatus   `json:"status"`
	LifecycleStage     *string          `json:"lifecycle_stage"`
	CreatedByName      string           `json:"created_by_name"`
	UpdatedByName      string           `json:"updated_by_name"`
	LicenseSlug        *string          `json:"license_slug"`
	CustomerSlug       *string          `json:"customer_slug"`
	DeploymentZoneSlug *string          `json:"deployment_zone_slug"`
}

// new_slug is the one optional column: NULL keeps the row's current slug, so
// a client that does not model the slug at all -- every caller written
// before renaming was possible -- sends the body it always sent and nothing
// moves. It is the same keep-if-absent shape UpdateComponent uses. The slug
// in the WHERE clause is a different thing: it ADDRESSES the instance and is
// matched against the pre-update row, so a rename reads by the old slug and
// returns the new one.
func (q *Queries) EditInstance(ctx context.Context, arg EditInstanceParams) (EditInstanceRow, error) {
	row := q.db.QueryRow(ctx, editInstance,
		arg.Name,
		arg.Description,
		arg.CustomerID,
		arg.LicenseID,
		arg.DeploymentZoneID,
		arg.StartLicenseDate,
		arg.EndLicenseDate,
		arg.Metadata,
		arg.NewSlug,
		arg.OrganizationID,
		arg.UserID,
		arg.Slug,
	)
	var i EditInstanceRow
	err := row.Scan(
		&i.ID,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedByID,
		&i.UpdatedAt,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CustomerID,
		&i.LicenseID,
		&i.DeploymentZoneID,
		&i.StartLicenseDate,
		&i.EndLicenseDate,
		&i.Metadata,
		&i.OrganizationID,
		&i.Status,
		&i.LifecycleStage,
		&i.CreatedByName,
		&i.UpdatedByName,
		&i.LicenseSlug,
		&i.CustomerSlug,
		&i.DeploymentZoneSlug,
	)
	return i, err
}

const getAllInstances = `-- name: GetAllInstances :many
SELECT i.id, i.created_by_id, creator.name AS created_by_name, i.created_at,
       i.updated_by_id, updater.name AS updated_by_name, i.updated_at, i.status, i.lifecycle_stage, i.name, i.slug, i.description,
       i.customer_id,
       c.slug AS customer_slug,
       i.license_id,
       l.slug AS license_slug,
       i.deployment_zone_id,
       dz.slug AS deployment_zone_slug,
       i.start_license_date,
       i.end_license_date,
       i.metadata,
       i.organization_id
FROM instance i
  INNER JOIN "user" creator ON i.created_by_id = creator.id
  INNER JOIN "user" updater ON i.updated_by_id = updater.id
  LEFT JOIN "license" l ON i.license_id = l.id
  LEFT JOIN "customer" c ON i.customer_id = c.id
  LEFT JOIN "deployment_zone" dz ON i.deployment_zone_id = dz.id
WHERE i.organization_id = $1
`

type GetAllInstancesRow struct {
	ID                 uuid.UUID        `json:"id"`
	CreatedByID        uuid.UUID        `json:"created_by_id"`
	CreatedByName      string           `json:"created_by_name"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedByID        uuid.UUID        `json:"updated_by_id"`
	UpdatedByName      string           `json:"updated_by_name"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	Status             InstanceStatus   `json:"status"`
	LifecycleStage     *string          `json:"lifecycle_stage"`
	Name               string           `json:"name"`
	Slug               string           `json:"slug"`
	Description        string           `json:"description"`
	CustomerID         uuid.UUID        `json:"customer_id"`
	CustomerSlug       *string          `json:"customer_slug"`
	LicenseID          uuid.UUID        `json:"license_id"`
	LicenseSlug        *string          `json:"license_slug"`
	DeploymentZoneID   *uuid.UUID       `json:"deployment_zone_id"`
	DeploymentZoneSlug *string          `json:"deployment_zone_slug"`
	StartLicenseDate   pgtype.Timestamp `json:"start_license_date"`
	EndLicenseDate     pgtype.Timestamp `json:"end_license_date"`
	Metadata           []byte           `json:"metadata"`
	OrganizationID     uuid.UUID        `json:"organization_id"`
}

// Unbounded on purpose: used by metadatafields/dryrunmetadatafield, which
// must validate a candidate JSON schema against every instance in the
// organization, not just one page. GetAllInstancesByCursor (below) is the
// cursor-paginated variant for list-facing callers (REST getinstances,
// GraphQL Query.instances).
func (q *Queries) GetAllInstances(ctx context.Context, organizationID uuid.UUID) ([]GetAllInstancesRow, error) {
	rows, err := q.db.Query(ctx, getAllInstances, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllInstancesRow
	for rows.Next() {
		var i GetAllInstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedByID,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedByID,
			&i.UpdatedByName,
			&i.UpdatedAt,
			&i.Status,
			&i.LifecycleStage,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CustomerID,
			&i.CustomerSlug,
			&i.LicenseID,
			&i.LicenseSlug,
			&i.DeploymentZoneID,
			&i.DeploymentZoneSlug,
			&i.StartLicenseDate,
			&i.EndLicenseDate,
			&i.Metadata,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllInstancesByCursor = `-- name: GetAllInstancesByCursor :many
SELECT i.id, i.created_by_id, creator.name AS created_by_name, i.created_at,
       i.updated_by_id, updater.name AS updated_by_name, i.updated_at, i.status, i.lifecycle_stage, i.name, i.slug, i.description,
       i.customer_id,
       c.slug AS customer_slug,
       i.license_id,
       l.slug AS license_slug,
       i.deployment_zone_id,
       dz.slug AS deployment_zone_slug,
       i.start_license_date,
       i.end_license_date,
       i.metadata,
       i.organization_id
FROM instance i
  INNER JOIN "user" creator ON i.created_by_id = creator.id
  INNER JOIN "user" updater ON i.updated_by_id = updater.id
  LEFT JOIN "license" l ON i.license_id = l.id
  LEFT JOIN "customer" c ON i.customer_id = c.id
  LEFT JOIN "deployment_zone" dz ON i.deployment_zone_id = dz.id
WHERE i.organization_id = $1
  AND (
    $2::text IS NULL
    OR EXISTS (
      SELECT 1
      FROM instance_integrations ii
      WHERE ii.instance_id = i.id
        AND ii.organization_id = i.organization_id
        AND ii.adapter = $2::text
        AND ii.external_id <> ''
    )
  )
  AND (
    $3::timestamp IS NULL
    OR (i.created_at, i.id) < ($3::timestamp, $4::uuid)
  )
ORDER BY i.created_at DESC, i.id DESC
LIMIT $5
`

type GetAllInstancesByCursorParams struct {
	OrganizationID  uuid.UUID        `json:"organization_id"`
	Adapter         *string          `json:"adapter"`
	CursorCreatedAt pgtype.Timestamp `json:"cursor_created_at"`
	CursorID        *uuid.UUID       `json:"cursor_id"`
	LimitPlusOne    int32            `json:"limit_plus_one"`
}

type GetAllInstancesByCursorRow struct {
	ID                 uuid.UUID        `json:"id"`
	CreatedByID        uuid.UUID        `json:"created_by_id"`
	CreatedByName      string           `json:"created_by_name"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedByID        uuid.UUID        `json:"updated_by_id"`
	UpdatedByName      string           `json:"updated_by_name"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	Status             InstanceStatus   `json:"status"`
	LifecycleStage     *string          `json:"lifecycle_stage"`
	Name               string           `json:"name"`
	Slug               string           `json:"slug"`
	Description        string           `json:"description"`
	CustomerID         uuid.UUID        `json:"customer_id"`
	CustomerSlug       *string          `json:"customer_slug"`
	LicenseID          uuid.UUID        `json:"license_id"`
	LicenseSlug        *string          `json:"license_slug"`
	DeploymentZoneID   *uuid.UUID       `json:"deployment_zone_id"`
	DeploymentZoneSlug *string          `json:"deployment_zone_slug"`
	StartLicenseDate   pgtype.Timestamp `json:"start_license_date"`
	EndLicenseDate     pgtype.Timestamp `json:"end_license_date"`
	Metadata           []byte           `json:"metadata"`
	OrganizationID     uuid.UUID        `json:"organization_id"`
}

// Cursor (keyset) pagination: ordered by created_at DESC, id DESC (id
// tie-breaks created_at, which is not guaranteed unique). Pass
// limit_plus_one = requested limit + 1 so the caller can detect whether a
// further page exists without a separate COUNT query. On the first page,
// pass NULL for both cursor_created_at and cursor_id. Pass NULL for
// adapter to page over every instance, or an adapter name to keep only
// the instances synced with that integration (a matching
// instance_integrations row with a non-empty external_id).
func (q *Queries) GetAllInstancesByCursor(ctx context.Context, arg GetAllInstancesByCursorParams) ([]GetAllInstancesByCursorRow, error) {
	rows, err := q.db.Query(ctx, getAllInstancesByCursor,
		arg.OrganizationID,
		arg.Adapter,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitPlusOne,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllInstancesByCursorRow
	for rows.Next() {
		var i GetAllInstancesByCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedByID,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedByID,
			&i.UpdatedByName,
			&i.UpdatedAt,
			&i.Status,
			&i.LifecycleStage,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CustomerID,
			&i.CustomerSlug,
			&i.LicenseID,
			&i.LicenseSlug,
			&i.DeploymentZoneID,
			&i.DeploymentZoneSlug,
			&i.StartLicenseDate,
			&i.EndLicenseDate,
			&i.Metadata,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstancesByCustomerIDs = `-- name: GetInstancesByCustomerIDs :many
SELECT i.id,
       i.created_by_id,
       creator.name AS created_by_name,
       i.created_at,
       i.updated_by_id,
       updater.name AS updated_by_name,
       i.updated_at,
       i.status,
       i.lifecycle_stage,
       i.name,
       i.slug,
       i.description,
       i.customer_id,
       c.slug AS customer_slug,
       i.license_id,
       l.slug AS license_slug,
       i.deployment_zone_id,
       dz.slug AS deployment_zone_slug,
       i.start_license_date,
       i.end_license_date,
       i.metadata,
       i.organization_id
FROM instance i
  INNER JOIN "user" creator ON i.created_by_id = creator.id
  INNER JOIN "user" updater ON i.updated_by_id = updater.id
  LEFT JOIN "license" l ON i.license_id = l.id
  LEFT JOIN "customer" c ON i.customer_id = c.id
  LEFT JOIN "deployment_zone" dz ON i.deployment_zone_id = dz.id
WHERE i.organization_id = $1
  AND i.customer_id = ANY ($2::uuid[])
ORDER BY i.created_at, i.id
`

type GetInstancesByCustomerIDsParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	CustomerIds    []uuid.UUID `json:"customer_ids"`
}

type GetInstancesByCustomerIDsRow struct {
	ID                 uuid.UUID        `json:"id"`
	CreatedByID        uuid.UUID        `json:"created_by_id"`
	CreatedByName      string           `json:"created_by_name"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedByID        uuid.UUID        `json:"updated_by_id"`
	UpdatedByName      string           `json:"updated_by_name"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	Status             InstanceStatus   `json:"status"`
	LifecycleStage     *string          `json:"lifecycle_stage"`
	Name               string           `json:"name"`
	Slug               string           `json:"slug"`
	Description        string           `json:"description"`
	CustomerID         uuid.UUID        `json:"customer_id"`
	CustomerSlug       *string          `json:"customer_slug"`
	LicenseID          uuid.UUID        `json:"license_id"`
	LicenseSlug        *string          `json:"license_slug"`
	DeploymentZoneID   *uuid.UUID       `json:"deployment_zone_id"`
	DeploymentZoneSlug *string          `json:"deployment_zone_slug"`
	StartLicenseDate   pgtype.Timestamp `json:"start_license_date"`
	EndLicenseDate     pgtype.Timestamp `json:"end_license_date"`
	Metadata           []byte           `json:"metadata"`
	OrganizationID     uuid.UUID        `json:"organization_id"`
}

// Deterministic order: snapshot clients pick "the customer's first instance"
// as the default portal target, which must not flip between refreshes.
func (q *Queries) GetInstancesByCustomerIDs(ctx context.Context, arg GetInstancesByCustomerIDsParams) ([]GetInstancesByCustomerIDsRow, error) {
	rows, err := q.db.Query(ctx, getInstancesByCustomerIDs, arg.OrganizationID, arg.CustomerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInstancesByCustomerIDsRow
	for rows.Next() {
		var i GetInstancesByCustomerIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedByID,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedByID,
			&i.UpdatedByName,
			&i.UpdatedAt,
			&i.Status,
			&i.LifecycleStage,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CustomerID,
			&i.CustomerSlug,
			&i.LicenseID,
			&i.LicenseSlug,
			&i.DeploymentZoneID,
			&i.DeploymentZoneSlug,
			&i.StartLicenseDate,
			&i.EndLicenseDate,
			&i.Metadata,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstancesByIDs = `-- name: GetInstancesByIDs :many
SELECT i.id,
       i.created_by_id,
       creator.name AS created_by_name,
       i.created_at,
       i.updated_by_id,
       updater.name AS updated_by_name,
       i.updated_at,
       i.status,
       i.lifecycle_stage,
       i.name,
       i.slug,
       i.description,
       i.customer_id,
       c.slug AS customer_slug,
       i.license_id,
       l.slug AS license_slug,
       i.deployment_zone_id,
       dz.slug AS deployment_zone_slug,
       i.start_license_date,
       i.end_license_date,
       i.metadata,
       i.organization_id
FROM instance i
  INNER JOIN "user" creator ON i.created_by_id = creator.id
  INNER JOIN "user" updater ON i.updated_by_id = updater.id
  LEFT JOIN "license" l ON i.license_id = l.id
  LEFT JOIN "customer" c ON i.customer_id = c.id
  LEFT JOIN "deployment_zone" dz ON i.deployment_zone_id = dz.id
WHERE i.organization_id = $1
  AND i.id = ANY ($2::uuid[])
`

type GetInstancesByIDsParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	InstanceIds    []uuid.UUID `json:"instance_ids"`
}

type GetInstancesByIDsRow struct {
	ID                 uuid.UUID        `json:"id"`
	CreatedByID        uuid.UUID        `json:"created_by_id"`
	CreatedByName      string           `json:"created_by_name"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedByID        uuid.UUID        `json:"updated_by_id"`
	UpdatedByName      string           `json:"updated_by_name"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	Status             InstanceStatus   `json:"status"`
	LifecycleStage     *string          `json:"lifecycle_stage"`
	Name               string           `json:"name"`
	Slug               string           `json:"slug"`
	Description        string           `json:"description"`
	CustomerID         uuid.UUID        `json:"customer_id"`
	CustomerSlug       *string          `json:"customer_slug"`
	LicenseID          uuid.UUID        `json:"license_id"`
	LicenseSlug        *string          `json:"license_slug"`
	DeploymentZoneID   *uuid.UUID       `json:"deployment_zone_id"`
	DeploymentZoneSlug *string          `json:"deployment_zone_slug"`
	StartLicenseDate   pgtype.Timestamp `json:"start_license_date"`
	EndLicenseDate     pgtype.Timestamp `json:"end_license_date"`
	Metadata           []byte           `json:"metadata"`
	OrganizationID     uuid.UUID        `json:"organization_id"`
}

func (q *Queries) GetInstancesByIDs(ctx context.Context, arg GetInstancesByIDsParams) ([]GetInstancesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getInstancesByIDs, arg.OrganizationID, arg.InstanceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInstancesByIDsRow
	for rows.Next() {
		var i GetInstancesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedByID,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedByID,
			&i.UpdatedByName,
			&i.UpdatedAt,
			&i.Status,
			&i.LifecycleStage,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CustomerID,
			&i.CustomerSlug,
			&i.LicenseID,
			&i.LicenseSlug,
			&i.DeploymentZoneID,
			&i.DeploymentZoneSlug,
			&i.StartLicenseDate,
			&i.EndLicenseDate,
			&i.Metadata,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstancesByLicenseIDs = `-- name: GetInstancesByLicenseIDs :many
SELECT i.id,
       i.created_by_id,
       creator.name AS created_by_name,
       i.created_at,
       i.updated_by_id,
       updater.name AS updated_by_name,
       i.updated_at,
       i.status,
       i.lifecycle_stage,
       i.name,
       i.slug,
       i.description,
       i.customer_id,
       c.slug AS customer_slug,
       i.license_id,
       l.slug AS license_slug,
       i.deployment_zone_id,
       dz.slug AS deployment_zone_slug,
       i.start_license_date,
       i.end_license_date,
       i.metadata,
       i.organization_id
FROM instance i
  INNER JOIN "user" creator ON i.created_by_id = creator.id
  INNER JOIN "user" updater ON i.updated_by_id = updater.id
  LEFT JOIN "license" l ON i.license_id = l.id
  LEFT JOIN "customer" c ON i.customer_id = c.id
  LEFT JOIN "deployment_zone" dz ON i.deployment_zone_id = dz.id
WHERE i.organization_id = $1
  AND i.license_id = ANY ($2::uuid[])
`

type GetInstancesByLicenseIDsParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	LicenseIds     []uuid.UUID `json:"license_ids"`
}

type GetInstancesByLicenseIDsRow struct {
	ID                 uuid.UUID        `json:"id"`
	CreatedByID        uuid.UUID        `json:"created_by_id"`
	CreatedByName      string           `json:"created_by_name"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedByID        uuid.UUID        `json:"updated_by_id"`
	UpdatedByName      string           `json:"updated_by_name"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	Status             InstanceStatus   `json:"status"`
	LifecycleStage     *string          `json:"lifecycle_stage"`
	Name               string           `json:"name"`
	Slug               string           `json:"slug"`
	Description        string           `json:"description"`
	CustomerID         uuid.UUID        `json:"customer_id"`
	CustomerSlug       *string          `json:"customer_slug"`
	LicenseID          uuid.UUID        `json:"license_id"`
	LicenseSlug        *string          `json:"license_slug"`
	DeploymentZoneID   *uuid.UUID       `json:"deployment_zone_id"`
	DeploymentZoneSlug *string          `json:"deployment_zone_slug"`
	StartLicenseDate   pgtype.Timestamp `json:"start_license_date"`
	EndLicenseDate     pgtype.Timestamp `json:"end_license_date"`
	Metadata           []byte           `json:"metadata"`
	OrganizationID     uuid.UUID        `json:"organization_id"`
}

func (q *Queries) GetInstancesByLicenseIDs(ctx context.Context, arg GetInstancesByLicenseIDsParams) ([]GetInstancesByLicenseIDsRow, error) {
	rows, err := q.db.Query(ctx, getInstancesByLicenseIDs, arg.OrganizationID, arg.LicenseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInstancesByLicenseIDsRow
	for rows.Next() {
		var i GetInstancesByLicenseIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedByID,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedByID,
			&i.UpdatedByName,
			&i.UpdatedAt,
			&i.Status,
			&i.LifecycleStage,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CustomerID,
			&i.CustomerSlug,
			&i.LicenseID,
			&i.LicenseSlug,
			&i.DeploymentZoneID,
			&i.DeploymentZoneSlug,
			&i.StartLicenseDate,
			&i.EndLicenseDate,
			&i.Metadata,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstancesByReleaseIDs = `-- name: GetInstancesByReleaseIDs :many
SELECT DISTINCT ON (d.release_id, i.id)
       d.release_id,
       i.id,
       i.created_by_id,
       creator.name AS created_by_name,
       i.created_at,
       i.updated_by_id,
       updater.name AS updated_by_name,
       i.updated_at,
       i.status,
       i.lifecycle_stage,
       i.name,
       i.slug,
       i.description,
       i.customer_id,
       c.slug AS customer_slug,
       i.license_id,
       l.slug AS license_slug,
       i.deployment_zone_id,
       dz.slug AS deployment_zone_slug,
       i.start_license_date,
       i.end_license_date,
       i.metadata,
       i.organization_id
FROM deployment d
  INNER JOIN instance i ON i.deployment_zone_id = d.deployment_zone_id
  INNER JOIN "user" creator ON i.created_by_id = creator.id
  INNER JOIN "user" updater ON i.updated_by_id = updater.id
  LEFT JOIN "license" l ON i.license_id = l.id
  LEFT JOIN "customer" c ON i.customer_id = c.id
  LEFT JOIN "deployment_zone" dz ON i.deployment_zone_id = dz.id
WHERE d.organization_id = $1
  AND d.release_id = ANY ($2::uuid[])
ORDER BY d.release_id, i.id, d.created_at DESC
`

type GetInstancesByReleaseIDsParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	ReleaseIds     []uuid.UUID `json:"release_ids"`
}

type GetInstancesByReleaseIDsRow struct {
	ReleaseID          uuid.UUID        `json:"release_id"`
	ID                 uuid.UUID        `json:"id"`
	CreatedByID        uuid.UUID        `json:"created_by_id"`
	CreatedByName      string           `json:"created_by_name"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedByID        uuid.UUID        `json:"updated_by_id"`
	UpdatedByName      string           `json:"updated_by_name"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	Status             InstanceStatus   `json:"status"`
	LifecycleStage     *string          `json:"lifecycle_stage"`
	Name               string           `json:"name"`
	Slug               string           `json:"slug"`
	Description        string           `json:"description"`
	CustomerID         uuid.UUID        `json:"customer_id"`
	CustomerSlug       *string          `json:"customer_slug"`
	LicenseID          uuid.UUID        `json:"license_id"`
	LicenseSlug        *string          `json:"license_slug"`
	DeploymentZoneID   *uuid.UUID       `json:"deployment_zone_id"`
	DeploymentZoneSlug *string          `json:"deployment_zone_slug"`
	StartLicenseDate   pgtype.Timestamp `json:"start_license_date"`
	EndLicenseDate     pgtype.Timestamp `json:"end_license_date"`
	Metadata           []byte           `json:"metadata"`
	OrganizationID     uuid.UUID        `json:"organization_id"`
}

func (q *Queries) GetInstancesByReleaseIDs(ctx context.Context, arg GetInstancesByReleaseIDsParams) ([]GetInstancesByReleaseIDsRow, error) {
	rows, err := q.db.Query(ctx, getInstancesByReleaseIDs, arg.OrganizationID, arg.ReleaseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInstancesByReleaseIDsRow
	for rows.Next() {
		var i GetInstancesByReleaseIDsRow
		if err := rows.Scan(
			&i.ReleaseID,
			&i.ID,
			&i.CreatedByID,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedByID,
			&i.UpdatedByName,
			&i.UpdatedAt,
			&i.Status,
			&i.LifecycleStage,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CustomerID,
			&i.CustomerSlug,
			&i.LicenseID,
			&i.LicenseSlug,
			&i.DeploymentZoneID,
			&i.DeploymentZoneSlug,
			&i.StartLicenseDate,
			&i.EndLicenseDate,
			&i.Metadata,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOneInstance = `-- name: GetOneInstance :one
SELECT i.id, i.created_by_id, creator.name AS created_by_name, i.created_at,
       i.updated_by_id, updater.name AS updated_by_name, i.updated_at, i.status, i.lifecycle_stage, i.name, i.slug, i.description,
       i.customer_id,
       c.slug AS customer_slug,
       i.license_id,
       l.slug AS license_slug,
       i.deployment_zone_id,
       dz.slug AS deployment_zone_slug,
       i.start_license_date,
       i.end_license_date,
       i.metadata,
       i.organization_id
FROM instance i
  INNER JOIN "user" creator ON i.created_by_id = creator.id
  INNER JOIN "user" updater ON i.updated_by_id = updater.id
  LEFT JOIN "license" l ON i.license_id = l.id
  LEFT JOIN "customer" c ON i.customer_id = c.id
  LEFT JOIN "deployment_zone" dz ON i.deployment_zone_id = dz.id
WHERE i.organization_id = $1
  AND i.slug = $2
`

type GetOneInstanceParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Slug           string    `json:"slug"`
}

type GetOneInstanceRow struct {
	ID                 uuid.UUID        `json:"id"`
	CreatedByID        uuid.UUID        `json:"created_by_id"`
	CreatedByName      string           `json:"created_by_name"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedByID        uuid.UUID        `json:"updated_by_id"`
	UpdatedByName      string           `json:"updated_by_name"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	Status             InstanceStatus   `json:"status"`
	LifecycleStage     *string          `json:"lifecycle_stage"`
	Name               string           `json:"name"`
	Slug               string           `json:"slug"`
	Description        string           `json:"description"`
	CustomerID         uuid.UUID        `json:"customer_id"`
	CustomerSlug       *string          `json:"customer_slug"`
	LicenseID          uuid.UUID        `json:"license_id"`
	LicenseSlug        *string          `json:"license_slug"`
	DeploymentZoneID   *uuid.UUID       `json:"deployment_zone_id"`
	DeploymentZoneSlug *string          `json:"deployment_zone_slug"`
	StartLicenseDate   pgtype.Timestamp `json:"start_license_date"`
	EndLicenseDate     pgtype.Timestamp `json:"end_license_date"`
	Metadata           []byte           `json:"metadata"`
	OrganizationID     uuid.UUID        `json:"organization_id"`
}

func (q *Queries) GetOneInstance(ctx context.Context, arg GetOneInstanceParams) (GetOneInstanceRow, error) {
	row := q.db.QueryRow(ctx, getOneInstance, arg.OrganizationID, arg.Slug)
	var i GetOneInstanceRow
	err := row.Scan(
		&i.ID,
		&i.CreatedByID,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedByID,
		&i.UpdatedByName,
		&i.UpdatedAt,
		&i.Status,
		&i.LifecycleStage,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CustomerID,
		&i.CustomerSlug,
		&i.LicenseID,
		&i.LicenseSlug,
		&i.DeploymentZoneID,
		&i.DeploymentZoneSlug,
		&i.StartLicenseDate,
		&i.EndLicenseDate,
		&i.Metadata,
		&i.OrganizationID,
	)
	return i, err
}

const instanceExists = `-- name: InstanceExists :one
SELECT EXISTS (
  SELECT 1
  FROM instance i
  WHERE i.id = $1
              AND i.organization_id = $2
)
`

type InstanceExistsParams struct {
	InstanceID     uuid.UUID `json:"instance_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) InstanceExists(ctx context.Context, arg InstanceExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, instanceExists, arg.InstanceID, arg.OrganizationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateInstanceLifecycleStage = `-- name: UpdateInstanceLifecycleStage :one
WITH updated AS (
  UPDATE instance i
  SET updated_by_id = uo.user_id,
      updated_at = now(),
      lifecycle_stage = $1
  FROM user_on_organization uo
  WHERE uo.organization_id = $2
         AND uo.user_id = $3
         AND uo.deleted_at IS NULL
         AND i.organization_id = uo.organization_id
         AND i.slug = $4
  RETURNING i.id, i.created_by_id, i.created_at, i.updated_by_id, i.updated_at, i.name, i.slug, i.description, i.customer_id, i.license_id, i.deployment_zone_id, i.start_license_date, i.end_license_date, i.metadata, i.organization_id, i.status, i.lifecycle_stage
)
SELECT updated.id, updated.created_by_id, updated.created_at, updated.updated_by_id, updated.updated_at, updated.name, updated.slug, updated.description, updated.customer_id, updated.license_id, updated.deployment_zone_id, updated.start_license_date, updated.end_license_date, updated.metadata, updated.organization_id, updated.status, updated.lifecycle_stage,
       creator.name AS created_by_name,
       updater.name AS updated_by_name,
       l.slug AS license_slug,
       c.slug AS customer_slug,
       dz.slug AS deployment_zone_slug
FROM updated
  INNER JOIN "user" creator ON updated.created_by_id = creator.id
  INNER JOIN "user" updater ON updated.updated_by_id = updater.id
  LEFT JOIN "license" l ON updated.license_id = l.id
  LEFT JOIN "customer" c ON updated.customer_id = c.id
  LEFT JOIN "deployment_zone" dz ON updated.deployment_zone_id = dz.id
`

type UpdateInstanceLifecycleStageParams struct {
	LifecycleStage *string   `json:"lifecycle_stage"`
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Slug           string    `json:"slug"`
}

type UpdateInstanceLifecycleStageRow struct {
	ID                 uuid.UUID        `json:"id"`
	CreatedByID        uuid.UUID        `json:"created_by_id"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedByID        uuid.UUID        `json:"updated_by_id"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	Name               string           `json:"name"`
	Slug               string           `json:"slug"`
	Description        string           `json:"description"`
	CustomerID         uuid.UUID        `json:"customer_id"`
	LicenseID          uuid.UUID        `json:"license_id"`
	DeploymentZoneID   *uuid.UUID       `json:"deployment_zone_id"`
	StartLicenseDate   pgtype.Timestamp `json:"start_license_date"`
	EndLicenseDate     pgtype.Timestamp `json:"end_license_date"`
	Metadata           []byte           `json:"metadata"`
	OrganizationID     uuid.UUID        `json:"organization_id"`
	Status             InstanceStatus   `json:"status"`
	LifecycleStage     *string          `json:"lifecycle_stage"`
	CreatedByName      string           `json:"created_by_name"`
	UpdatedByName      string           `json:"updated_by_name"`
	LicenseSlug        *string          `json:"license_slug"`
	CustomerSlug       *string          `json:"customer_slug"`
	DeploymentZoneSlug *string          `json:"deployment_zone_slug"`
}

func (q *Queries) UpdateInstanceLifecycleStage(ctx context.Context, arg UpdateInstanceLifecycleStageParams) (UpdateInstanceLifecycleStageRow, error) {
	row := q.db.QueryRow(ctx, updateInstanceLifecycleStage,
		arg.LifecycleStage,
		arg.OrganizationID,
		arg.UserID,
		arg.Slug,
	)
	var i UpdateInstanceLifecycleStageRow
	err := row.Scan(
		&i.ID,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedByID,
		&i.UpdatedAt,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CustomerID,
		&i.LicenseID,
		&i.DeploymentZoneID,
		&i.StartLicenseDate,
		&i.EndLicenseDate,
		&i.Metadata,
		&i.OrganizationID,
		&i.Status,
		&i.LifecycleStage,
		&i.CreatedByName,
		&i.UpdatedByName,
		&i.LicenseSlug,
		&i.CustomerSlug,
		&i.DeploymentZoneSlug,
	)
	return i, err
}

const updateInstanceStatus = `-- name: UpdateInstanceStatus :one
WITH updated AS (
  UPDATE instance i
  SET updated_by_id = uo.user_id,
      updated_at = now(),
      status = $1::instance_status
  FROM user_on_organization uo
  WHERE uo.organization_id = $2
         AND uo.user_id = $3
         AND uo.deleted_at IS NULL
         AND i.organization_id = uo.organization_id
         AND i.slug = $4
  RETURNING i.id, i.created_by_id, i.created_at, i.updated_by_id, i.updated_at, i.name, i.slug, i.description, i.customer_id, i.license_id, i.deployment_zone_id, i.start_license_date, i.end_license_date, i.metadata, i.organization_id, i.status, i.lifecycle_stage
)
SELECT updated.id, updated.created_by_id, updated.created_at, updated.updated_by_id, updated.updated_at, updated.name, updated.slug, updated.description, updated.customer_id, updated.license_id, updated.deployment_zone_id, updated.start_license_date, updated.end_license_date, updated.metadata, updated.organization_id, updated.status, updated.lifecycle_stage,
       creator.name AS created_by_name,
       updater.name AS updated_by_name,
       l.slug AS license_slug,
       c.slug AS customer_slug,
       dz.slug AS deployment_zone_slug
FROM updated
  INNER JOIN "user" creator ON updated.created_by_id = creator.id
  INNER JOIN "user" updater ON updated.updated_by_id = updater.id
  LEFT JOIN "license" l ON updated.license_id = l.id
  LEFT JOIN "customer" c ON updated.customer_id = c.id
  LEFT JOIN "deployment_zone" dz ON updated.deployment_zone_id = dz.id
`

type UpdateInstanceStatusParams struct {
	Status         InstanceStatus `json:"status"`
	OrganizationID uuid.UUID      `json:"organization_id"`
	UserID         uuid.UUID      `json:"user_id"`
	Slug           string         `json:"slug"`
}

type UpdateInstanceStatusRow struct {
	ID                 uuid.UUID        `json:"id"`
	CreatedByID        uuid.UUID        `json:"created_by_id"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedByID        uuid.UUID        `json:"updated_by_id"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	Name               string           `json:"name"`
	Slug               string           `json:"slug"`
	Description        string           `json:"description"`
	CustomerID         uuid.UUID        `json:"customer_id"`
	LicenseID          uuid.UUID        `json:"license_id"`
	DeploymentZoneID   *uuid.UUID       `json:"deployment_zone_id"`
	StartLicenseDate   pgtype.Timestamp `json:"start_license_date"`
	EndLicenseDate     pgtype.Timestamp `json:"end_license_date"`
	Metadata           []byte           `json:"metadata"`
	OrganizationID     uuid.UUID        `json:"organization_id"`
	Status             InstanceStatus   `json:"status"`
	LifecycleStage     *string          `json:"lifecycle_stage"`
	CreatedByName      string           `json:"created_by_name"`
	UpdatedByName      string           `json:"updated_by_name"`
	LicenseSlug        *string          `json:"license_slug"`
	CustomerSlug       *string          `json:"customer_slug"`
	DeploymentZoneSlug *string          `json:"deployment_zone_slug"`
}

func (q *Queries) UpdateInstanceStatus(ctx context.Context, arg UpdateInstanceStatusParams) (UpdateInstanceStatusRow, error) {
	row := q.db.QueryRow(ctx, updateInstanceStatus,
		arg.Status,
		arg.OrganizationID,
		arg.UserID,
		arg.Slug,
	)
	var i UpdateInstanceStatusRow
	err := row.Scan(
		&i.ID,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedByID,
		&i.UpdatedAt,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CustomerID,
		&i.LicenseID,
		&i.DeploymentZoneID,
		&i.StartLicenseDate,
		&i.EndLicenseDate,
		&i.Metadata,
		&i.OrganizationID,
		&i.Status,
		&i.LifecycleStage,
		&i.CreatedByName,
		&i.UpdatedByName,
		&i.LicenseSlug,
		&i.CustomerSlug,
		&i.DeploymentZoneSlug,
	)
	return i, err
}
