// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
)

type AggregationMethod string

const (
	AggregationMethodSUM     AggregationMethod = "SUM"
	AggregationMethodCOUNT   AggregationMethod = "COUNT"
	AggregationMethodAVERAGE AggregationMethod = "AVERAGE"
	AggregationMethodMAX     AggregationMethod = "MAX"
	AggregationMethodMIN     AggregationMethod = "MIN"
	AggregationMethodLATEST  AggregationMethod = "LATEST"
)

func (e *AggregationMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AggregationMethod(s)
	case string:
		*e = AggregationMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for AggregationMethod: %T", src)
	}
	return nil
}

type NullAggregationMethod struct {
	AggregationMethod AggregationMethod `json:"aggregation_method"`
	Valid             bool              `json:"valid"` // Valid is true if AggregationMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAggregationMethod) Scan(value interface{}) error {
	if value == nil {
		ns.AggregationMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AggregationMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAggregationMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AggregationMethod), nil
}

type EntitlementResetAnchor string

const (
	EntitlementResetAnchorCALENDAR     EntitlementResetAnchor = "CALENDAR"
	EntitlementResetAnchorLICENSESTART EntitlementResetAnchor = "LICENSE_START"
)

func (e *EntitlementResetAnchor) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntitlementResetAnchor(s)
	case string:
		*e = EntitlementResetAnchor(s)
	default:
		return fmt.Errorf("unsupported scan type for EntitlementResetAnchor: %T", src)
	}
	return nil
}

type NullEntitlementResetAnchor struct {
	EntitlementResetAnchor EntitlementResetAnchor `json:"entitlement_reset_anchor"`
	Valid                  bool                   `json:"valid"` // Valid is true if EntitlementResetAnchor is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntitlementResetAnchor) Scan(value interface{}) error {
	if value == nil {
		ns.EntitlementResetAnchor, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntitlementResetAnchor.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntitlementResetAnchor) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntitlementResetAnchor), nil
}

type EntitlementResetPeriod string

const (
	EntitlementResetPeriodHOUR  EntitlementResetPeriod = "HOUR"
	EntitlementResetPeriodDAY   EntitlementResetPeriod = "DAY"
	EntitlementResetPeriodWEEK  EntitlementResetPeriod = "WEEK"
	EntitlementResetPeriodMONTH EntitlementResetPeriod = "MONTH"
	EntitlementResetPeriodYEAR  EntitlementResetPeriod = "YEAR"
)

func (e *EntitlementResetPeriod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntitlementResetPeriod(s)
	case string:
		*e = EntitlementResetPeriod(s)
	default:
		return fmt.Errorf("unsupported scan type for EntitlementResetPeriod: %T", src)
	}
	return nil
}

type NullEntitlementResetPeriod struct {
	EntitlementResetPeriod EntitlementResetPeriod `json:"entitlement_reset_period"`
	Valid                  bool                   `json:"valid"` // Valid is true if EntitlementResetPeriod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntitlementResetPeriod) Scan(value interface{}) error {
	if value == nil {
		ns.EntitlementResetPeriod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntitlementResetPeriod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntitlementResetPeriod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntitlementResetPeriod), nil
}

type EntitlementType string

const (
	EntitlementTypeBOOLEAN        EntitlementType = "BOOLEAN"
	EntitlementTypeNUMBER         EntitlementType = "NUMBER"
	EntitlementTypeCONFIG         EntitlementType = "CONFIG"
	EntitlementTypeNUMBERAICREDIT EntitlementType = "NUMBER_AI_CREDIT"
)

func (e *EntitlementType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntitlementType(s)
	case string:
		*e = EntitlementType(s)
	default:
		return fmt.Errorf("unsupported scan type for EntitlementType: %T", src)
	}
	return nil
}

type NullEntitlementType struct {
	EntitlementType EntitlementType `json:"entitlement_type"`
	Valid           bool            `json:"valid"` // Valid is true if EntitlementType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntitlementType) Scan(value interface{}) error {
	if value == nil {
		ns.EntitlementType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntitlementType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntitlementType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntitlementType), nil
}

type InstanceStatus string

const (
	InstanceStatusHEALTHY     InstanceStatus = "HEALTHY"
	InstanceStatusDEGRADED    InstanceStatus = "DEGRADED"
	InstanceStatusINCIDENT    InstanceStatus = "INCIDENT"
	InstanceStatusMAINTENANCE InstanceStatus = "MAINTENANCE"
)

func (e *InstanceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InstanceStatus(s)
	case string:
		*e = InstanceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InstanceStatus: %T", src)
	}
	return nil
}

type NullInstanceStatus struct {
	InstanceStatus InstanceStatus `json:"instance_status"`
	Valid          bool           `json:"valid"` // Valid is true if InstanceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInstanceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InstanceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InstanceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInstanceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InstanceStatus), nil
}

type UsageReportBehavior string

const (
	UsageReportBehaviorAppend UsageReportBehavior = "append"
	UsageReportBehaviorSet    UsageReportBehavior = "set"
)

func (e *UsageReportBehavior) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsageReportBehavior(s)
	case string:
		*e = UsageReportBehavior(s)
	default:
		return fmt.Errorf("unsupported scan type for UsageReportBehavior: %T", src)
	}
	return nil
}

type NullUsageReportBehavior struct {
	UsageReportBehavior UsageReportBehavior `json:"usage_report_behavior"`
	Valid               bool                `json:"valid"` // Valid is true if UsageReportBehavior is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsageReportBehavior) Scan(value interface{}) error {
	if value == nil {
		ns.UsageReportBehavior, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsageReportBehavior.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsageReportBehavior) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsageReportBehavior), nil
}
