// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage_ledger.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendUsageLedger = `-- name: AppendUsageLedger :exec
INSERT INTO usage_ledger (organization_id, instance_id, entitlement_id, license_id,
                          report_seq, reported_at, window_start, window_end,
                          behavior, aggregation_method,
                          reported_value, value_before, value_after, event_count_after,
                          limit_value, overage_percent, transaction_id, properties)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8,
        $9, $10,
        $11::text::numeric, $12::text::numeric,
        $13::text::numeric, $14,
        $15::text::numeric, $16,
        $17, $18)
`

type AppendUsageLedgerParams struct {
	OrganizationID    uuid.UUID           `json:"organization_id"`
	InstanceID        uuid.UUID           `json:"instance_id"`
	EntitlementID     uuid.UUID           `json:"entitlement_id"`
	LicenseID         uuid.UUID           `json:"license_id"`
	ReportSeq         int64               `json:"report_seq"`
	ReportedAt        pgtype.Timestamp    `json:"reported_at"`
	WindowStart       pgtype.Timestamp    `json:"window_start"`
	WindowEnd         pgtype.Timestamp    `json:"window_end"`
	Behavior          UsageReportBehavior `json:"behavior"`
	AggregationMethod AggregationMethod   `json:"aggregation_method"`
	ReportedValue     string              `json:"reported_value"`
	ValueBefore       string              `json:"value_before"`
	ValueAfter        string              `json:"value_after"`
	EventCountAfter   int32               `json:"event_count_after"`
	LimitValue        *string             `json:"limit_value"`
	OveragePercent    int16               `json:"overage_percent"`
	TransactionID     *string             `json:"transaction_id"`
	Properties        []byte              `json:"properties"`
}

// One row per ACCEPTED report, written by the report transaction right after
// AcceptEntitlementUsage and under the same lock. The NUMERIC values arrive as
// decimal strings formatted from the float64 counter, so value_after -
// value_before is exact.
func (q *Queries) AppendUsageLedger(ctx context.Context, arg AppendUsageLedgerParams) error {
	_, err := q.db.Exec(ctx, appendUsageLedger,
		arg.OrganizationID,
		arg.InstanceID,
		arg.EntitlementID,
		arg.LicenseID,
		arg.ReportSeq,
		arg.ReportedAt,
		arg.WindowStart,
		arg.WindowEnd,
		arg.Behavior,
		arg.AggregationMethod,
		arg.ReportedValue,
		arg.ValueBefore,
		arg.ValueAfter,
		arg.EventCountAfter,
		arg.LimitValue,
		arg.OveragePercent,
		arg.TransactionID,
		arg.Properties,
	)
	return err
}

const checkUsageLedgerInvariants = `-- name: CheckUsageLedgerInvariants :one
WITH in_range AS (
  SELECT ul.report_seq, ul.window_start, ul.value_before, ul.value_after
  FROM usage_ledger ul
  WHERE ul.organization_id = $1
    AND ul.instance_id = $2
    AND ul.entitlement_id = $3
    AND ul.reported_at >= $4
    AND ul.reported_at < $5
),
bounds AS (
  SELECT min(r.report_seq) AS first_seq, max(r.report_seq) AS last_seq, count(*) AS row_count
  FROM in_range r
),
counter AS (
  SELECT eu.report_seq, (eu.value ->> 'value')::numeric AS value, eu.period_start
  FROM entitlement_usage eu
  WHERE eu.instance_id = $2
    AND eu.entitlement_id = $3
),
pred AS (
  SELECT ul.report_seq, ul.window_start, ul.value_before, ul.value_after
  FROM usage_ledger ul, bounds b
  WHERE ul.organization_id = $1
    AND ul.instance_id = $2
    AND ul.entitlement_id = $3
    AND ul.report_seq = b.first_seq - 1
),
chain AS (
  SELECT c.report_seq, c.window_start, c.value_before, c.in_period,
         lag(c.report_seq) OVER (ORDER BY c.report_seq) AS prev_seq,
         lag(c.window_start) OVER (ORDER BY c.report_seq) AS prev_window_start,
         lag(c.value_after) OVER (ORDER BY c.report_seq) AS prev_value_after
  FROM (SELECT r.report_seq, r.window_start, r.value_before, r.value_after, TRUE AS in_period FROM in_range r
        UNION ALL
        SELECT p.report_seq, p.window_start, p.value_before, p.value_after, FALSE AS in_period FROM pred p) c
),
tail AS (
  SELECT ul.window_start, ul.value_after
  FROM usage_ledger ul, counter k
  WHERE ul.organization_id = $1
    AND ul.instance_id = $2
    AND ul.entitlement_id = $3
    AND ul.report_seq = k.report_seq
)
SELECT
  coalesce(b.first_seq, 0)::bigint AS first_seq,
  coalesce(b.last_seq, 0)::bigint AS last_seq,
  b.row_count::bigint AS row_count,
  coalesce((SELECT k.report_seq FROM counter k), -1)::bigint AS counter_seq,
  coalesce((SELECT trim_scale(k.value)::text FROM counter k), '')::text AS counter_value,
  (SELECT count(DISTINCT ul.report_seq)
     FROM usage_ledger ul, counter k
    WHERE ul.organization_id = $1
      AND ul.instance_id = $2
      AND ul.entitlement_id = $3
      AND ul.report_seq BETWEEN b.first_seq AND k.report_seq)::bigint AS seqs_present,
  EXISTS (SELECT 1 FROM pred) AS pred_exists,
  EXISTS (SELECT 1
            FROM usage_ledger ul
           WHERE ul.organization_id = $1
             AND ul.instance_id = $2
             AND ul.entitlement_id = $3
             AND ul.report_seq < b.first_seq) AS lower_exists,
  coalesce((SELECT min(c.report_seq) FROM chain c
    WHERE c.in_period
      AND c.prev_seq = c.report_seq - 1
      AND c.prev_window_start IS NOT DISTINCT FROM c.window_start
      AND c.value_before <> c.prev_value_after), 0)::bigint AS first_chain_break,
  coalesce((SELECT min(c.report_seq) FROM chain c, usage_ledger_epoch e
    WHERE c.in_period
      AND c.window_start IS NOT NULL
      AND c.window_start >= e.epoch_at + INTERVAL '24 hours'
      AND ((c.prev_seq IS NULL AND c.report_seq = 1)
           OR (c.prev_seq = c.report_seq - 1 AND c.prev_window_start IS DISTINCT FROM c.window_start))
      AND c.value_before <> 0), 0)::bigint AS first_window_start_break,
  EXISTS (SELECT 1 FROM tail) AS tail_exists,
  coalesce((SELECT t.window_start IS NOT DISTINCT FROM k.period_start FROM tail t, counter k), FALSE)::boolean AS tail_in_counter_window,
  coalesce((SELECT t.value_after = k.value FROM tail t, counter k), FALSE)::boolean AS tail_matches_counter,
  coalesce((SELECT trim_scale(t.value_after)::text FROM tail t), '')::text AS tail_value_after
FROM bounds b
`

type CheckUsageLedgerInvariantsParams struct {
	OrganizationID uuid.UUID        `json:"organization_id"`
	InstanceID     uuid.UUID        `json:"instance_id"`
	EntitlementID  uuid.UUID        `json:"entitlement_id"`
	FromAt         pgtype.Timestamp `json:"from_at"`
	ToAt           pgtype.Timestamp `json:"to_at"`
}

type CheckUsageLedgerInvariantsRow struct {
	FirstSeq              int64  `json:"first_seq"`
	LastSeq               int64  `json:"last_seq"`
	RowCount              int64  `json:"row_count"`
	CounterSeq            int64  `json:"counter_seq"`
	CounterValue          string `json:"counter_value"`
	SeqsPresent           int64  `json:"seqs_present"`
	PredExists            bool   `json:"pred_exists"`
	LowerExists           bool   `json:"lower_exists"`
	FirstChainBreak       int64  `json:"first_chain_break"`
	FirstWindowStartBreak int64  `json:"first_window_start_break"`
	TailExists            bool   `json:"tail_exists"`
	TailInCounterWindow   bool   `json:"tail_in_counter_window"`
	TailMatchesCounter    bool   `json:"tail_matches_counter"`
	TailValueAfter        string `json:"tail_value_after"`
}

// Everything the journal invariants need about a pair, in one statement so
// that one snapshot answers them all: a report committing meanwhile cannot
// make the counter and the journal disagree.
//
//	in_range     the rows dated in [from, to)
//	pred         the row just before the first of them, whatever its date
//	counter      the live counter: its value, window and report_seq
//	tail         the row the counter's report_seq names
//
// 0 stands for "none" in the seq columns (a report_seq is at least 1), and -1
// for "no counter" in counter_seq.
//
// The chain is checked over pred and in_range, between consecutive reports
// only (a gap is the sequence invariant's to report): a row's value_before
// must be the previous row's value_after when both are in one window, and the
// first row of a window opened a day after the journal existed must start at 0.
func (q *Queries) CheckUsageLedgerInvariants(ctx context.Context, arg CheckUsageLedgerInvariantsParams) (CheckUsageLedgerInvariantsRow, error) {
	row := q.db.QueryRow(ctx, checkUsageLedgerInvariants,
		arg.OrganizationID,
		arg.InstanceID,
		arg.EntitlementID,
		arg.FromAt,
		arg.ToAt,
	)
	var i CheckUsageLedgerInvariantsRow
	err := row.Scan(
		&i.FirstSeq,
		&i.LastSeq,
		&i.RowCount,
		&i.CounterSeq,
		&i.CounterValue,
		&i.SeqsPresent,
		&i.PredExists,
		&i.LowerExists,
		&i.FirstChainBreak,
		&i.FirstWindowStartBreak,
		&i.TailExists,
		&i.TailInCounterWindow,
		&i.TailMatchesCounter,
		&i.TailValueAfter,
	)
	return i, err
}

const findUsageReportByTransactionID = `-- name: FindUsageReportByTransactionID :one
SELECT ul.report_seq,
       ul.reported_at,
       ul.window_start,
       ul.window_end,
       ul.behavior,
       ul.reported_value::text                                   AS reported_value,
       (ul.reported_value = $1::text::numeric)::bool AS same_value,
       ul.value_after::float8                                    AS value_after,
       ul.event_count_after,
       -- -1 for an unlimited grant (NULL limit), as the response says it.
       coalesce(ul.limit_value::float8, -1)::float8              AS limit_value,
       ul.license_id,
       l.slug                                                    AS license_slug
FROM usage_ledger ul
LEFT JOIN "license" l
  ON l.id = ul.license_id
 AND l.organization_id = ul.organization_id
WHERE ul.organization_id = $2
  AND ul.instance_id = $3
  AND ul.entitlement_id = $4
  AND ul.transaction_id = $5
  AND ul.reported_at >= $6
  AND ul.reported_at < $7
ORDER BY ul.reported_at DESC
LIMIT 1
`

type FindUsageReportByTransactionIDParams struct {
	Value          string           `json:"value"`
	OrganizationID uuid.UUID        `json:"organization_id"`
	InstanceID     uuid.UUID        `json:"instance_id"`
	EntitlementID  uuid.UUID        `json:"entitlement_id"`
	TransactionID  *string          `json:"transaction_id"`
	NotBefore      pgtype.Timestamp `json:"not_before"`
	NotAfter       pgtype.Timestamp `json:"not_after"`
}

type FindUsageReportByTransactionIDRow struct {
	ReportSeq       int64               `json:"report_seq"`
	ReportedAt      pgtype.Timestamp    `json:"reported_at"`
	WindowStart     pgtype.Timestamp    `json:"window_start"`
	WindowEnd       pgtype.Timestamp    `json:"window_end"`
	Behavior        UsageReportBehavior `json:"behavior"`
	ReportedValue   string              `json:"reported_value"`
	SameValue       bool                `json:"same_value"`
	ValueAfter      float64             `json:"value_after"`
	EventCountAfter int32               `json:"event_count_after"`
	LimitValue      float64             `json:"limit_value"`
	LicenseID       uuid.UUID           `json:"license_id"`
	LicenseSlug     *string             `json:"license_slug"`
}

// The idempotency-key lookup: the report a key was last accepted under within
// [not_before, not_after), run under the pair's lock. same_value compares the
// values as NUMERIC, so 10 and 10.0 are the same report. not_after is a day
// past the report's own instant: it keeps the scan off empty future
// partitions while tolerating a clock that stepped back.
func (q *Queries) FindUsageReportByTransactionID(ctx context.Context, arg FindUsageReportByTransactionIDParams) (FindUsageReportByTransactionIDRow, error) {
	row := q.db.QueryRow(ctx, findUsageReportByTransactionID,
		arg.Value,
		arg.OrganizationID,
		arg.InstanceID,
		arg.EntitlementID,
		arg.TransactionID,
		arg.NotBefore,
		arg.NotAfter,
	)
	var i FindUsageReportByTransactionIDRow
	err := row.Scan(
		&i.ReportSeq,
		&i.ReportedAt,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Behavior,
		&i.ReportedValue,
		&i.SameValue,
		&i.ValueAfter,
		&i.EventCountAfter,
		&i.LimitValue,
		&i.LicenseID,
		&i.LicenseSlug,
	)
	return i, err
}

const getPairReportSeq = `-- name: GetPairReportSeq :one
SELECT coalesce((SELECT eu.report_seq FROM entitlement_usage eu
                  WHERE eu.instance_id = $1
                    AND eu.entitlement_id = $2), 0)::bigint AS report_seq
`

type GetPairReportSeqParams struct {
	InstanceID    uuid.UUID `json:"instance_id"`
	EntitlementID uuid.UUID `json:"entitlement_id"`
}

// The pair's report counter, 0 before its first report. Read by Seal under
// the pair's lock.
func (q *Queries) GetPairReportSeq(ctx context.Context, arg GetPairReportSeqParams) (int64, error) {
	row := q.db.QueryRow(ctx, getPairReportSeq, arg.InstanceID, arg.EntitlementID)
	var report_seq int64
	err := row.Scan(&report_seq)
	return report_seq, err
}

const hasProtectedUsageLedgerRows = `-- name: HasProtectedUsageLedgerRows :one
SELECT EXISTS (
  SELECT 1
  FROM usage_ledger old
  WHERE old.reported_at >= $1
    AND old.reported_at < $2
  AND (EXISTS (
    SELECT 1
    FROM instance_billing ib
    WHERE ib.instance_id = old.instance_id
      AND ib.status <> 'CANCELED'
      AND (
        -- (a) not invoiced yet: since the current period started.
        old.reported_at >= ib.current_period_start
        -- the last row of the pair before it, so that the "first_seq - 1"
        -- probe of invariant 1 stays answerable.
        OR (old.reported_at < ib.current_period_start
            AND NOT EXISTS (
              SELECT 1 FROM usage_ledger nxt
              WHERE nxt.instance_id = old.instance_id
                AND nxt.entitlement_id = old.entitlement_id
                AND nxt.reported_at > old.reported_at
                AND nxt.reported_at < ib.current_period_start))
      )
  )
  OR EXISTS (
    -- (b) in the service period of a DRAFT invoice: held, awaiting release,
    -- recompose or handoff.
    SELECT 1
    FROM instance_billing ib
    JOIN instance_invoice inv ON inv.instance_billing_id = ib.id
    WHERE ib.instance_id = old.instance_id
      AND inv.status = 'DRAFT'
      AND old.reported_at >= inv.service_from
      AND old.reported_at < inv.service_to
  ))
)::bool AS protected
`

type HasProtectedUsageLedgerRowsParams struct {
	RangeStart pgtype.Timestamp `json:"range_start"`
	RangeEnd   pgtype.Timestamp `json:"range_end"`
}

// Whether any row dated in [range_start, range_end) is protected (D-33): a
// partition holding one is not dropped.
func (q *Queries) HasProtectedUsageLedgerRows(ctx context.Context, arg HasProtectedUsageLedgerRowsParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasProtectedUsageLedgerRows, arg.RangeStart, arg.RangeEnd)
	var protected bool
	err := row.Scan(&protected)
	return protected, err
}

const listOrganizationUsageReports = `-- name: ListOrganizationUsageReports :many
SELECT ul.organization_id, ul.instance_id, ul.entitlement_id, ul.license_id,
       ul.report_seq, ul.reported_at, ul.window_start, ul.window_end,
       ul.behavior::text AS behavior, ul.aggregation_method::text AS aggregation_method,
       ul.reported_value::text AS reported_value,
       ul.value_before::text AS value_before,
       ul.value_after::text AS value_after,
       trim_scale(ul.value_after - ul.value_before)::text AS delta,
       (CASE WHEN ul.limit_value IS NULL THEN 0
             ELSE trim_scale(GREATEST(0, ul.value_after - ul.limit_value) - GREATEST(0, ul.value_before - ul.limit_value))
        END)::text AS overage_delta,
       ul.event_count_after, coalesce(ul.limit_value::text, '')::text AS limit_value, ul.overage_percent,
       ul.transaction_id, ul.properties
FROM usage_ledger ul
WHERE ul.organization_id = $1
  AND ul.reported_at >= $2
  AND ul.reported_at < $3
  AND ($4::uuid IS NULL OR ul.instance_id = $4::uuid)
  AND ($5::uuid IS NULL OR ul.entitlement_id = $5::uuid)
  AND (ul.reported_at, ul.instance_id, ul.entitlement_id, ul.report_seq)
      > ($6::timestamp, $7::uuid,
         $8::uuid, $9::bigint)
ORDER BY ul.reported_at, ul.instance_id, ul.entitlement_id, ul.report_seq
LIMIT $10
`

type ListOrganizationUsageReportsParams struct {
	OrganizationID     uuid.UUID        `json:"organization_id"`
	FromAt             pgtype.Timestamp `json:"from_at"`
	ToAt               pgtype.Timestamp `json:"to_at"`
	InstanceID         *uuid.UUID       `json:"instance_id"`
	EntitlementID      *uuid.UUID       `json:"entitlement_id"`
	AfterReportedAt    pgtype.Timestamp `json:"after_reported_at"`
	AfterInstanceID    uuid.UUID        `json:"after_instance_id"`
	AfterEntitlementID uuid.UUID        `json:"after_entitlement_id"`
	AfterSeq           int64            `json:"after_seq"`
	PageSize           int32            `json:"page_size"`
}

type ListOrganizationUsageReportsRow struct {
	OrganizationID    uuid.UUID        `json:"organization_id"`
	InstanceID        uuid.UUID        `json:"instance_id"`
	EntitlementID     uuid.UUID        `json:"entitlement_id"`
	LicenseID         uuid.UUID        `json:"license_id"`
	ReportSeq         int64            `json:"report_seq"`
	ReportedAt        pgtype.Timestamp `json:"reported_at"`
	WindowStart       pgtype.Timestamp `json:"window_start"`
	WindowEnd         pgtype.Timestamp `json:"window_end"`
	Behavior          string           `json:"behavior"`
	AggregationMethod string           `json:"aggregation_method"`
	ReportedValue     string           `json:"reported_value"`
	ValueBefore       string           `json:"value_before"`
	ValueAfter        string           `json:"value_after"`
	Delta             string           `json:"delta"`
	OverageDelta      string           `json:"overage_delta"`
	EventCountAfter   int32            `json:"event_count_after"`
	LimitValue        string           `json:"limit_value"`
	OveragePercent    int16            `json:"overage_percent"`
	TransactionID     *string          `json:"transaction_id"`
	Properties        []byte           `json:"properties"`
}

// One page of an organization's journal, every pair or a filtered few, in
// (reported_at, instance_id, entitlement_id, report_seq) order through
// idx_usage_ledger_org_reported_at. The ID filters reach a deleted instance or
// entitlement, whose rows survive it. Same columns as ListPairUsageReports.
func (q *Queries) ListOrganizationUsageReports(ctx context.Context, arg ListOrganizationUsageReportsParams) ([]ListOrganizationUsageReportsRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationUsageReports,
		arg.OrganizationID,
		arg.FromAt,
		arg.ToAt,
		arg.InstanceID,
		arg.EntitlementID,
		arg.AfterReportedAt,
		arg.AfterInstanceID,
		arg.AfterEntitlementID,
		arg.AfterSeq,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationUsageReportsRow
	for rows.Next() {
		var i ListOrganizationUsageReportsRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.InstanceID,
			&i.EntitlementID,
			&i.LicenseID,
			&i.ReportSeq,
			&i.ReportedAt,
			&i.WindowStart,
			&i.WindowEnd,
			&i.Behavior,
			&i.AggregationMethod,
			&i.ReportedValue,
			&i.ValueBefore,
			&i.ValueAfter,
			&i.Delta,
			&i.OverageDelta,
			&i.EventCountAfter,
			&i.LimitValue,
			&i.OveragePercent,
			&i.TransactionID,
			&i.Properties,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPairUsageReports = `-- name: ListPairUsageReports :many
SELECT ul.organization_id, ul.instance_id, ul.entitlement_id, ul.license_id,
       ul.report_seq, ul.reported_at, ul.window_start, ul.window_end,
       ul.behavior::text AS behavior, ul.aggregation_method::text AS aggregation_method,
       ul.reported_value::text AS reported_value,
       ul.value_before::text AS value_before,
       ul.value_after::text AS value_after,
       trim_scale(ul.value_after - ul.value_before)::text AS delta,
       (CASE WHEN ul.limit_value IS NULL THEN 0
             ELSE trim_scale(GREATEST(0, ul.value_after - ul.limit_value) - GREATEST(0, ul.value_before - ul.limit_value))
        END)::text AS overage_delta,
       ul.event_count_after, coalesce(ul.limit_value::text, '')::text AS limit_value, ul.overage_percent,
       ul.transaction_id, ul.properties
FROM usage_ledger ul
WHERE ul.organization_id = $1
  AND ul.instance_id = $2
  AND ul.entitlement_id = $3
  AND ul.reported_at >= $4
  AND ul.reported_at < $5
  AND ul.report_seq > $6
  AND ($7::text IS NULL OR ul.transaction_id = $7::text)
ORDER BY ul.report_seq
LIMIT $8
`

type ListPairUsageReportsParams struct {
	OrganizationID uuid.UUID        `json:"organization_id"`
	InstanceID     uuid.UUID        `json:"instance_id"`
	EntitlementID  uuid.UUID        `json:"entitlement_id"`
	FromAt         pgtype.Timestamp `json:"from_at"`
	ToAt           pgtype.Timestamp `json:"to_at"`
	AfterSeq       int64            `json:"after_seq"`
	TransactionID  *string          `json:"transaction_id"`
	PageSize       int32            `json:"page_size"`
}

type ListPairUsageReportsRow struct {
	OrganizationID    uuid.UUID        `json:"organization_id"`
	InstanceID        uuid.UUID        `json:"instance_id"`
	EntitlementID     uuid.UUID        `json:"entitlement_id"`
	LicenseID         uuid.UUID        `json:"license_id"`
	ReportSeq         int64            `json:"report_seq"`
	ReportedAt        pgtype.Timestamp `json:"reported_at"`
	WindowStart       pgtype.Timestamp `json:"window_start"`
	WindowEnd         pgtype.Timestamp `json:"window_end"`
	Behavior          string           `json:"behavior"`
	AggregationMethod string           `json:"aggregation_method"`
	ReportedValue     string           `json:"reported_value"`
	ValueBefore       string           `json:"value_before"`
	ValueAfter        string           `json:"value_after"`
	Delta             string           `json:"delta"`
	OverageDelta      string           `json:"overage_delta"`
	EventCountAfter   int32            `json:"event_count_after"`
	LimitValue        string           `json:"limit_value"`
	OveragePercent    int16            `json:"overage_percent"`
	TransactionID     *string          `json:"transaction_id"`
	Properties        []byte           `json:"properties"`
}

// One page of a pair's journal, in report_seq order, through the primary key.
// Decimals come out as their exact text, limit_value as ” when unlimited (a
// cast hides its nullability from sqlc); delta and overage_delta are computed
// here, in NUMERIC, so they are as exact as the columns. trim_scale drops the
// trailing zeros a subtraction of two scales leaves (2.5 - 0.5 is 2, not 2.0).
func (q *Queries) ListPairUsageReports(ctx context.Context, arg ListPairUsageReportsParams) ([]ListPairUsageReportsRow, error) {
	rows, err := q.db.Query(ctx, listPairUsageReports,
		arg.OrganizationID,
		arg.InstanceID,
		arg.EntitlementID,
		arg.FromAt,
		arg.ToAt,
		arg.AfterSeq,
		arg.TransactionID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPairUsageReportsRow
	for rows.Next() {
		var i ListPairUsageReportsRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.InstanceID,
			&i.EntitlementID,
			&i.LicenseID,
			&i.ReportSeq,
			&i.ReportedAt,
			&i.WindowStart,
			&i.WindowEnd,
			&i.Behavior,
			&i.AggregationMethod,
			&i.ReportedValue,
			&i.ValueBefore,
			&i.ValueAfter,
			&i.Delta,
			&i.OverageDelta,
			&i.EventCountAfter,
			&i.LimitValue,
			&i.OveragePercent,
			&i.TransactionID,
			&i.Properties,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageLedgerOrganizations = `-- name: ListUsageLedgerOrganizations :many
WITH RECURSIVE orgs AS (
  (SELECT ul.organization_id FROM usage_ledger ul ORDER BY ul.organization_id LIMIT 1)
  UNION ALL
  SELECT (SELECT ul.organization_id FROM usage_ledger ul
           WHERE ul.organization_id > orgs.organization_id
           ORDER BY ul.organization_id LIMIT 1)
  FROM orgs
  WHERE orgs.organization_id IS NOT NULL
)
SELECT orgs.organization_id::uuid AS organization_id FROM orgs WHERE orgs.organization_id IS NOT NULL
`

// Every organization with at least one journal row, without reading the rows:
// a loose index scan that jumps from one organization_id to the next on
// idx_usage_ledger_org_reported_at, one probe per organization.
func (q *Queries) ListUsageLedgerOrganizations(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUsageLedgerOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var organization_id uuid.UUID
		if err := rows.Scan(&organization_id); err != nil {
			return nil, err
		}
		items = append(items, organization_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageLedgerPartitions = `-- name: ListUsageLedgerPartitions :many
SELECT c.relname::text AS name
FROM pg_catalog.pg_inherits i
JOIN pg_catalog.pg_class c ON c.oid = i.inhrelid
WHERE i.inhparent = 'usage_ledger'::regclass
ORDER BY c.relname
`

// The partitions attached to usage_ledger, by name. A table named like one but
// detached is not listed: it holds no rows anybody reads.
func (q *Queries) ListUsageLedgerPartitions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listUsageLedgerPartitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeOrganizationUsageLedger = `-- name: PurgeOrganizationUsageLedger :execrows
DELETE FROM usage_ledger ul
USING (
  SELECT old.instance_id, old.entitlement_id, old.report_seq, old.reported_at
  FROM usage_ledger old
  WHERE old.organization_id = $1
    AND old.reported_at < $2
  AND NOT EXISTS (
    SELECT 1
    FROM instance_billing ib
    WHERE ib.instance_id = old.instance_id
      AND ib.status <> 'CANCELED'
      AND (
        -- (a) not invoiced yet: since the current period started.
        old.reported_at >= ib.current_period_start
        -- the last row of the pair before it, so that the "first_seq - 1"
        -- probe of invariant 1 stays answerable.
        OR (old.reported_at < ib.current_period_start
            AND NOT EXISTS (
              SELECT 1 FROM usage_ledger nxt
              WHERE nxt.instance_id = old.instance_id
                AND nxt.entitlement_id = old.entitlement_id
                AND nxt.reported_at > old.reported_at
                AND nxt.reported_at < ib.current_period_start))
      )
  )
  AND NOT EXISTS (
    -- (b) in the service period of a DRAFT invoice: held, awaiting release,
    -- recompose or handoff.
    SELECT 1
    FROM instance_billing ib
    JOIN instance_invoice inv ON inv.instance_billing_id = ib.id
    WHERE ib.instance_id = old.instance_id
      AND inv.status = 'DRAFT'
      AND old.reported_at >= inv.service_from
      AND old.reported_at < inv.service_to
  )
  LIMIT $3
) doomed
WHERE ul.instance_id = doomed.instance_id
  AND ul.entitlement_id = doomed.entitlement_id
  AND ul.report_seq = doomed.report_seq
  AND ul.reported_at = doomed.reported_at
`

type PurgeOrganizationUsageLedgerParams struct {
	OrganizationID uuid.UUID        `json:"organization_id"`
	Cutoff         pgtype.Timestamp `json:"cutoff"`
	BatchSize      int32            `json:"batch_size"`
}

// One batch of an organization's journal rows older than cutoff, through
// idx_usage_ledger_org_reported_at. The caller repeats it until a batch comes
// back short. Rows that are not invoiced yet are never deleted (D-33): those
// of a live subscription since its current period started, the last row before
// that of each pair, and those in the service period of a DRAFT invoice.
func (q *Queries) PurgeOrganizationUsageLedger(ctx context.Context, arg PurgeOrganizationUsageLedgerParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOrganizationUsageLedger, arg.OrganizationID, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveUsageReportPair = `-- name: ResolveUsageReportPair :one
SELECT
  coalesce((SELECT i.id FROM instance i
             WHERE i.organization_id = $1 AND i.slug = $2),
           '00000000-0000-0000-0000-000000000000')::uuid AS instance_id,
  coalesce((SELECT e.id FROM entitlement e
             WHERE e.organization_id = $1 AND e.slug = $3),
           '00000000-0000-0000-0000-000000000000')::uuid AS entitlement_id
`

type ResolveUsageReportPairParams struct {
	OrganizationID  uuid.UUID `json:"organization_id"`
	InstanceSlug    string    `json:"instance_slug"`
	EntitlementSlug string    `json:"entitlement_slug"`
}

type ResolveUsageReportPairRow struct {
	InstanceID    uuid.UUID `json:"instance_id"`
	EntitlementID uuid.UUID `json:"entitlement_id"`
}

// The instance and entitlement a usage history request names, in one round
// trip: the nil UUID for a slug the organization does not have. Neither has
// to be granted by the instance's current licence -- its history outlives a
// licence change.
func (q *Queries) ResolveUsageReportPair(ctx context.Context, arg ResolveUsageReportPairParams) (ResolveUsageReportPairRow, error) {
	row := q.db.QueryRow(ctx, resolveUsageReportPair, arg.OrganizationID, arg.InstanceSlug, arg.EntitlementSlug)
	var i ResolveUsageReportPairRow
	err := row.Scan(&i.InstanceID, &i.EntitlementID)
	return i, err
}

const summarizeUsageLimits = `-- name: SummarizeUsageLimits :many
SELECT coalesce(trim_scale(ul.limit_value)::text, '')::text AS limit_value,
       ul.overage_percent,
       count(*)::bigint AS row_count
FROM usage_ledger ul
WHERE ul.organization_id = $1
  AND ul.instance_id = $2
  AND ul.entitlement_id = $3
  AND ul.reported_at >= $4
  AND ul.reported_at < $5
GROUP BY ul.limit_value, ul.overage_percent
ORDER BY min(ul.report_seq)
`

type SummarizeUsageLimitsParams struct {
	OrganizationID uuid.UUID        `json:"organization_id"`
	InstanceID     uuid.UUID        `json:"instance_id"`
	EntitlementID  uuid.UUID        `json:"entitlement_id"`
	FromAt         pgtype.Timestamp `json:"from_at"`
	ToAt           pgtype.Timestamp `json:"to_at"`
}

type SummarizeUsageLimitsRow struct {
	LimitValue     string `json:"limit_value"`
	OveragePercent int16  `json:"overage_percent"`
	RowCount       int64  `json:"row_count"`
}

// The distinct (limit, overage percent) pairs the gate applied to a pair's
// rows dated in [from, to), in the order they first applied. limit_value is
// ” when unlimited.
func (q *Queries) SummarizeUsageLimits(ctx context.Context, arg SummarizeUsageLimitsParams) ([]SummarizeUsageLimitsRow, error) {
	rows, err := q.db.Query(ctx, summarizeUsageLimits,
		arg.OrganizationID,
		arg.InstanceID,
		arg.EntitlementID,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummarizeUsageLimitsRow
	for rows.Next() {
		var i SummarizeUsageLimitsRow
		if err := rows.Scan(&i.LimitValue, &i.OveragePercent, &i.RowCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summarizeUsageWindows = `-- name: SummarizeUsageWindows :many
SELECT ul.window_start,
       ul.window_end,
       trim_scale(sum(ul.value_after - ul.value_before))::text AS usage,
       trim_scale(sum(CASE WHEN ul.limit_value IS NULL THEN 0
                           ELSE GREATEST(0, ul.value_after - ul.limit_value)
                              - GREATEST(0, ul.value_before - ul.limit_value)
                      END))::text AS overage,
       count(*)::bigint AS row_count,
       min(ul.report_seq)::bigint AS first_seq,
       max(ul.report_seq)::bigint AS last_seq
FROM usage_ledger ul
WHERE ul.organization_id = $1
  AND ul.instance_id = $2
  AND ul.entitlement_id = $3
  AND ul.reported_at >= $4
  AND ul.reported_at < $5
GROUP BY ul.window_start, ul.window_end
ORDER BY min(ul.report_seq)
`

type SummarizeUsageWindowsParams struct {
	OrganizationID uuid.UUID        `json:"organization_id"`
	InstanceID     uuid.UUID        `json:"instance_id"`
	EntitlementID  uuid.UUID        `json:"entitlement_id"`
	FromAt         pgtype.Timestamp `json:"from_at"`
	ToAt           pgtype.Timestamp `json:"to_at"`
}

type SummarizeUsageWindowsRow struct {
	WindowStart pgtype.Timestamp `json:"window_start"`
	WindowEnd   pgtype.Timestamp `json:"window_end"`
	Usage       string           `json:"usage"`
	Overage     string           `json:"overage"`
	RowCount    int64            `json:"row_count"`
	FirstSeq    int64            `json:"first_seq"`
	LastSeq     int64            `json:"last_seq"`
}

// A pair's rows dated in [from, to), summed by reset window, oldest window
// first. Usage is the counter's own movement; overage is its movement above
// the limit each row was gated against (0 on an unlimited row). Decimals come
// out as exact text.
func (q *Queries) SummarizeUsageWindows(ctx context.Context, arg SummarizeUsageWindowsParams) ([]SummarizeUsageWindowsRow, error) {
	rows, err := q.db.Query(ctx, summarizeUsageWindows,
		arg.OrganizationID,
		arg.InstanceID,
		arg.EntitlementID,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummarizeUsageWindowsRow
	for rows.Next() {
		var i SummarizeUsageWindowsRow
		if err := rows.Scan(
			&i.WindowStart,
			&i.WindowEnd,
			&i.Usage,
			&i.Overage,
			&i.RowCount,
			&i.FirstSeq,
			&i.LastSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
