// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing_settings.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getBillingSettings = `-- name: GetBillingSettings :one
SELECT s.default_collection_method, s.default_days_until_due, s.handoff_stripe_invoices
FROM organization_billing_settings s
WHERE s.organization_id = $1
`

type GetBillingSettingsRow struct {
	DefaultCollectionMethod CollectionMethod `json:"default_collection_method"`
	DefaultDaysUntilDue     int32            `json:"default_days_until_due"`
	HandoffStripeInvoices   bool             `json:"handoff_stripe_invoices"`
}

// The organization's billing defaults. No row means every default.
func (q *Queries) GetBillingSettings(ctx context.Context, organizationID uuid.UUID) (GetBillingSettingsRow, error) {
	row := q.db.QueryRow(ctx, getBillingSettings, organizationID)
	var i GetBillingSettingsRow
	err := row.Scan(&i.DefaultCollectionMethod, &i.DefaultDaysUntilDue, &i.HandoffStripeInvoices)
	return i, err
}

const upsertBillingSettings = `-- name: UpsertBillingSettings :one
INSERT INTO organization_billing_settings (organization_id, default_collection_method, default_days_until_due,
                                           handoff_stripe_invoices, created_by_id, updated_by_id)
VALUES ($1, $2, $3,
        $4, $5, $5)
ON CONFLICT (organization_id) DO UPDATE
  SET default_collection_method = EXCLUDED.default_collection_method,
      default_days_until_due    = EXCLUDED.default_days_until_due,
      handoff_stripe_invoices   = EXCLUDED.handoff_stripe_invoices,
      updated_by_id             = EXCLUDED.updated_by_id,
      updated_at                = now()
RETURNING default_collection_method, default_days_until_due, handoff_stripe_invoices
`

type UpsertBillingSettingsParams struct {
	OrganizationID          uuid.UUID        `json:"organization_id"`
	DefaultCollectionMethod CollectionMethod `json:"default_collection_method"`
	DefaultDaysUntilDue     int32            `json:"default_days_until_due"`
	HandoffStripeInvoices   bool             `json:"handoff_stripe_invoices"`
	UserID                  uuid.UUID        `json:"user_id"`
}

type UpsertBillingSettingsRow struct {
	DefaultCollectionMethod CollectionMethod `json:"default_collection_method"`
	DefaultDaysUntilDue     int32            `json:"default_days_until_due"`
	HandoffStripeInvoices   bool             `json:"handoff_stripe_invoices"`
}

func (q *Queries) UpsertBillingSettings(ctx context.Context, arg UpsertBillingSettingsParams) (UpsertBillingSettingsRow, error) {
	row := q.db.QueryRow(ctx, upsertBillingSettings,
		arg.OrganizationID,
		arg.DefaultCollectionMethod,
		arg.DefaultDaysUntilDue,
		arg.HandoffStripeInvoices,
		arg.UserID,
	)
	var i UpsertBillingSettingsRow
	err := row.Scan(&i.DefaultCollectionMethod, &i.DefaultDaysUntilDue, &i.HandoffStripeInvoices)
	return i, err
}
