// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: close.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceSubscriptionPeriod = `-- name: AdvanceSubscriptionPeriod :exec
UPDATE instance_billing
SET current_period_start = $1,
    current_period_end   = $2,
    updated_by_id        = $3,
    updated_at           = $4
WHERE id = $5
`

type AdvanceSubscriptionPeriodParams struct {
	PeriodStart pgtype.Timestamp `json:"period_start"`
	PeriodEnd   pgtype.Timestamp `json:"period_end"`
	UserID      uuid.UUID        `json:"user_id"`
	Now         pgtype.Timestamp `json:"now"`
	ID          uuid.UUID        `json:"id"`
}

func (q *Queries) AdvanceSubscriptionPeriod(ctx context.Context, arg AdvanceSubscriptionPeriodParams) error {
	_, err := q.db.Exec(ctx, advanceSubscriptionPeriod,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.UserID,
		arg.Now,
		arg.ID,
	)
	return err
}

const getPreviousInvoiceLines = `-- name: GetPreviousInvoiceLines :one
SELECT i.lines
FROM instance_invoice i
WHERE i.instance_billing_id = $1
  AND i.status <> 'VOID'
  AND i.boundary_at < $2
ORDER BY i.boundary_at DESC, i.created_at DESC
LIMIT 1
`

type GetPreviousInvoiceLinesParams struct {
	InstanceBillingID uuid.UUID        `json:"instance_billing_id"`
	BoundaryAt        pgtype.Timestamp `json:"boundary_at"`
}

// The lines of a subscription's latest live invoice before a boundary: the
// previous close, whose usage fingerprints the next period starts after.
func (q *Queries) GetPreviousInvoiceLines(ctx context.Context, arg GetPreviousInvoiceLinesParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPreviousInvoiceLines, arg.InstanceBillingID, arg.BoundaryAt)
	var lines []byte
	err := row.Scan(&lines)
	return lines, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, organization_id, instance_id, customer_id, instance_slug, instance_name, customer_slug, customer_name, status, provider_kind, collection_method, days_until_due, base_license_price_id, billing_period, currency, anchor_at, started_at, current_period_start, current_period_end, cancel_at_period_end, cancel_requested_at, canceled_at, cancellation_reason, past_due_since, scheduled_license_price_id, scheduled_at, created_at, created_by_id, updated_at, updated_by_id, trial_ends_at
FROM instance_billing ib
WHERE ib.id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id uuid.UUID) (InstanceBilling, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i InstanceBilling
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InstanceID,
		&i.CustomerID,
		&i.InstanceSlug,
		&i.InstanceName,
		&i.CustomerSlug,
		&i.CustomerName,
		&i.Status,
		&i.ProviderKind,
		&i.CollectionMethod,
		&i.DaysUntilDue,
		&i.BaseLicensePriceID,
		&i.BillingPeriod,
		&i.Currency,
		&i.AnchorAt,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CancelRequestedAt,
		&i.CanceledAt,
		&i.CancellationReason,
		&i.PastDueSince,
		&i.ScheduledLicensePriceID,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.UpdatedAt,
		&i.UpdatedByID,
		&i.TrialEndsAt,
	)
	return i, err
}

const getSystemActor = `-- name: GetSystemActor :one
SELECT u.id
FROM "user" u
JOIN user_on_organization m
  ON m.user_id = u.id
 AND m.organization_id = $1
 AND m.deleted_at IS NULL
WHERE u.external_id = $2
`

type GetSystemActorParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ExternalID     string    `json:"external_id"`
}

// system:kaiten's membership in an organization: the user work Kaiten does on
// its own behalf is recorded under. No row when it has none.
func (q *Queries) GetSystemActor(ctx context.Context, arg GetSystemActorParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSystemActor, arg.OrganizationID, arg.ExternalID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listDueSubscriptions = `-- name: ListDueSubscriptions :many
SELECT ib.id, ib.organization_id
FROM instance_billing ib
WHERE ib.status IN ('TRIAL', 'ACTIVE', 'PAST_DUE')
  AND ib.current_period_end <= $1
  AND ($2::uuid IS NULL OR ib.organization_id = $2::uuid)
  AND ($3::uuid IS NULL OR ib.instance_id = $3::uuid)
  AND NOT (ib.id = ANY ($4::uuid[]))
ORDER BY ib.current_period_end, ib.id
LIMIT $5
`

type ListDueSubscriptionsParams struct {
	DueBefore      pgtype.Timestamp `json:"due_before"`
	OrganizationID *uuid.UUID       `json:"organization_id"`
	InstanceID     *uuid.UUID       `json:"instance_id"`
	Excluded       []uuid.UUID      `json:"excluded"`
	PageSize       int32            `json:"page_size"`
}

type ListDueSubscriptionsRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

// The live subscriptions whose period ended at or before due_before, oldest
// boundary first, optionally one organization or one instance's, skipping
// those a pass already gave up on.
func (q *Queries) ListDueSubscriptions(ctx context.Context, arg ListDueSubscriptionsParams) ([]ListDueSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listDueSubscriptions,
		arg.DueBefore,
		arg.OrganizationID,
		arg.InstanceID,
		arg.Excluded,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueSubscriptionsRow
	for rows.Next() {
		var i ListDueSubscriptionsRow
		if err := rows.Scan(&i.ID, &i.OrganizationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDueSubscription = `-- name: LockDueSubscription :one
SELECT id, organization_id, instance_id, customer_id, instance_slug, instance_name, customer_slug, customer_name, status, provider_kind, collection_method, days_until_due, base_license_price_id, billing_period, currency, anchor_at, started_at, current_period_start, current_period_end, cancel_at_period_end, cancel_requested_at, canceled_at, cancellation_reason, past_due_since, scheduled_license_price_id, scheduled_at, created_at, created_by_id, updated_at, updated_by_id, trial_ends_at
FROM instance_billing ib
WHERE ib.id = $1
FOR UPDATE SKIP LOCKED
`

// The subscription a close works on, locked; no row when another close or a
// use case holds it, which the close takes as "not now" rather than waiting.
func (q *Queries) LockDueSubscription(ctx context.Context, id uuid.UUID) (InstanceBilling, error) {
	row := q.db.QueryRow(ctx, lockDueSubscription, id)
	var i InstanceBilling
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InstanceID,
		&i.CustomerID,
		&i.InstanceSlug,
		&i.InstanceName,
		&i.CustomerSlug,
		&i.CustomerName,
		&i.Status,
		&i.ProviderKind,
		&i.CollectionMethod,
		&i.DaysUntilDue,
		&i.BaseLicensePriceID,
		&i.BillingPeriod,
		&i.Currency,
		&i.AnchorAt,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CancelRequestedAt,
		&i.CanceledAt,
		&i.CancellationReason,
		&i.PastDueSince,
		&i.ScheduledLicensePriceID,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.UpdatedAt,
		&i.UpdatedByID,
		&i.TrialEndsAt,
	)
	return i, err
}
