// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
)

type CollectionMethod string

const (
	CollectionMethodSENDINVOICE         CollectionMethod = "SEND_INVOICE"
	CollectionMethodCHARGEAUTOMATICALLY CollectionMethod = "CHARGE_AUTOMATICALLY"
)

func (e *CollectionMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CollectionMethod(s)
	case string:
		*e = CollectionMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for CollectionMethod: %T", src)
	}
	return nil
}

type NullCollectionMethod struct {
	CollectionMethod CollectionMethod `json:"collection_method"`
	Valid            bool             `json:"valid"` // Valid is true if CollectionMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCollectionMethod) Scan(value interface{}) error {
	if value == nil {
		ns.CollectionMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CollectionMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCollectionMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CollectionMethod), nil
}
