// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const billingClock = `-- name: BillingClock :one
SELECT date_trunc('milliseconds', clock_timestamp() AT TIME ZONE 'UTC')::timestamp(3) AS now
`

// The instant billing acts at: the database's clock, in UTC, to the
// millisecond -- the clock the usage report dates its reports with.
func (q *Queries) BillingClock(ctx context.Context) (pgtype.Timestamp, error) {
	row := q.db.QueryRow(ctx, billingClock)
	var now pgtype.Timestamp
	err := row.Scan(&now)
	return now, err
}

const getBillingCustomer = `-- name: GetBillingCustomer :one
SELECT c.id, c.slug, c.name, c.billing_email
FROM customer c
WHERE c.organization_id = $1
  AND c.id = $2
`

type GetBillingCustomerParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

type GetBillingCustomerRow struct {
	ID           uuid.UUID `json:"id"`
	Slug         string    `json:"slug"`
	Name         string    `json:"name"`
	BillingEmail *string   `json:"billing_email"`
}

// The customer a subscription bills. billing_email is personal data: it is
// snapshotted on the invoice, never written to an event.
func (q *Queries) GetBillingCustomer(ctx context.Context, arg GetBillingCustomerParams) (GetBillingCustomerRow, error) {
	row := q.db.QueryRow(ctx, getBillingCustomer, arg.OrganizationID, arg.ID)
	var i GetBillingCustomerRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.BillingEmail,
	)
	return i, err
}

const getBillingLicense = `-- name: GetBillingLicense :one
SELECT l.id, l.slug, l.name, l.lifecycle_state
FROM license l
WHERE l.organization_id = $1
  AND l.id = $2
`

type GetBillingLicenseParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

type GetBillingLicenseRow struct {
	ID             uuid.UUID             `json:"id"`
	Slug           string                `json:"slug"`
	Name           string                `json:"name"`
	LifecycleState LicenseLifecycleState `json:"lifecycle_state"`
}

func (q *Queries) GetBillingLicense(ctx context.Context, arg GetBillingLicenseParams) (GetBillingLicenseRow, error) {
	row := q.db.QueryRow(ctx, getBillingLicense, arg.OrganizationID, arg.ID)
	var i GetBillingLicenseRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.LifecycleState,
	)
	return i, err
}

const getInstanceBilling = `-- name: GetInstanceBilling :one
SELECT id, organization_id, instance_id, customer_id, instance_slug, instance_name, customer_slug, customer_name, status, provider_kind, collection_method, days_until_due, base_license_price_id, billing_period, currency, anchor_at, started_at, current_period_start, current_period_end, cancel_at_period_end, cancel_requested_at, canceled_at, cancellation_reason, past_due_since, scheduled_license_price_id, scheduled_at, created_at, created_by_id, updated_at, updated_by_id
FROM instance_billing ib
WHERE ib.organization_id = $1
  AND ib.instance_id = $2
`

type GetInstanceBillingParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	InstanceID     *uuid.UUID `json:"instance_id"`
}

// An instance's subscription row, the one it keeps for life.
func (q *Queries) GetInstanceBilling(ctx context.Context, arg GetInstanceBillingParams) (InstanceBilling, error) {
	row := q.db.QueryRow(ctx, getInstanceBilling, arg.OrganizationID, arg.InstanceID)
	var i InstanceBilling
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InstanceID,
		&i.CustomerID,
		&i.InstanceSlug,
		&i.InstanceName,
		&i.CustomerSlug,
		&i.CustomerName,
		&i.Status,
		&i.ProviderKind,
		&i.CollectionMethod,
		&i.DaysUntilDue,
		&i.BaseLicensePriceID,
		&i.BillingPeriod,
		&i.Currency,
		&i.AnchorAt,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CancelRequestedAt,
		&i.CanceledAt,
		&i.CancellationReason,
		&i.PastDueSince,
		&i.ScheduledLicensePriceID,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.UpdatedAt,
		&i.UpdatedByID,
	)
	return i, err
}

const getInstanceBySlug = `-- name: GetInstanceBySlug :one
SELECT i.id, i.slug, i.name, i.customer_id, i.license_id
FROM instance i
WHERE i.organization_id = $1
  AND i.slug = $2
`

type GetInstanceBySlugParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Slug           string    `json:"slug"`
}

type GetInstanceBySlugRow struct {
	ID         uuid.UUID `json:"id"`
	Slug       string    `json:"slug"`
	Name       string    `json:"name"`
	CustomerID uuid.UUID `json:"customer_id"`
	LicenseID  uuid.UUID `json:"license_id"`
}

func (q *Queries) GetInstanceBySlug(ctx context.Context, arg GetInstanceBySlugParams) (GetInstanceBySlugRow, error) {
	row := q.db.QueryRow(ctx, getInstanceBySlug, arg.OrganizationID, arg.Slug)
	var i GetInstanceBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CustomerID,
		&i.LicenseID,
	)
	return i, err
}

const insertInstanceBilling = `-- name: InsertInstanceBilling :one
INSERT INTO instance_billing (organization_id, instance_id, customer_id, instance_slug, instance_name,
                              customer_slug, customer_name, status, provider_kind, collection_method,
                              days_until_due, base_license_price_id, billing_period, currency, anchor_at,
                              started_at, current_period_start, current_period_end, created_by_id,
                              updated_by_id)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8,
        $9, $10, $11,
        $12, $13, $14, $15,
        $15, $15, $16, $17,
        $17)
RETURNING id, organization_id, instance_id, customer_id, instance_slug, instance_name, customer_slug, customer_name, status, provider_kind, collection_method, days_until_due, base_license_price_id, billing_period, currency, anchor_at, started_at, current_period_start, current_period_end, cancel_at_period_end, cancel_requested_at, canceled_at, cancellation_reason, past_due_since, scheduled_license_price_id, scheduled_at, created_at, created_by_id, updated_at, updated_by_id
`

type InsertInstanceBillingParams struct {
	OrganizationID     uuid.UUID             `json:"organization_id"`
	InstanceID         *uuid.UUID            `json:"instance_id"`
	CustomerID         *uuid.UUID            `json:"customer_id"`
	InstanceSlug       string                `json:"instance_slug"`
	InstanceName       string                `json:"instance_name"`
	CustomerSlug       string                `json:"customer_slug"`
	CustomerName       string                `json:"customer_name"`
	Status             InstanceBillingStatus `json:"status"`
	ProviderKind       BillingProviderKind   `json:"provider_kind"`
	CollectionMethod   *CollectionMethod     `json:"collection_method"`
	DaysUntilDue       *int32                `json:"days_until_due"`
	BaseLicensePriceID uuid.UUID             `json:"base_license_price_id"`
	BillingPeriod      BillingPeriod         `json:"billing_period"`
	Currency           string                `json:"currency"`
	AnchorAt           pgtype.Timestamp      `json:"anchor_at"`
	CurrentPeriodEnd   pgtype.Timestamp      `json:"current_period_end"`
	UserID             uuid.UUID             `json:"user_id"`
}

func (q *Queries) InsertInstanceBilling(ctx context.Context, arg InsertInstanceBillingParams) (InstanceBilling, error) {
	row := q.db.QueryRow(ctx, insertInstanceBilling,
		arg.OrganizationID,
		arg.InstanceID,
		arg.CustomerID,
		arg.InstanceSlug,
		arg.InstanceName,
		arg.CustomerSlug,
		arg.CustomerName,
		arg.Status,
		arg.ProviderKind,
		arg.CollectionMethod,
		arg.DaysUntilDue,
		arg.BaseLicensePriceID,
		arg.BillingPeriod,
		arg.Currency,
		arg.AnchorAt,
		arg.CurrentPeriodEnd,
		arg.UserID,
	)
	var i InstanceBilling
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InstanceID,
		&i.CustomerID,
		&i.InstanceSlug,
		&i.InstanceName,
		&i.CustomerSlug,
		&i.CustomerName,
		&i.Status,
		&i.ProviderKind,
		&i.CollectionMethod,
		&i.DaysUntilDue,
		&i.BaseLicensePriceID,
		&i.BillingPeriod,
		&i.Currency,
		&i.AnchorAt,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CancelRequestedAt,
		&i.CanceledAt,
		&i.CancellationReason,
		&i.PastDueSince,
		&i.ScheduledLicensePriceID,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.UpdatedAt,
		&i.UpdatedByID,
	)
	return i, err
}

const lockInstanceBilling = `-- name: LockInstanceBilling :one
SELECT id, organization_id, instance_id, customer_id, instance_slug, instance_name, customer_slug, customer_name, status, provider_kind, collection_method, days_until_due, base_license_price_id, billing_period, currency, anchor_at, started_at, current_period_start, current_period_end, cancel_at_period_end, cancel_requested_at, canceled_at, cancellation_reason, past_due_since, scheduled_license_price_id, scheduled_at, created_at, created_by_id, updated_at, updated_by_id
FROM instance_billing ib
WHERE ib.organization_id = $1
  AND ib.instance_id = $2
FOR UPDATE
`

type LockInstanceBillingParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	InstanceID     *uuid.UUID `json:"instance_id"`
}

func (q *Queries) LockInstanceBilling(ctx context.Context, arg LockInstanceBillingParams) (InstanceBilling, error) {
	row := q.db.QueryRow(ctx, lockInstanceBilling, arg.OrganizationID, arg.InstanceID)
	var i InstanceBilling
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InstanceID,
		&i.CustomerID,
		&i.InstanceSlug,
		&i.InstanceName,
		&i.CustomerSlug,
		&i.CustomerName,
		&i.Status,
		&i.ProviderKind,
		&i.CollectionMethod,
		&i.DaysUntilDue,
		&i.BaseLicensePriceID,
		&i.BillingPeriod,
		&i.Currency,
		&i.AnchorAt,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CancelRequestedAt,
		&i.CanceledAt,
		&i.CancellationReason,
		&i.PastDueSince,
		&i.ScheduledLicensePriceID,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.UpdatedAt,
		&i.UpdatedByID,
	)
	return i, err
}

const lockInstanceForSubscribe = `-- name: LockInstanceForSubscribe :one
SELECT i.id, i.slug, i.name, i.customer_id, i.license_id
FROM instance i
WHERE i.organization_id = $1
  AND i.slug = $2
FOR UPDATE
`

type LockInstanceForSubscribeParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Slug           string    `json:"slug"`
}

type LockInstanceForSubscribeRow struct {
	ID         uuid.UUID `json:"id"`
	Slug       string    `json:"slug"`
	Name       string    `json:"name"`
	CustomerID uuid.UUID `json:"customer_id"`
	LicenseID  uuid.UUID `json:"license_id"`
}

// The instance a subscribe names, locked for the transaction: its customer
// and licence are what the subscription is for.
func (q *Queries) LockInstanceForSubscribe(ctx context.Context, arg LockInstanceForSubscribeParams) (LockInstanceForSubscribeRow, error) {
	row := q.db.QueryRow(ctx, lockInstanceForSubscribe, arg.OrganizationID, arg.Slug)
	var i LockInstanceForSubscribeRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CustomerID,
		&i.LicenseID,
	)
	return i, err
}

const resubscribeInstanceBilling = `-- name: ResubscribeInstanceBilling :one
UPDATE instance_billing
SET customer_id           = $1,
    instance_slug         = $2,
    instance_name         = $3,
    customer_slug         = $4,
    customer_name         = $5,
    status                = $6,
    provider_kind         = $7,
    collection_method     = $8,
    days_until_due        = $9,
    base_license_price_id = $10,
    billing_period        = $11,
    currency              = $12,
    anchor_at             = $13,
    started_at            = $13,
    current_period_start  = $13,
    current_period_end    = $14,
    cancel_at_period_end  = FALSE,
    cancel_requested_at   = NULL,
    canceled_at           = NULL,
    cancellation_reason   = NULL,
    past_due_since        = NULL,
    scheduled_license_price_id = NULL,
    scheduled_at          = NULL,
    updated_by_id         = $15,
    updated_at            = $16
WHERE id = $17
  AND organization_id = $18
  AND status = 'CANCELED'
RETURNING id, organization_id, instance_id, customer_id, instance_slug, instance_name, customer_slug, customer_name, status, provider_kind, collection_method, days_until_due, base_license_price_id, billing_period, currency, anchor_at, started_at, current_period_start, current_period_end, cancel_at_period_end, cancel_requested_at, canceled_at, cancellation_reason, past_due_since, scheduled_license_price_id, scheduled_at, created_at, created_by_id, updated_at, updated_by_id
`

type ResubscribeInstanceBillingParams struct {
	CustomerID         *uuid.UUID            `json:"customer_id"`
	InstanceSlug       string                `json:"instance_slug"`
	InstanceName       string                `json:"instance_name"`
	CustomerSlug       string                `json:"customer_slug"`
	CustomerName       string                `json:"customer_name"`
	Status             InstanceBillingStatus `json:"status"`
	ProviderKind       BillingProviderKind   `json:"provider_kind"`
	CollectionMethod   *CollectionMethod     `json:"collection_method"`
	DaysUntilDue       *int32                `json:"days_until_due"`
	BaseLicensePriceID uuid.UUID             `json:"base_license_price_id"`
	BillingPeriod      BillingPeriod         `json:"billing_period"`
	Currency           string                `json:"currency"`
	AnchorAt           pgtype.Timestamp      `json:"anchor_at"`
	CurrentPeriodEnd   pgtype.Timestamp      `json:"current_period_end"`
	UserID             uuid.UUID             `json:"user_id"`
	Now                pgtype.Timestamp      `json:"now"`
	ID                 uuid.UUID             `json:"id"`
	OrganizationID     uuid.UUID             `json:"organization_id"`
}

// A CANCELED subscription subscribed again: the same row, with a new price,
// anchor and period, and nothing left of the life that ended.
func (q *Queries) ResubscribeInstanceBilling(ctx context.Context, arg ResubscribeInstanceBillingParams) (InstanceBilling, error) {
	row := q.db.QueryRow(ctx, resubscribeInstanceBilling,
		arg.CustomerID,
		arg.InstanceSlug,
		arg.InstanceName,
		arg.CustomerSlug,
		arg.CustomerName,
		arg.Status,
		arg.ProviderKind,
		arg.CollectionMethod,
		arg.DaysUntilDue,
		arg.BaseLicensePriceID,
		arg.BillingPeriod,
		arg.Currency,
		arg.AnchorAt,
		arg.CurrentPeriodEnd,
		arg.UserID,
		arg.Now,
		arg.ID,
		arg.OrganizationID,
	)
	var i InstanceBilling
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InstanceID,
		&i.CustomerID,
		&i.InstanceSlug,
		&i.InstanceName,
		&i.CustomerSlug,
		&i.CustomerName,
		&i.Status,
		&i.ProviderKind,
		&i.CollectionMethod,
		&i.DaysUntilDue,
		&i.BaseLicensePriceID,
		&i.BillingPeriod,
		&i.Currency,
		&i.AnchorAt,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CancelRequestedAt,
		&i.CanceledAt,
		&i.CancellationReason,
		&i.PastDueSince,
		&i.ScheduledLicensePriceID,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.UpdatedAt,
		&i.UpdatedByID,
	)
	return i, err
}
