// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telemetry.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const billingGauges = `-- name: BillingGauges :one
SELECT
  (SELECT count(*) FROM instance_billing b
    WHERE b.status IN ('TRIAL', 'ACTIVE', 'PAST_DUE')
      AND b.current_period_end <= $1::timestamp)::bigint AS close_backlog,
  (SELECT count(*) FROM instance_billing b WHERE b.status = 'PAST_DUE')::bigint AS past_due,
  (SELECT min(i.issued_at) FROM instance_invoice i WHERE i.handoff_status = 'PENDING')::timestamp AS oldest_pending_issued_at,
  (SELECT count(*) FROM customer_billing c
    WHERE c.payment_method_status = 'ACTIVE'
      AND c.payment_method_exp_year IS NOT NULL AND c.payment_method_exp_month IS NOT NULL
      AND make_date(c.payment_method_exp_year, c.payment_method_exp_month, 1) + interval '1 month' > $2::timestamp
      AND make_date(c.payment_method_exp_year, c.payment_method_exp_month, 1) + interval '1 month'
          <= $2::timestamp + interval '30 days')::bigint AS payment_methods_expiring
`

type BillingGaugesParams struct {
	CloseBefore pgtype.Timestamp `json:"close_before"`
	Now         pgtype.Timestamp `json:"now"`
}

type BillingGaugesRow struct {
	CloseBacklog           int64            `json:"close_backlog"`
	PastDue                int64            `json:"past_due"`
	OldestPendingIssuedAt  pgtype.Timestamp `json:"oldest_pending_issued_at"`
	PaymentMethodsExpiring int64            `json:"payment_methods_expiring"`
}

// The deployment-wide gauges of §19.1, read at each metrics collection:
// what is late, owed or about to stop working, over every organization.
func (q *Queries) BillingGauges(ctx context.Context, arg BillingGaugesParams) (BillingGaugesRow, error) {
	row := q.db.QueryRow(ctx, billingGauges, arg.CloseBefore, arg.Now)
	var i BillingGaugesRow
	err := row.Scan(
		&i.CloseBacklog,
		&i.PastDue,
		&i.OldestPendingIssuedAt,
		&i.PaymentMethodsExpiring,
	)
	return i, err
}

const oldestProviderSync = `-- name: OldestProviderSync :many
SELECT provider_kind, min(last_synced_at)::timestamp AS oldest_synced_at
FROM billing_sync_state
WHERE last_synced_at IS NOT NULL
GROUP BY provider_kind
`

type OldestProviderSyncRow struct {
	ProviderKind   BillingProviderKind `json:"provider_kind"`
	OldestSyncedAt pgtype.Timestamp    `json:"oldest_synced_at"`
}

// Per provider, the least recent sync of any organization: its lag is the
// sync lag the alert watches.
func (q *Queries) OldestProviderSync(ctx context.Context) ([]OldestProviderSyncRow, error) {
	rows, err := q.db.Query(ctx, oldestProviderSync)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OldestProviderSyncRow
	for rows.Next() {
		var i OldestProviderSyncRow
		if err := rows.Scan(&i.ProviderKind, &i.OldestSyncedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
