// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const compactNotificationReads = `-- name: CompactNotificationReads :exec
DELETE FROM notification_read r
USING audit_trail at
WHERE r.audit_trail_id = at.id
  AND r.user_id = $1
  AND at.occurred_at <= $2
`

type CompactNotificationReadsParams struct {
	UserID        uuid.UUID          `json:"user_id"`
	ReadAllBefore pgtype.Timestamptz `json:"read_all_before"`
}

// Deletes the individual marks the watermark now covers. This is what bounds
// notification_read: without it the table would keep every row a user ever
// clicked, all of them redundant.
func (q *Queries) CompactNotificationReads(ctx context.Context, arg CompactNotificationReadsParams) error {
	_, err := q.db.Exec(ctx, compactNotificationReads, arg.UserID, arg.ReadAllBefore)
	return err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) AS unread_count
FROM (
  SELECT 1
  FROM audit_trail at
  LEFT JOIN notification_read r
    ON r.audit_trail_id = at.id AND r.user_id = $1
  CROSS JOIN LATERAL (
    SELECT COALESCE(
      (SELECT us.read_all_before FROM notification_user_state us WHERE us.user_id = $1),
      '-infinity'::timestamptz
    ) AS read_all_before
  ) s
  WHERE at.organization_id = $2
    AND at.event_name = ANY($3::text[])
    AND at.occurred_at >= $4
    AND r.user_id IS NULL
    AND at.occurred_at > s.read_all_before
  LIMIT $5
) capped
`

type CountUnreadNotificationsParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	EventNames     []string           `json:"event_names"`
	WindowStart    pgtype.Timestamptz `json:"window_start"`
	MaxCount       int32              `json:"max_count"`
}

// Capped deliberately: the badge shows "99+" past a point, so counting further
// buys nothing and an organization with a large backlog should not pay for it.
// The cap is the caller's, passed as max_count.
func (q *Queries) CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications,
		arg.UserID,
		arg.OrganizationID,
		arg.EventNames,
		arg.WindowStart,
		arg.MaxCount,
	)
	var unread_count int64
	err := row.Scan(&unread_count)
	return unread_count, err
}

const deleteNotificationPreferences = `-- name: DeleteNotificationPreferences :exec
DELETE FROM notification_preference
WHERE user_id = $1
  AND event_name = ANY($2::text[])
  AND channel = $3
`

type DeleteNotificationPreferencesParams struct {
	UserID     uuid.UUID `json:"user_id"`
	EventNames []string  `json:"event_names"`
	Channel    string    `json:"channel"`
}

// Used when a PUT restates the catalogue default for an event: storing "the
// default, again" would freeze today's default into the user's row and make a
// later change to it invisible to everyone who ever opened the page.
func (q *Queries) DeleteNotificationPreferences(ctx context.Context, arg DeleteNotificationPreferencesParams) error {
	_, err := q.db.Exec(ctx, deleteNotificationPreferences, arg.UserID, arg.EventNames, arg.Channel)
	return err
}

const getNotification = `-- name: GetNotification :one
SELECT
  at.id,
  at.event_name,
  at.event_type,
  at.occurred_at,
  at.payload,
  at.instance_id
FROM audit_trail at
WHERE at.id = $1
  AND at.organization_id = $2
`

type GetNotificationParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type GetNotificationRow struct {
	ID         uuid.UUID          `json:"id"`
	EventName  string             `json:"event_name"`
	EventType  string             `json:"event_type"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Payload    []byte             `json:"payload"`
	InstanceID *uuid.UUID         `json:"instance_id"`
}

// One row, for the frame pushed down an open stream. Scoped by organization for
// the same reason the feed is: the id arrives over a NOTIFY channel every replica
// listens on, so the query is what proves it belongs to this reader.
func (q *Queries) GetNotification(ctx context.Context, arg GetNotificationParams) (GetNotificationRow, error) {
	row := q.db.QueryRow(ctx, getNotification, arg.ID, arg.OrganizationID)
	var i GetNotificationRow
	err := row.Scan(
		&i.ID,
		&i.EventName,
		&i.EventType,
		&i.OccurredAt,
		&i.Payload,
		&i.InstanceID,
	)
	return i, err
}

const listNotificationPreferences = `-- name: ListNotificationPreferences :many
SELECT event_name, channel, enabled
FROM notification_preference
WHERE user_id = $1
`

type ListNotificationPreferencesRow struct {
	EventName string `json:"event_name"`
	Channel   string `json:"channel"`
	Enabled   bool   `json:"enabled"`
}

// Overrides only. Absent rows mean the catalogue default, which is resolved in
// Go rather than here so that changing a default never needs a data migration.
func (q *Queries) ListNotificationPreferences(ctx context.Context, userID uuid.UUID) ([]ListNotificationPreferencesRow, error) {
	rows, err := q.db.Query(ctx, listNotificationPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationPreferencesRow
	for rows.Next() {
		var i ListNotificationPreferencesRow
		if err := rows.Scan(&i.EventName, &i.Channel, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT
  at.id,
  at.event_name,
  at.event_type,
  at.occurred_at,
  at.payload,
  at.instance_id,
  (r.user_id IS NOT NULL OR at.occurred_at <= s.read_all_before) AS read
FROM audit_trail at
LEFT JOIN notification_read r
  ON r.audit_trail_id = at.id AND r.user_id = $1
CROSS JOIN LATERAL (
  SELECT COALESCE(
    (SELECT us.read_all_before FROM notification_user_state us WHERE us.user_id = $1),
    '-infinity'::timestamptz
  ) AS read_all_before
) s
WHERE at.organization_id = $2
  AND at.event_name = ANY($3::text[])
  AND at.occurred_at >= $4
  AND (
    $5::timestamptz IS NULL
    OR (at.occurred_at, at.id) < ($5::timestamptz, $6::uuid)
  )
  AND (
    NOT $7::boolean
    OR (r.user_id IS NULL AND at.occurred_at > s.read_all_before)
  )
ORDER BY at.occurred_at DESC, at.id DESC
LIMIT $8
`

type ListNotificationsParams struct {
	UserID           uuid.UUID          `json:"user_id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	EventNames       []string           `json:"event_names"`
	WindowStart      pgtype.Timestamptz `json:"window_start"`
	CursorOccurredAt pgtype.Timestamptz `json:"cursor_occurred_at"`
	CursorID         *uuid.UUID         `json:"cursor_id"`
	UnreadOnly       bool               `json:"unread_only"`
	LimitPlusOne     int32              `json:"limit_plus_one"`
}

type ListNotificationsRow struct {
	ID         uuid.UUID          `json:"id"`
	EventName  string             `json:"event_name"`
	EventType  string             `json:"event_type"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Payload    []byte             `json:"payload"`
	InstanceID *uuid.UUID         `json:"instance_id"`
	Read       *bool              `json:"read"`
}

// The feed: one organization's notifiable audit trail rows, newest first, with
// this user's read state resolved.
//
// Read is two things ORed: an individual mark (notification_read) or the "mark
// all read" watermark. Keeping both is what lets "mark all read" be one UPDATE
// instead of one row per notification.
//
// Cursor (keyset) pagination on (occurred_at, id) -- id tie-breaks, since
// occurred_at is not unique. Pass limit_plus_one = requested limit + 1 to learn
// whether a further page exists without a second query. On the first page, pass
// NULL for both cursor columns.
//
// unread_only is applied here rather than by the caller because the predicate it
// needs (the watermark join) only exists inside this query.
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.OrganizationID,
		arg.EventNames,
		arg.WindowStart,
		arg.CursorOccurredAt,
		arg.CursorID,
		arg.UnreadOnly,
		arg.LimitPlusOne,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsRow
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventName,
			&i.EventType,
			&i.OccurredAt,
			&i.Payload,
			&i.InstanceID,
			&i.Read,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
INSERT INTO notification_user_state (user_id, read_all_before)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
  SET read_all_before = GREATEST(notification_user_state.read_all_before, EXCLUDED.read_all_before)
`

type MarkAllNotificationsReadParams struct {
	UserID        uuid.UUID          `json:"user_id"`
	ReadAllBefore pgtype.Timestamptz `json:"read_all_before"`
}

// Moves the watermark instead of writing a row per notification.
func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, arg.UserID, arg.ReadAllBefore)
	return err
}

const markNotificationsRead = `-- name: MarkNotificationsRead :execrows
INSERT INTO notification_read (user_id, audit_trail_id)
SELECT $1, at.id
FROM audit_trail at
WHERE at.id = ANY($2::uuid[])
  AND at.organization_id = $3
ON CONFLICT DO NOTHING
`

type MarkNotificationsReadParams struct {
	UserID         uuid.UUID   `json:"user_id"`
	Ids            []uuid.UUID `json:"ids"`
	OrganizationID uuid.UUID   `json:"organization_id"`
}

// The join against audit_trail is the authorization: an id from another
// organization matches nothing and marks nothing, rather than erroring, which is
// also what makes the call idempotent for a client retrying a partial page.
func (q *Queries) MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationsRead, arg.UserID, arg.Ids, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveDeploymentZones = `-- name: ResolveDeploymentZones :many
SELECT id, slug, name
FROM deployment_zone
WHERE organization_id = $1
  AND id = ANY($2::uuid[])
`

type ResolveDeploymentZonesParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	Ids            []uuid.UUID `json:"ids"`
}

type ResolveDeploymentZonesRow struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
	Name string    `json:"name"`
}

func (q *Queries) ResolveDeploymentZones(ctx context.Context, arg ResolveDeploymentZonesParams) ([]ResolveDeploymentZonesRow, error) {
	rows, err := q.db.Query(ctx, resolveDeploymentZones, arg.OrganizationID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveDeploymentZonesRow
	for rows.Next() {
		var i ResolveDeploymentZonesRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveInstances = `-- name: ResolveInstances :many
SELECT id, slug, name
FROM instance
WHERE organization_id = $1
  AND id = ANY($2::uuid[])
`

type ResolveInstancesParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	Ids            []uuid.UUID `json:"ids"`
}

type ResolveInstancesRow struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
	Name string    `json:"name"`
}

// The objects a page of notifications names, looked up once per page rather than
// once per row. Resolved at read time for the same reason titles are rendered
// then: a payload is whatever its producer wrote, some events carry nothing but
// ids, and a link has to use the slug an object has now, not the one it had.
// Scoped by organization like every read here: the ids come from rows this reader
// may see, but the scope is what proves it.
func (q *Queries) ResolveInstances(ctx context.Context, arg ResolveInstancesParams) ([]ResolveInstancesRow, error) {
	rows, err := q.db.Query(ctx, resolveInstances, arg.OrganizationID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveInstancesRow
	for rows.Next() {
		var i ResolveInstancesRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveLicenses = `-- name: ResolveLicenses :many
SELECT id, slug, name
FROM license
WHERE organization_id = $1
  AND id = ANY($2::uuid[])
`

type ResolveLicensesParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	Ids            []uuid.UUID `json:"ids"`
}

type ResolveLicensesRow struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
	Name string    `json:"name"`
}

func (q *Queries) ResolveLicenses(ctx context.Context, arg ResolveLicensesParams) ([]ResolveLicensesRow, error) {
	rows, err := q.db.Query(ctx, resolveLicenses, arg.OrganizationID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveLicensesRow
	for rows.Next() {
		var i ResolveLicensesRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveReleases = `-- name: ResolveReleases :many
SELECT id, slug, version
FROM release
WHERE organization_id = $1
  AND id = ANY($2::uuid[])
`

type ResolveReleasesParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	Ids            []uuid.UUID `json:"ids"`
}

type ResolveReleasesRow struct {
	ID      uuid.UUID `json:"id"`
	Slug    string    `json:"slug"`
	Version string    `json:"version"`
}

func (q *Queries) ResolveReleases(ctx context.Context, arg ResolveReleasesParams) ([]ResolveReleasesRow, error) {
	rows, err := q.db.Query(ctx, resolveReleases, arg.OrganizationID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveReleasesRow
	for rows.Next() {
		var i ResolveReleasesRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNotificationPreference = `-- name: UpsertNotificationPreference :exec
INSERT INTO notification_preference (user_id, event_name, channel, enabled)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, event_name, channel) DO UPDATE
  SET enabled = EXCLUDED.enabled
`

type UpsertNotificationPreferenceParams struct {
	UserID    uuid.UUID `json:"user_id"`
	EventName string    `json:"event_name"`
	Channel   string    `json:"channel"`
	Enabled   bool      `json:"enabled"`
}

func (q *Queries) UpsertNotificationPreference(ctx context.Context, arg UpsertNotificationPreferenceParams) error {
	_, err := q.db.Exec(ctx, upsertNotificationPreference,
		arg.UserID,
		arg.EventName,
		arg.Channel,
		arg.Enabled,
	)
	return err
}
