// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox_events.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO outbox_events (organization_id,
                           event_name,
                           event_type,
                           data,
                           headers)
VALUES ($1,
    $2,
    $3,
    $4,
    $5)
`

type CreateOutboxEventParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	EventName      string    `json:"event_name"`
	EventType      string    `json:"event_type"`
	Data           []byte    `json:"data"`
	Headers        []byte    `json:"headers"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.Exec(ctx, createOutboxEvent,
		arg.OrganizationID,
		arg.EventName,
		arg.EventType,
		arg.Data,
		arg.Headers,
	)
	return err
}

type CreateOutboxEventsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	EventName      string    `json:"event_name"`
	EventType      string    `json:"event_type"`
	Data           []byte    `json:"data"`
	Headers        []byte    `json:"headers"`
}

const deleteOutboxEvent = `-- name: DeleteOutboxEvent :exec
DELETE FROM outbox_events WHERE id = $1
`

func (q *Queries) DeleteOutboxEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOutboxEvent, id)
	return err
}

const getPendingOutboxEventsWithOrg = `-- name: GetPendingOutboxEventsWithOrg :many
SELECT
    oe.id,
    oe.organization_id,
    oe.event_name,
    oe.event_type,
    oe.occurred_at,
    oe.data,
    oe.headers
FROM outbox_events oe
JOIN organization o ON oe.organization_id = o.id
ORDER BY oe.occurred_at ASC
LIMIT $1
`

func (q *Queries) GetPendingOutboxEventsWithOrg(ctx context.Context, batchSize int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxEventsWithOrg, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventName,
			&i.EventType,
			&i.OccurredAt,
			&i.Data,
			&i.Headers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutboxEvents = `-- name: ListOutboxEvents :many
SELECT id,
       organization_id,
       event_name,
       event_type,
       occurred_at,
       data,
       headers
FROM outbox_events
WHERE organization_id = $1
ORDER BY occurred_at DESC
`

func (q *Queries) ListOutboxEvents(ctx context.Context, organizationID uuid.UUID) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listOutboxEvents, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventName,
			&i.EventType,
			&i.OccurredAt,
			&i.Data,
			&i.Headers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
