// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_token.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPlatformToken = `-- name: CreatePlatformToken :one
WITH platform_identity AS (SELECT u.id
                           FROM "user" u
                           WHERE u.external_id = 'system:kaiten'
                             AND u.deleted_at IS NULL)
INSERT INTO token (kind, hash, lookup_hash, created_by, expires_at,
                   service_account_id, scopes, name, slug)
SELECT 'platform'::token_kind,
       $1,
       $2,
       platform_identity.id,
       $3,
       platform_identity.id,
       $4,
       $5,
       $6
FROM platform_identity
RETURNING id, name, slug, scopes, created_at, expires_at
`

type CreatePlatformTokenParams struct {
	Hash       string           `json:"hash"`
	LookupHash string           `json:"lookup_hash"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	Scopes     []string         `json:"scopes"`
	Name       string           `json:"name"`
	Slug       string           `json:"slug"`
}

type CreatePlatformTokenRow struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Slug      string           `json:"slug"`
	Scopes    []string         `json:"scopes"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

// Called only by kaiten-admin-tools: a platform token cannot issue another one
// (token_platform_has_no_parent enforces the same rule in the schema).
// organization_id is left out of the column list rather than written as NULL --
// the absence is the point, and token_platform_is_orgless_system checks it.
//
// The returned columns are listed explicitly rather than RETURNING *, so
// organization_id is never read -- see the file header.
//
// The CTE is named platform_identity, not system_user: SYSTEM_USER is a reserved
// word in PostgreSQL 16+ and sqlc's parser rejects it as an unquoted identifier.
func (q *Queries) CreatePlatformToken(ctx context.Context, arg CreatePlatformTokenParams) (CreatePlatformTokenRow, error) {
	row := q.db.QueryRow(ctx, createPlatformToken,
		arg.Hash,
		arg.LookupHash,
		arg.ExpiresAt,
		arg.Scopes,
		arg.Name,
		arg.Slug,
	)
	var i CreatePlatformTokenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Scopes,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createSystemOrganizationToken = `-- name: CreateSystemOrganizationToken :one
WITH platform_identity AS (SELECT u.id, u.name
                           FROM "user" u
                           WHERE u.external_id = 'system:kaiten'
                             AND u.deleted_at IS NULL),
     membership AS (SELECT uoo.user_id, uoo.organization_id, platform_identity.name
                    FROM user_on_organization uoo
                           INNER JOIN platform_identity ON platform_identity.id = uoo.user_id
                    WHERE uoo.organization_id = $1
                      AND uoo.deleted_at IS NULL),
     inserted_token AS (
       INSERT INTO token (kind, hash, lookup_hash, created_by, expires_at,
                          service_account_id, organization_id, scopes, name, slug,
                          issued_by_platform_token_id)
         SELECT 'organization'::token_kind,
                $2,
                $3,
                membership.user_id,
                $4,
                membership.user_id,
                membership.organization_id,
                $5,
                $6,
                $7,
                $8
         FROM membership
         RETURNING id, name, slug, scopes, created_at, expires_at,
           service_account_id, created_by)
SELECT inserted_token.id,
       inserted_token.name,
       inserted_token.slug,
       inserted_token.scopes,
       inserted_token.created_at,
       inserted_token.expires_at,
       inserted_token.service_account_id,
       inserted_token.created_by,
       membership.name AS created_by_name
FROM inserted_token,
     membership
`

type CreateSystemOrganizationTokenParams struct {
	OrganizationID          uuid.UUID        `json:"organization_id"`
	Hash                    string           `json:"hash"`
	LookupHash              string           `json:"lookup_hash"`
	ExpiresAt               pgtype.Timestamp `json:"expires_at"`
	Scopes                  []string         `json:"scopes"`
	Name                    string           `json:"name"`
	Slug                    string           `json:"slug"`
	IssuedByPlatformTokenID *uuid.UUID       `json:"issued_by_platform_token_id"`
}

type CreateSystemOrganizationTokenRow struct {
	ID               uuid.UUID        `json:"id"`
	Name             string           `json:"name"`
	Slug             string           `json:"slug"`
	Scopes           []string         `json:"scopes"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	ExpiresAt        pgtype.Timestamp `json:"expires_at"`
	ServiceAccountID uuid.UUID        `json:"service_account_id"`
	CreatedBy        uuid.UUID        `json:"created_by"`
	CreatedByName    string           `json:"created_by_name"`
}

// The mint: an ordinary kind='organization' token owned by system:kaiten inside
// one organization. It cannot reuse CreateToken, because that query now requires
// u.organization_id = uoo.organization_id and so deliberately excludes this
// orgless owner.
//
// Membership is resolved *inside* the INSERT, so it cannot be checked and then
// raced: zero rows means system:kaiten has no live membership in the target and
// the caller gets pgx.ErrNoRows. Nothing here creates a membership -- that is the
// organization trigger's job, and its absence is a platform invariant breach,
// not something to paper over.
//
// The owner is returned as well as used: the response is an ordinary
// schema.PlainToken, whose ServiceAccountID and CreatedBy are system:kaiten's
// membership in this organization. Resolving them here rather than in Go is what
// makes them the SAME row the INSERT actually wrote -- a second lookup could
// disagree with it.
func (q *Queries) CreateSystemOrganizationToken(ctx context.Context, arg CreateSystemOrganizationTokenParams) (CreateSystemOrganizationTokenRow, error) {
	row := q.db.QueryRow(ctx, createSystemOrganizationToken,
		arg.OrganizationID,
		arg.Hash,
		arg.LookupHash,
		arg.ExpiresAt,
		arg.Scopes,
		arg.Name,
		arg.Slug,
		arg.IssuedByPlatformTokenID,
	)
	var i CreateSystemOrganizationTokenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Scopes,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ServiceAccountID,
		&i.CreatedBy,
		&i.CreatedByName,
	)
	return i, err
}

const getActivePlatformTokenByLookupHash = `-- name: GetActivePlatformTokenByLookupHash :one

SELECT t.id,
       t.hash,
       t.service_account_id,
       t.scopes,
       t.expires_at,
       u.external_id AS service_account_external_id
FROM token t
       JOIN "user" u ON u.id = t.service_account_id
WHERE t.lookup_hash = $1
  AND t.kind = 'platform'
  AND t.revoked_date IS NULL
  AND u.deleted_at IS NULL
  AND (t.expires_at IS NULL OR t.expires_at > now())
`

type GetActivePlatformTokenByLookupHashRow struct {
	ID                       uuid.UUID        `json:"id"`
	Hash                     string           `json:"hash"`
	ServiceAccountID         uuid.UUID        `json:"service_account_id"`
	Scopes                   []string         `json:"scopes"`
	ExpiresAt                pgtype.Timestamp `json:"expires_at"`
	ServiceAccountExternalID string           `json:"service_account_external_id"`
}

// Queries for the platform credential class (token.kind = 'platform') and for
// the organization tokens it mints.
//
// Two invariants hold across this whole file:
//
//   - No query here selects token.organization_id. The generated Go type for
//     that column is pinned to a non-pointer uuid.UUID (see sqlc.yaml), which is
//     only sound because no path that can return a kind='platform' row -- where
//     the column is NULL -- ever reads it.
//   - The owner is resolved by external_id = 'system:kaiten', never by the
//     literal UUID the migration pins. A database whose identity row went
//     missing then errors instead of writing a dangling credential.
//
// The authentication path for a ksm_ credential. There is no organization join
// because a platform token has no organization -- which is also why this cannot
// share GetActiveTokenByLookupHash: that query's join is what makes an
// organization JWT possible, and the two must not be reachable from one lookup.
func (q *Queries) GetActivePlatformTokenByLookupHash(ctx context.Context, lookupHash string) (GetActivePlatformTokenByLookupHashRow, error) {
	row := q.db.QueryRow(ctx, getActivePlatformTokenByLookupHash, lookupHash)
	var i GetActivePlatformTokenByLookupHashRow
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.ServiceAccountID,
		&i.Scopes,
		&i.ExpiresAt,
		&i.ServiceAccountExternalID,
	)
	return i, err
}

const getPlatformTokenByID = `-- name: GetPlatformTokenByID :one
SELECT t.id,
       t.name,
       t.slug,
       t.scopes,
       t.created_at,
       t.expires_at
FROM token t
WHERE t.id = $1
  AND t.kind = 'platform'
  AND t.revoked_date IS NULL
  AND (t.expires_at IS NULL OR t.expires_at > now())
`

type GetPlatformTokenByIDRow struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Slug      string           `json:"slug"`
	Scopes    []string         `json:"scopes"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

// Introspection for GET /api/platform/me. Never the hash, never the lookup hash:
// this answers "which credential am I holding", not "what is its secret".
func (q *Queries) GetPlatformTokenByID(ctx context.Context, tokenID uuid.UUID) (GetPlatformTokenByIDRow, error) {
	row := q.db.QueryRow(ctx, getPlatformTokenByID, tokenID)
	var i GetPlatformTokenByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Scopes,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listPlatformTokens = `-- name: ListPlatformTokens :many
SELECT t.id,
       t.name,
       t.slug,
       t.scopes,
       t.created_at,
       t.expires_at,
       t.revoked_date
FROM token t
WHERE t.kind = 'platform'
ORDER BY t.created_at DESC
`

type ListPlatformTokensRow struct {
	ID          uuid.UUID        `json:"id"`
	Name        string           `json:"name"`
	Slug        string           `json:"slug"`
	Scopes      []string         `json:"scopes"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	ExpiresAt   pgtype.Timestamp `json:"expires_at"`
	RevokedDate pgtype.Timestamp `json:"revoked_date"`
}

// Includes revoked and expired rows: `platform-token list` is an inventory, and
// a revoked credential's absence would hide exactly the history an operator
// needs after a rotation.
func (q *Queries) ListPlatformTokens(ctx context.Context) ([]ListPlatformTokensRow, error) {
	rows, err := q.db.Query(ctx, listPlatformTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlatformTokensRow
	for rows.Next() {
		var i ListPlatformTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Scopes,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemOrganizationTokensByPlatformToken = `-- name: ListSystemOrganizationTokensByPlatformToken :many
SELECT token.id,
       token.name,
       token.slug,
       token.scopes,
       token.expires_at,
       token.created_at
FROM token
WHERE token.organization_id = $1
  AND token.issued_by_platform_token_id = $2::uuid
  AND token.revoked_date IS NULL
ORDER BY token.name
`

type ListSystemOrganizationTokensByPlatformTokenParams struct {
	OrganizationID  uuid.UUID `json:"organization_id"`
	PlatformTokenID uuid.UUID `json:"platform_token_id"`
}

type ListSystemOrganizationTokensByPlatformTokenRow struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Slug      string           `json:"slug"`
	Scopes    []string         `json:"scopes"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

// The credentials this platform credential currently holds in one organization.
//
// It exists so a client can find a credential's SLUG from the NAME it chose. The
// slug is server-generated with a random suffix (slugutil.GenerateUnique), and
// revocation is addressed by slug -- so without this, a client that wanted to
// retire a credential it had itself minted had no way to name it, and re-minting
// under the same name is refused by the token_name constraint, so a supersede
// path has no way to address the credential it needs to replace.
//
// Read-only, and narrowed exactly like RevokeSystemOrganizationTokenBySlug: the
// target organization, tokens this platform credential issued, still active. One
// platform credential therefore cannot enumerate another's children, which is the
// property that lets this be published at all -- a broader list would be a way to
// discover credentials the caller has no business seeing.
//
// No hash, no lookup_hash: nothing here can be used to authenticate as one of
// these credentials, only to identify one for revocation. The ::uuid cast forces
// a non-null parameter, as in the two revoke queries above.
func (q *Queries) ListSystemOrganizationTokensByPlatformToken(ctx context.Context, arg ListSystemOrganizationTokensByPlatformTokenParams) ([]ListSystemOrganizationTokensByPlatformTokenRow, error) {
	rows, err := q.db.Query(ctx, listSystemOrganizationTokensByPlatformToken, arg.OrganizationID, arg.PlatformTokenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSystemOrganizationTokensByPlatformTokenRow
	for rows.Next() {
		var i ListSystemOrganizationTokensByPlatformTokenRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Scopes,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeRetiredTokens = `-- name: PurgeRetiredTokens :execrows
WITH retired AS (SELECT t.id
                 FROM token t
                 WHERE (t.revoked_date IS NOT NULL AND t.revoked_date < $1)
                    OR (t.expires_at IS NOT NULL AND t.expires_at < $1)
                 ORDER BY coalesce(t.revoked_date, t.expires_at), t.id
                 LIMIT $2
                   FOR UPDATE SKIP LOCKED)
DELETE
FROM token t
  USING retired
WHERE t.id = retired.id
`

type PurgeRetiredTokensParams struct {
	RetiredBefore pgtype.Timestamp `json:"retired_before"`
	BatchSize     int32            `json:"batch_size"`
}

// Retired means revoked or expired -- a token that is neither is live and is
// never touched here, whatever its age. Deleting a parent only nulls its
// children's issued_by_platform_token_id (ON DELETE SET NULL); it does not
// delete or revoke them.
//
// One bounded batch, oldest first, so a table that has accumulated for months is
// drained over many short transactions instead of one long one holding locks and
// bloating WAL. SKIP LOCKED avoids waiting behind an unrelated transaction that is
// touching a retired row -- a concurrent revoke of an already-expired credential,
// for instance. Same shape as the transport-table purges in
// internal/infrastructure/retention.
//
// retired_at is coalesce(revoked_date, expires_at): for a row that is both, the
// revocation is what retired it, and it is necessarily the earlier of the two for
// ordering purposes only. Ordering by it, then by id, makes progress
// deterministic across batches.
func (q *Queries) PurgeRetiredTokens(ctx context.Context, arg PurgeRetiredTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeRetiredTokens, arg.RetiredBefore, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokePlatformTokenByName = `-- name: RevokePlatformTokenByName :one
WITH platform_identity AS (SELECT u.id
                           FROM "user" u
                           WHERE u.external_id = 'system:kaiten'
                             AND u.deleted_at IS NULL)
UPDATE token
SET revoked_by   = platform_identity.id,
    revoked_date = now()
FROM platform_identity
WHERE token.name = $1
  AND token.kind = 'platform'
  AND token.revoked_date IS NULL
RETURNING token.id, token.lookup_hash
`

type RevokePlatformTokenByNameRow struct {
	ID         uuid.UUID `json:"id"`
	LookupHash string    `json:"lookup_hash"`
}

// Names are unique among *active* platform tokens
// (uq_token_platform_name_active), so this matches at most one row. The revoker
// is system:kaiten itself: revocation happens in kaiten-admin-tools, where there
// is no acting user to attribute it to.
func (q *Queries) RevokePlatformTokenByName(ctx context.Context, name string) (RevokePlatformTokenByNameRow, error) {
	row := q.db.QueryRow(ctx, revokePlatformTokenByName, name)
	var i RevokePlatformTokenByNameRow
	err := row.Scan(&i.ID, &i.LookupHash)
	return i, err
}

const revokeSystemOrganizationTokenByName = `-- name: RevokeSystemOrganizationTokenByName :many
WITH platform_identity AS (SELECT u.id
                           FROM "user" u
                           WHERE u.external_id = 'system:kaiten'
                             AND u.deleted_at IS NULL)
UPDATE token
SET revoked_by   = platform_identity.id,
    revoked_date = now()
FROM platform_identity
WHERE token.service_account_id = platform_identity.id
  AND token.name = $1
  AND token.organization_id = $2
  AND token.revoked_date IS NULL
RETURNING token.id, token.lookup_hash
`

type RevokeSystemOrganizationTokenByNameParams struct {
	Name           string    `json:"name"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type RevokeSystemOrganizationTokenByNameRow struct {
	ID         uuid.UUID `json:"id"`
	LookupHash string    `json:"lookup_hash"`
}

// The revoke half of `kaiten-admin-tools service-token mint --replace`. By name,
// not by slug: the name is what the operator chose and can name again on a
// re-run, while the slug is server-generated and never reused. It is also
// parent-agnostic, unlike RevokeSystemOrganizationTokenBySlug -- an operator at a
// shell holds the database connection string and no platform credential, so the
// token being replaced may have been issued by a parent that is long gone, or by
// no parent at all.
//
// Restricted to system:kaiten's own tokens: a platform tool must not be able to
// revoke a tenant's service-account credentials by guessing a name. The partial
// token_name index means at most one row is active per name, so the result is
// always zero rows or one -- :many because "zero" is the ordinary case on a first
// run and pgx.ErrNoRows would be the wrong way to say so.
func (q *Queries) RevokeSystemOrganizationTokenByName(ctx context.Context, arg RevokeSystemOrganizationTokenByNameParams) ([]RevokeSystemOrganizationTokenByNameRow, error) {
	rows, err := q.db.Query(ctx, revokeSystemOrganizationTokenByName, arg.Name, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevokeSystemOrganizationTokenByNameRow
	for rows.Next() {
		var i RevokeSystemOrganizationTokenByNameRow
		if err := rows.Scan(&i.ID, &i.LookupHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSystemOrganizationTokenBySlug = `-- name: RevokeSystemOrganizationTokenBySlug :one
WITH platform_identity AS (SELECT u.id
                           FROM "user" u
                           WHERE u.external_id = 'system:kaiten'
                             AND u.deleted_at IS NULL)
UPDATE token
SET revoked_by   = platform_identity.id,
    revoked_date = now()
FROM platform_identity
WHERE token.slug = $1
  AND token.organization_id = $2
  AND token.issued_by_platform_token_id = $3::uuid
  AND token.revoked_date IS NULL
RETURNING token.id, token.lookup_hash
`

type RevokeSystemOrganizationTokenBySlugParams struct {
	TokenSlug       string    `json:"token_slug"`
	OrganizationID  uuid.UUID `json:"organization_id"`
	PlatformTokenID uuid.UUID `json:"platform_token_id"`
}

type RevokeSystemOrganizationTokenBySlugRow struct {
	ID         uuid.UUID `json:"id"`
	LookupHash string    `json:"lookup_hash"`
}

// Early revocation of a minted token through the Platform API, before its parent
// is retired. Scoped to the target organization and to tokens this platform
// token issued, so one platform credential cannot revoke another's children. The
// ::uuid cast forces a non-null parameter -- see
// RevokeTokensIssuedByPlatformToken.
func (q *Queries) RevokeSystemOrganizationTokenBySlug(ctx context.Context, arg RevokeSystemOrganizationTokenBySlugParams) (RevokeSystemOrganizationTokenBySlugRow, error) {
	row := q.db.QueryRow(ctx, revokeSystemOrganizationTokenBySlug, arg.TokenSlug, arg.OrganizationID, arg.PlatformTokenID)
	var i RevokeSystemOrganizationTokenBySlugRow
	err := row.Scan(&i.ID, &i.LookupHash)
	return i, err
}

const revokeTokensIssuedByPlatformToken = `-- name: RevokeTokensIssuedByPlatformToken :many
WITH platform_identity AS (SELECT u.id
                           FROM "user" u
                           WHERE u.external_id = 'system:kaiten'
                             AND u.deleted_at IS NULL)
UPDATE token
SET revoked_by   = platform_identity.id,
    revoked_date = now()
FROM platform_identity
WHERE token.issued_by_platform_token_id = $1::uuid
  AND token.revoked_date IS NULL
RETURNING token.id, token.lookup_hash
`

type RevokeTokensIssuedByPlatformTokenRow struct {
	ID         uuid.UUID `json:"id"`
	LookupHash string    `json:"lookup_hash"`
}

// The cascade from decision 11. Runs in the same transaction as the parent's
// revocation, and returns every lookup_hash so the caller can publish one cache
// eviction per token -- otherwise a revoked child keeps authenticating for as
// long as the validation cache holds it.
//
// The ::uuid cast is not cosmetic: issued_by_platform_token_id is a nullable
// column, so without it sqlc emits a *uuid.UUID parameter -- and a nil there
// would match no row (= NULL is never true) while reporting success. The parent
// id is always known, being the caller's own credential.
func (q *Queries) RevokeTokensIssuedByPlatformToken(ctx context.Context, platformTokenID uuid.UUID) ([]RevokeTokensIssuedByPlatformTokenRow, error) {
	rows, err := q.db.Query(ctx, revokeTokensIssuedByPlatformToken, platformTokenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevokeTokensIssuedByPlatformTokenRow
	for rows.Next() {
		var i RevokeTokensIssuedByPlatformTokenRow
		if err := rows.Scan(&i.ID, &i.LookupHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
