// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: redemptions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyDiscount = `-- name: ApplyDiscount :one
UPDATE instance_voucher iv
SET applications_count = iv.applications_count + 1,
    status             = CASE
                           WHEN $1::integer IS NOT NULL
                             AND iv.applications_count + 1 >= $1::integer
                             THEN 'EXPIRED'::instance_voucher_status
                           ELSE iv.status END,
    expired_at         = CASE
                           WHEN $1::integer IS NOT NULL
                             AND iv.applications_count + 1 >= $1::integer
                             THEN $2::timestamp
                           ELSE iv.expired_at END,
    updated_at         = $2::timestamp
WHERE iv.organization_id = $3
  AND iv.id = $4
RETURNING iv.status
`

type ApplyDiscountParams struct {
	ApplicationsMax *int32           `json:"applications_max"`
	Now             pgtype.Timestamp `json:"now"`
	OrganizationID  uuid.UUID        `json:"organization_id"`
	ID              uuid.UUID        `json:"id"`
}

// One invoice received a DISCOUNT line from the redemption. Reaching the
// duration's limit expires it.
func (q *Queries) ApplyDiscount(ctx context.Context, arg ApplyDiscountParams) (InstanceVoucherStatus, error) {
	row := q.db.QueryRow(ctx, applyDiscount,
		arg.ApplicationsMax,
		arg.Now,
		arg.OrganizationID,
		arg.ID,
	)
	var status InstanceVoucherStatus
	err := row.Scan(&status)
	return status, err
}

const claimRedemption = `-- name: ClaimRedemption :one
UPDATE voucher
SET redemptions_count = redemptions_count + 1,
    status            = CASE
                          WHEN max_redemptions IS NOT NULL AND redemptions_count + 1 >= max_redemptions
                            THEN 'EXHAUSTED'::voucher_status
                          ELSE status END,
    updated_at        = $1,
    updated_by_id     = $2
WHERE id = $3
  AND organization_id = $4
  AND status = 'ACTIVE'
  AND (starts_at IS NULL OR starts_at <= $1)
  AND (expires_at IS NULL OR expires_at > $1)
  AND (max_redemptions IS NULL OR redemptions_count < max_redemptions)
RETURNING redemptions_count, status
`

type ClaimRedemptionParams struct {
	Now            pgtype.Timestamp `json:"now"`
	UserID         uuid.UUID        `json:"user_id"`
	ID             uuid.UUID        `json:"id"`
	OrganizationID uuid.UUID        `json:"organization_id"`
}

type ClaimRedemptionRow struct {
	RedemptionsCount int32         `json:"redemptions_count"`
	Status           VoucherStatus `json:"status"`
}

// The conditional increment: the only race-free way to honour
// max_redemptions. No row: the voucher stopped being redeemable.
func (q *Queries) ClaimRedemption(ctx context.Context, arg ClaimRedemptionParams) (ClaimRedemptionRow, error) {
	row := q.db.QueryRow(ctx, claimRedemption,
		arg.Now,
		arg.UserID,
		arg.ID,
		arg.OrganizationID,
	)
	var i ClaimRedemptionRow
	err := row.Scan(&i.RedemptionsCount, &i.Status)
	return i, err
}

const customerHasPaid = `-- name: CustomerHasPaid :one
SELECT EXISTS (SELECT 1
               FROM instance_invoice ii
               JOIN instance_billing ib ON ib.id = ii.subscription_id
               WHERE ib.organization_id = $1
                 AND ib.customer_id = $2
                 AND ii.status = 'PAID'
                 AND ii.total_minor > 0)::boolean AS paid
`

type CustomerHasPaidParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	CustomerID     *uuid.UUID `json:"customer_id"`
}

// Whether any instance of the customer has a PAID invoice with something to
// pay: a customer who paid is no longer a first-time one.
func (q *Queries) CustomerHasPaid(ctx context.Context, arg CustomerHasPaidParams) (bool, error) {
	row := q.db.QueryRow(ctx, customerHasPaid, arg.OrganizationID, arg.CustomerID)
	var paid bool
	err := row.Scan(&paid)
	return paid, err
}

const getInstanceForRedeem = `-- name: GetInstanceForRedeem :one
SELECT i.id, i.slug, i.customer_id, i.license_id
FROM instance i
WHERE i.organization_id = $1
  AND i.slug = $2
`

type GetInstanceForRedeemParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Slug           string    `json:"slug"`
}

type GetInstanceForRedeemRow struct {
	ID         uuid.UUID `json:"id"`
	Slug       string    `json:"slug"`
	CustomerID uuid.UUID `json:"customer_id"`
	LicenseID  uuid.UUID `json:"license_id"`
}

func (q *Queries) GetInstanceForRedeem(ctx context.Context, arg GetInstanceForRedeemParams) (GetInstanceForRedeemRow, error) {
	row := q.db.QueryRow(ctx, getInstanceForRedeem, arg.OrganizationID, arg.Slug)
	var i GetInstanceForRedeemRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.CustomerID,
		&i.LicenseID,
	)
	return i, err
}

const getRedeemSubscription = `-- name: GetRedeemSubscription :one
SELECT ib.billing_period, ib.currency::text AS currency, lp.currency::text AS base_currency,
       lp.unit_amount_decimal::text AS base_amount
FROM instance_billing ib
JOIN license_price lp ON lp.id = ib.base_license_price_id AND lp.organization_id = ib.organization_id
WHERE ib.organization_id = $1
  AND ib.instance_id = $2
  AND ib.status IN ('TRIAL', 'ACTIVE', 'PAST_DUE')
FOR SHARE OF ib
`

type GetRedeemSubscriptionParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	InstanceID     *uuid.UUID `json:"instance_id"`
}

type GetRedeemSubscriptionRow struct {
	BillingPeriod BillingPeriod `json:"billing_period"`
	Currency      string        `json:"currency"`
	BaseCurrency  string        `json:"base_currency"`
	BaseAmount    string        `json:"base_amount"`
}

// The instance's live subscription, held FOR SHARE so the currency and period
// checks hold until the redemption commits, with its base price.
func (q *Queries) GetRedeemSubscription(ctx context.Context, arg GetRedeemSubscriptionParams) (GetRedeemSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getRedeemSubscription, arg.OrganizationID, arg.InstanceID)
	var i GetRedeemSubscriptionRow
	err := row.Scan(
		&i.BillingPeriod,
		&i.Currency,
		&i.BaseCurrency,
		&i.BaseAmount,
	)
	return i, err
}

const insertInstanceVoucher = `-- name: InsertInstanceVoucher :one
INSERT INTO instance_voucher (organization_id, instance_id, voucher_id, redeemed_at, redeemed_by_id,
                              effective_starts_at, effective_expires_at)
VALUES ($1, $2, $3, $4, $5,
        $4, $6)
RETURNING id
`

type InsertInstanceVoucherParams struct {
	OrganizationID     uuid.UUID        `json:"organization_id"`
	InstanceID         uuid.UUID        `json:"instance_id"`
	VoucherID          uuid.UUID        `json:"voucher_id"`
	Now                pgtype.Timestamp `json:"now"`
	UserID             uuid.UUID        `json:"user_id"`
	EffectiveExpiresAt pgtype.Timestamp `json:"effective_expires_at"`
}

func (q *Queries) InsertInstanceVoucher(ctx context.Context, arg InsertInstanceVoucherParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertInstanceVoucher,
		arg.OrganizationID,
		arg.InstanceID,
		arg.VoucherID,
		arg.Now,
		arg.UserID,
		arg.EffectiveExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const instanceHasBoostable = `-- name: InstanceHasBoostable :one
SELECT EXISTS (SELECT 1
               FROM instance_effective_entitlement ee
               WHERE ee.instance_id = $1
                 AND ee.entitlement_type IN ('NUMBER', 'NUMBER_AI_CREDIT')
                 AND ee.entitlement_id = ANY ($2::uuid[]))::boolean AS boostable
`

type InstanceHasBoostableParams struct {
	InstanceID     uuid.UUID   `json:"instance_id"`
	EntitlementIds []uuid.UUID `json:"entitlement_ids"`
}

// Whether the instance has a number entitlement among those a boost targets.
func (q *Queries) InstanceHasBoostable(ctx context.Context, arg InstanceHasBoostableParams) (bool, error) {
	row := q.db.QueryRow(ctx, instanceHasBoostable, arg.InstanceID, arg.EntitlementIds)
	var boostable bool
	err := row.Scan(&boostable)
	return boostable, err
}

const instanceHoldsAnyAddon = `-- name: InstanceHoldsAnyAddon :one
SELECT EXISTS (SELECT 1
               FROM instance_addon ia
               WHERE ia.instance_id = $1
                 AND ia.removed_at IS NULL
                 AND ia.addon_id = ANY ($2::uuid[]))::boolean AS holds
`

type InstanceHoldsAnyAddonParams struct {
	InstanceID uuid.UUID   `json:"instance_id"`
	AddonIds   []uuid.UUID `json:"addon_ids"`
}

func (q *Queries) InstanceHoldsAnyAddon(ctx context.Context, arg InstanceHoldsAnyAddonParams) (bool, error) {
	row := q.db.QueryRow(ctx, instanceHoldsAnyAddon, arg.InstanceID, arg.AddonIds)
	var holds bool
	err := row.Scan(&holds)
	return holds, err
}

const instanceRedeemed = `-- name: InstanceRedeemed :one
SELECT EXISTS (SELECT 1
               FROM instance_voucher iv
               WHERE iv.instance_id = $1
                 AND iv.voucher_id = $2)::boolean AS redeemed
`

type InstanceRedeemedParams struct {
	InstanceID uuid.UUID `json:"instance_id"`
	VoucherID  uuid.UUID `json:"voucher_id"`
}

func (q *Queries) InstanceRedeemed(ctx context.Context, arg InstanceRedeemedParams) (bool, error) {
	row := q.db.QueryRow(ctx, instanceRedeemed, arg.InstanceID, arg.VoucherID)
	var redeemed bool
	err := row.Scan(&redeemed)
	return redeemed, err
}

const listApplicableDiscounts = `-- name: ListApplicableDiscounts :many
SELECT iv.id AS instance_voucher_id, iv.voucher_id, v.name, v.price_discount_type,
       coalesce(v.price_discount_value::text, '')::text AS price_discount_value, coalesce(v.currency::text, '')::text AS currency, v.price_applies_to,
       v.applicable_license_price_ids::uuid[] AS applicable_license_price_ids,
       v.applicable_addon_price_ids::uuid[] AS applicable_addon_price_ids, v.duration, v.duration_in_periods,
       iv.applications_count
FROM instance_voucher iv
JOIN voucher v ON v.id = iv.voucher_id AND v.organization_id = iv.organization_id
WHERE iv.organization_id = $1
  AND iv.instance_id = $2
  AND iv.status = 'ACTIVE'
  AND v.voucher_type = 'PRICE'
  AND iv.redeemed_at <= $3
  AND iv.effective_starts_at <= $3
  AND (iv.effective_expires_at IS NULL OR $3 < iv.effective_expires_at)
ORDER BY iv.redeemed_at, iv.id
`

type ListApplicableDiscountsParams struct {
	OrganizationID uuid.UUID        `json:"organization_id"`
	InstanceID     uuid.UUID        `json:"instance_id"`
	At             pgtype.Timestamp `json:"at"`
}

type ListApplicableDiscountsRow struct {
	InstanceVoucherID         uuid.UUID          `json:"instance_voucher_id"`
	VoucherID                 uuid.UUID          `json:"voucher_id"`
	Name                      string             `json:"name"`
	PriceDiscountType         *PriceDiscountType `json:"price_discount_type"`
	PriceDiscountValue        string             `json:"price_discount_value"`
	Currency                  string             `json:"currency"`
	PriceAppliesTo            *PriceAppliesTo    `json:"price_applies_to"`
	ApplicableLicensePriceIds []uuid.UUID        `json:"applicable_license_price_ids"`
	ApplicableAddonPriceIds   []uuid.UUID        `json:"applicable_addon_price_ids"`
	Duration                  VoucherDuration    `json:"duration"`
	DurationInPeriods         *int32             `json:"duration_in_periods"`
	ApplicationsCount         int32              `json:"applications_count"`
}

// What billing reads at a boundary: the instance's PRICE redemptions that
// may apply to an invoice composed at an instant, oldest first.
func (q *Queries) ListApplicableDiscounts(ctx context.Context, arg ListApplicableDiscountsParams) ([]ListApplicableDiscountsRow, error) {
	rows, err := q.db.Query(ctx, listApplicableDiscounts, arg.OrganizationID, arg.InstanceID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicableDiscountsRow
	for rows.Next() {
		var i ListApplicableDiscountsRow
		if err := rows.Scan(
			&i.InstanceVoucherID,
			&i.VoucherID,
			&i.Name,
			&i.PriceDiscountType,
			&i.PriceDiscountValue,
			&i.Currency,
			&i.PriceAppliesTo,
			&i.ApplicableLicensePriceIds,
			&i.ApplicableAddonPriceIds,
			&i.Duration,
			&i.DurationInPeriods,
			&i.ApplicationsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRedemptions = `-- name: ListRedemptions :many
SELECT iv.id, iv.voucher_id, v.name AS voucher_name, v.voucher_type, v.code_normalized, i.slug AS instance_slug,
       iv.redeemed_at, iv.effective_starts_at, iv.effective_expires_at, iv.applications_count, iv.status,
       iv.expired_at, iv.revoked_at, iv.revoked_reason, v.duration, v.duration_in_periods
FROM instance_voucher iv
JOIN voucher v ON v.id = iv.voucher_id AND v.organization_id = iv.organization_id
JOIN instance i ON i.id = iv.instance_id AND i.organization_id = iv.organization_id
WHERE iv.organization_id = $1
  AND ($2::uuid IS NULL OR iv.instance_id = $2)
  AND ($3::uuid IS NULL OR iv.voucher_id = $3)
  AND ($4::uuid IS NULL OR iv.id = $4)
  AND ($5::instance_voucher_status IS NULL OR iv.status = $5)
ORDER BY iv.redeemed_at DESC, iv.id DESC
`

type ListRedemptionsParams struct {
	OrganizationID uuid.UUID              `json:"organization_id"`
	InstanceID     *uuid.UUID             `json:"instance_id"`
	VoucherID      *uuid.UUID             `json:"voucher_id"`
	ID             *uuid.UUID             `json:"id"`
	Status         *InstanceVoucherStatus `json:"status"`
}

type ListRedemptionsRow struct {
	ID                 uuid.UUID             `json:"id"`
	VoucherID          uuid.UUID             `json:"voucher_id"`
	VoucherName        string                `json:"voucher_name"`
	VoucherType        VoucherType           `json:"voucher_type"`
	CodeNormalized     *string               `json:"code_normalized"`
	InstanceSlug       string                `json:"instance_slug"`
	RedeemedAt         pgtype.Timestamp      `json:"redeemed_at"`
	EffectiveStartsAt  pgtype.Timestamp      `json:"effective_starts_at"`
	EffectiveExpiresAt pgtype.Timestamp      `json:"effective_expires_at"`
	ApplicationsCount  int32                 `json:"applications_count"`
	Status             InstanceVoucherStatus `json:"status"`
	ExpiredAt          pgtype.Timestamp      `json:"expired_at"`
	RevokedAt          pgtype.Timestamp      `json:"revoked_at"`
	RevokedReason      *string               `json:"revoked_reason"`
	Duration           VoucherDuration       `json:"duration"`
	DurationInPeriods  *int32                `json:"duration_in_periods"`
}

func (q *Queries) ListRedemptions(ctx context.Context, arg ListRedemptionsParams) ([]ListRedemptionsRow, error) {
	rows, err := q.db.Query(ctx, listRedemptions,
		arg.OrganizationID,
		arg.InstanceID,
		arg.VoucherID,
		arg.ID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRedemptionsRow
	for rows.Next() {
		var i ListRedemptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.VoucherID,
			&i.VoucherName,
			&i.VoucherType,
			&i.CodeNormalized,
			&i.InstanceSlug,
			&i.RedeemedAt,
			&i.EffectiveStartsAt,
			&i.EffectiveExpiresAt,
			&i.ApplicationsCount,
			&i.Status,
			&i.ExpiredAt,
			&i.RevokedAt,
			&i.RevokedReason,
			&i.Duration,
			&i.DurationInPeriods,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInstanceVoucher = `-- name: LockInstanceVoucher :one
SELECT iv.id, iv.status
FROM instance_voucher iv
WHERE iv.organization_id = $1
  AND iv.instance_id = $2
  AND iv.id = $3
FOR UPDATE
`

type LockInstanceVoucherParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	InstanceID     uuid.UUID `json:"instance_id"`
	ID             uuid.UUID `json:"id"`
}

type LockInstanceVoucherRow struct {
	ID     uuid.UUID             `json:"id"`
	Status InstanceVoucherStatus `json:"status"`
}

func (q *Queries) LockInstanceVoucher(ctx context.Context, arg LockInstanceVoucherParams) (LockInstanceVoucherRow, error) {
	row := q.db.QueryRow(ctx, lockInstanceVoucher, arg.OrganizationID, arg.InstanceID, arg.ID)
	var i LockInstanceVoucherRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const revokeInstanceVoucher = `-- name: RevokeInstanceVoucher :exec
UPDATE instance_voucher
SET status         = 'REVOKED',
    revoked_at     = $1,
    revoked_by_id  = $2::uuid,
    revoked_reason = $3,
    updated_at     = $1
WHERE organization_id = $4
  AND id = $5
`

type RevokeInstanceVoucherParams struct {
	Now            pgtype.Timestamp `json:"now"`
	UserID         uuid.UUID        `json:"user_id"`
	Reason         *string          `json:"reason"`
	OrganizationID uuid.UUID        `json:"organization_id"`
	ID             uuid.UUID        `json:"id"`
}

func (q *Queries) RevokeInstanceVoucher(ctx context.Context, arg RevokeInstanceVoucherParams) error {
	_, err := q.db.Exec(ctx, revokeInstanceVoucher,
		arg.Now,
		arg.UserID,
		arg.Reason,
		arg.OrganizationID,
		arg.ID,
	)
	return err
}
