// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vouchers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAddonPrices = `-- name: CountAddonPrices :one
SELECT count(*)::integer
FROM addon_price
WHERE organization_id = $1
  AND id = ANY ($2::uuid[])
`

type CountAddonPricesParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	Ids            []uuid.UUID `json:"ids"`
}

func (q *Queries) CountAddonPrices(ctx context.Context, arg CountAddonPricesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countAddonPrices, arg.OrganizationID, arg.Ids)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countAddons = `-- name: CountAddons :one
SELECT count(*)::integer
FROM addon
WHERE organization_id = $1
  AND id = ANY ($2::uuid[])
`

type CountAddonsParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	Ids            []uuid.UUID `json:"ids"`
}

func (q *Queries) CountAddons(ctx context.Context, arg CountAddonsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countAddons, arg.OrganizationID, arg.Ids)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countLicensePrices = `-- name: CountLicensePrices :one
SELECT count(*)::integer
FROM license_price
WHERE organization_id = $1
  AND id = ANY ($2::uuid[])
`

type CountLicensePricesParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	Ids            []uuid.UUID `json:"ids"`
}

func (q *Queries) CountLicensePrices(ctx context.Context, arg CountLicensePricesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countLicensePrices, arg.OrganizationID, arg.Ids)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countLicenses = `-- name: CountLicenses :one
SELECT count(*)::integer
FROM license
WHERE organization_id = $1
  AND id = ANY ($2::uuid[])
`

type CountLicensesParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	Ids            []uuid.UUID `json:"ids"`
}

func (q *Queries) CountLicenses(ctx context.Context, arg CountLicensesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countLicenses, arg.OrganizationID, arg.Ids)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteVoucherGrants = `-- name: DeleteVoucherGrants :exec
DELETE
FROM voucher_entitlement_grant
WHERE organization_id = $1
  AND voucher_id = $2
`

type DeleteVoucherGrantsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	VoucherID      uuid.UUID `json:"voucher_id"`
}

func (q *Queries) DeleteVoucherGrants(ctx context.Context, arg DeleteVoucherGrantsParams) error {
	_, err := q.db.Exec(ctx, deleteVoucherGrants, arg.OrganizationID, arg.VoucherID)
	return err
}

const getBoostableEntitlement = `-- name: GetBoostableEntitlement :one
SELECT id, type
FROM entitlement
WHERE organization_id = $1
  AND slug = $2
`

type GetBoostableEntitlementParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Slug           string    `json:"slug"`
}

type GetBoostableEntitlementRow struct {
	ID   uuid.UUID       `json:"id"`
	Type EntitlementType `json:"type"`
}

func (q *Queries) GetBoostableEntitlement(ctx context.Context, arg GetBoostableEntitlementParams) (GetBoostableEntitlementRow, error) {
	row := q.db.QueryRow(ctx, getBoostableEntitlement, arg.OrganizationID, arg.Slug)
	var i GetBoostableEntitlementRow
	err := row.Scan(&i.ID, &i.Type)
	return i, err
}

const getCustomerIDBySlug = `-- name: GetCustomerIDBySlug :one
SELECT id
FROM customer
WHERE organization_id = $1
  AND slug = $2
`

type GetCustomerIDBySlugParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Slug           string    `json:"slug"`
}

func (q *Queries) GetCustomerIDBySlug(ctx context.Context, arg GetCustomerIDBySlugParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getCustomerIDBySlug, arg.OrganizationID, arg.Slug)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertVoucher = `-- name: InsertVoucher :one
INSERT INTO voucher (organization_id, code, name, description, voucher_type, duration, duration_in_periods,
                     max_redemptions, starts_at, expires_at, price_discount_type, price_discount_value, currency,
                     price_applies_to, applicable_license_price_ids, applicable_addon_price_ids,
                     applicable_license_ids, applicable_addon_ids, restricted_customer_id, redemption_rules,
                     created_by_id, updated_by_id)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9,
        $10, $11,
        CAST($12::text AS NUMERIC), $13, $14,
        $15::uuid[], $16::uuid[],
        $17::uuid[], $18::uuid[],
        $19, $20, $21, $21)
RETURNING id
`

type InsertVoucherParams struct {
	OrganizationID            uuid.UUID          `json:"organization_id"`
	Code                      string             `json:"code"`
	Name                      string             `json:"name"`
	Description               *string            `json:"description"`
	VoucherType               VoucherType        `json:"voucher_type"`
	Duration                  VoucherDuration    `json:"duration"`
	DurationInPeriods         *int32             `json:"duration_in_periods"`
	MaxRedemptions            *int32             `json:"max_redemptions"`
	StartsAt                  pgtype.Timestamp   `json:"starts_at"`
	ExpiresAt                 pgtype.Timestamp   `json:"expires_at"`
	PriceDiscountType         *PriceDiscountType `json:"price_discount_type"`
	PriceDiscountValue        *string            `json:"price_discount_value"`
	Currency                  *string            `json:"currency"`
	PriceAppliesTo            *PriceAppliesTo    `json:"price_applies_to"`
	ApplicableLicensePriceIds []uuid.UUID        `json:"applicable_license_price_ids"`
	ApplicableAddonPriceIds   []uuid.UUID        `json:"applicable_addon_price_ids"`
	ApplicableLicenseIds      []uuid.UUID        `json:"applicable_license_ids"`
	ApplicableAddonIds        []uuid.UUID        `json:"applicable_addon_ids"`
	RestrictedCustomerID      *uuid.UUID         `json:"restricted_customer_id"`
	RedemptionRules           []byte             `json:"redemption_rules"`
	UserID                    uuid.UUID          `json:"user_id"`
}

func (q *Queries) InsertVoucher(ctx context.Context, arg InsertVoucherParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertVoucher,
		arg.OrganizationID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.VoucherType,
		arg.Duration,
		arg.DurationInPeriods,
		arg.MaxRedemptions,
		arg.StartsAt,
		arg.ExpiresAt,
		arg.PriceDiscountType,
		arg.PriceDiscountValue,
		arg.Currency,
		arg.PriceAppliesTo,
		arg.ApplicableLicensePriceIds,
		arg.ApplicableAddonPriceIds,
		arg.ApplicableLicenseIds,
		arg.ApplicableAddonIds,
		arg.RestrictedCustomerID,
		arg.RedemptionRules,
		arg.UserID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertVoucherGrant = `-- name: InsertVoucherGrant :exec
INSERT INTO voucher_entitlement_grant (organization_id, voucher_id, entitlement_id, modifier_type, modifier_value)
VALUES ($1, $2, $3, $4,
        CAST($5::text AS NUMERIC))
`

type InsertVoucherGrantParams struct {
	OrganizationID uuid.UUID         `json:"organization_id"`
	VoucherID      uuid.UUID         `json:"voucher_id"`
	EntitlementID  uuid.UUID         `json:"entitlement_id"`
	ModifierType   BoostModifierType `json:"modifier_type"`
	ModifierValue  *string           `json:"modifier_value"`
}

func (q *Queries) InsertVoucherGrant(ctx context.Context, arg InsertVoucherGrantParams) error {
	_, err := q.db.Exec(ctx, insertVoucherGrant,
		arg.OrganizationID,
		arg.VoucherID,
		arg.EntitlementID,
		arg.ModifierType,
		arg.ModifierValue,
	)
	return err
}

const listVoucherGrants = `-- name: ListVoucherGrants :many
SELECT g.voucher_id, g.modifier_type, coalesce(g.modifier_value::text, '')::text AS modifier_value, e.slug AS entitlement_slug,
       g.entitlement_id
FROM voucher_entitlement_grant g
JOIN entitlement e ON e.id = g.entitlement_id AND e.organization_id = g.organization_id
WHERE g.organization_id = $1
  AND g.voucher_id = ANY ($2::uuid[])
ORDER BY e.slug
`

type ListVoucherGrantsParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	VoucherIds     []uuid.UUID `json:"voucher_ids"`
}

type ListVoucherGrantsRow struct {
	VoucherID       uuid.UUID         `json:"voucher_id"`
	ModifierType    BoostModifierType `json:"modifier_type"`
	ModifierValue   string            `json:"modifier_value"`
	EntitlementSlug string            `json:"entitlement_slug"`
	EntitlementID   uuid.UUID         `json:"entitlement_id"`
}

func (q *Queries) ListVoucherGrants(ctx context.Context, arg ListVoucherGrantsParams) ([]ListVoucherGrantsRow, error) {
	rows, err := q.db.Query(ctx, listVoucherGrants, arg.OrganizationID, arg.VoucherIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVoucherGrantsRow
	for rows.Next() {
		var i ListVoucherGrantsRow
		if err := rows.Scan(
			&i.VoucherID,
			&i.ModifierType,
			&i.ModifierValue,
			&i.EntitlementSlug,
			&i.EntitlementID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVouchers = `-- name: ListVouchers :many
SELECT v.id, v.code, v.code_normalized, v.name, v.description, v.voucher_type, v.status, v.duration,
       v.duration_in_periods, v.max_redemptions, v.redemptions_count, v.starts_at, v.expires_at,
       v.price_discount_type, coalesce(v.price_discount_value::text, '')::text AS price_discount_value, coalesce(v.currency::text, '')::text AS currency,
       v.price_applies_to, v.applicable_license_price_ids::uuid[] AS applicable_license_price_ids,
       v.applicable_addon_price_ids::uuid[] AS applicable_addon_price_ids,
       v.applicable_license_ids::uuid[] AS applicable_license_ids,
       v.applicable_addon_ids::uuid[] AS applicable_addon_ids, v.restricted_customer_id,
       c.slug AS restricted_customer_slug, v.redemption_rules, v.created_at, v.updated_at
FROM voucher v
LEFT JOIN customer c ON c.id = v.restricted_customer_id AND c.organization_id = v.organization_id
WHERE v.organization_id = $1
  AND ($2::uuid IS NULL OR v.id = $2)
  AND ($3::text IS NULL
    OR v.code_normalized = upper(regexp_replace($3::text, '[^A-Za-z0-9]', '', 'g')))
  AND ($4::voucher_status IS NULL OR v.status = $4)
  AND ($5::voucher_type IS NULL OR v.voucher_type = $5)
  AND ($6::text IS NULL OR c.slug = $6)
ORDER BY v.created_at DESC, v.id DESC
`

type ListVouchersParams struct {
	OrganizationID uuid.UUID      `json:"organization_id"`
	ID             *uuid.UUID     `json:"id"`
	Code           *string        `json:"code"`
	Status         *VoucherStatus `json:"status"`
	VoucherType    *VoucherType   `json:"voucher_type"`
	CustomerSlug   *string        `json:"customer_slug"`
}

type ListVouchersRow struct {
	ID                        uuid.UUID          `json:"id"`
	Code                      string             `json:"code"`
	CodeNormalized            *string            `json:"code_normalized"`
	Name                      string             `json:"name"`
	Description               *string            `json:"description"`
	VoucherType               VoucherType        `json:"voucher_type"`
	Status                    VoucherStatus      `json:"status"`
	Duration                  VoucherDuration    `json:"duration"`
	DurationInPeriods         *int32             `json:"duration_in_periods"`
	MaxRedemptions            *int32             `json:"max_redemptions"`
	RedemptionsCount          int32              `json:"redemptions_count"`
	StartsAt                  pgtype.Timestamp   `json:"starts_at"`
	ExpiresAt                 pgtype.Timestamp   `json:"expires_at"`
	PriceDiscountType         *PriceDiscountType `json:"price_discount_type"`
	PriceDiscountValue        string             `json:"price_discount_value"`
	Currency                  string             `json:"currency"`
	PriceAppliesTo            *PriceAppliesTo    `json:"price_applies_to"`
	ApplicableLicensePriceIds []uuid.UUID        `json:"applicable_license_price_ids"`
	ApplicableAddonPriceIds   []uuid.UUID        `json:"applicable_addon_price_ids"`
	ApplicableLicenseIds      []uuid.UUID        `json:"applicable_license_ids"`
	ApplicableAddonIds        []uuid.UUID        `json:"applicable_addon_ids"`
	RestrictedCustomerID      *uuid.UUID         `json:"restricted_customer_id"`
	RestrictedCustomerSlug    *string            `json:"restricted_customer_slug"`
	RedemptionRules           []byte             `json:"redemption_rules"`
	CreatedAt                 pgtype.Timestamp   `json:"created_at"`
	UpdatedAt                 pgtype.Timestamp   `json:"updated_at"`
}

// Vouchers with their decimals as text, newest first; id narrows to one,
// code to the one a normalized code names.
func (q *Queries) ListVouchers(ctx context.Context, arg ListVouchersParams) ([]ListVouchersRow, error) {
	rows, err := q.db.Query(ctx, listVouchers,
		arg.OrganizationID,
		arg.ID,
		arg.Code,
		arg.Status,
		arg.VoucherType,
		arg.CustomerSlug,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVouchersRow
	for rows.Next() {
		var i ListVouchersRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.CodeNormalized,
			&i.Name,
			&i.Description,
			&i.VoucherType,
			&i.Status,
			&i.Duration,
			&i.DurationInPeriods,
			&i.MaxRedemptions,
			&i.RedemptionsCount,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.PriceDiscountType,
			&i.PriceDiscountValue,
			&i.Currency,
			&i.PriceAppliesTo,
			&i.ApplicableLicensePriceIds,
			&i.ApplicableAddonPriceIds,
			&i.ApplicableLicenseIds,
			&i.ApplicableAddonIds,
			&i.RestrictedCustomerID,
			&i.RestrictedCustomerSlug,
			&i.RedemptionRules,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockVoucher = `-- name: LockVoucher :one
SELECT v.id, v.status, v.voucher_type, v.redemptions_count
FROM voucher v
WHERE v.organization_id = $1
  AND v.id = $2
FOR UPDATE
`

type LockVoucherParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

type LockVoucherRow struct {
	ID               uuid.UUID     `json:"id"`
	Status           VoucherStatus `json:"status"`
	VoucherType      VoucherType   `json:"voucher_type"`
	RedemptionsCount int32         `json:"redemptions_count"`
}

func (q *Queries) LockVoucher(ctx context.Context, arg LockVoucherParams) (LockVoucherRow, error) {
	row := q.db.QueryRow(ctx, lockVoucher, arg.OrganizationID, arg.ID)
	var i LockVoucherRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.VoucherType,
		&i.RedemptionsCount,
	)
	return i, err
}

const setVoucherStatus = `-- name: SetVoucherStatus :exec
UPDATE voucher
SET status        = $1,
    updated_at    = CURRENT_TIMESTAMP,
    updated_by_id = $2
WHERE organization_id = $3
  AND id = $4
`

type SetVoucherStatusParams struct {
	Status         VoucherStatus `json:"status"`
	UserID         uuid.UUID     `json:"user_id"`
	OrganizationID uuid.UUID     `json:"organization_id"`
	ID             uuid.UUID     `json:"id"`
}

func (q *Queries) SetVoucherStatus(ctx context.Context, arg SetVoucherStatusParams) error {
	_, err := q.db.Exec(ctx, setVoucherStatus,
		arg.Status,
		arg.UserID,
		arg.OrganizationID,
		arg.ID,
	)
	return err
}

const updateVoucher = `-- name: UpdateVoucher :exec
UPDATE voucher
SET code                         = $1,
    name                         = $2,
    description                  = $3,
    duration                     = $4,
    duration_in_periods          = $5,
    max_redemptions              = $6,
    starts_at                    = $7,
    expires_at                   = $8,
    price_discount_type          = $9,
    price_discount_value         = CAST($10::text AS NUMERIC),
    currency                     = $11,
    price_applies_to             = $12,
    applicable_license_price_ids = $13::uuid[],
    applicable_addon_price_ids   = $14::uuid[],
    applicable_license_ids       = $15::uuid[],
    applicable_addon_ids         = $16::uuid[],
    restricted_customer_id       = $17,
    redemption_rules             = $18,
    updated_at                   = CURRENT_TIMESTAMP,
    updated_by_id                = $19
WHERE organization_id = $20
  AND id = $21
`

type UpdateVoucherParams struct {
	Code                      string             `json:"code"`
	Name                      string             `json:"name"`
	Description               *string            `json:"description"`
	Duration                  VoucherDuration    `json:"duration"`
	DurationInPeriods         *int32             `json:"duration_in_periods"`
	MaxRedemptions            *int32             `json:"max_redemptions"`
	StartsAt                  pgtype.Timestamp   `json:"starts_at"`
	ExpiresAt                 pgtype.Timestamp   `json:"expires_at"`
	PriceDiscountType         *PriceDiscountType `json:"price_discount_type"`
	PriceDiscountValue        *string            `json:"price_discount_value"`
	Currency                  *string            `json:"currency"`
	PriceAppliesTo            *PriceAppliesTo    `json:"price_applies_to"`
	ApplicableLicensePriceIds []uuid.UUID        `json:"applicable_license_price_ids"`
	ApplicableAddonPriceIds   []uuid.UUID        `json:"applicable_addon_price_ids"`
	ApplicableLicenseIds      []uuid.UUID        `json:"applicable_license_ids"`
	ApplicableAddonIds        []uuid.UUID        `json:"applicable_addon_ids"`
	RestrictedCustomerID      *uuid.UUID         `json:"restricted_customer_id"`
	RedemptionRules           []byte             `json:"redemption_rules"`
	UserID                    uuid.UUID          `json:"user_id"`
	OrganizationID            uuid.UUID          `json:"organization_id"`
	ID                        uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateVoucher(ctx context.Context, arg UpdateVoucherParams) error {
	_, err := q.db.Exec(ctx, updateVoucher,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Duration,
		arg.DurationInPeriods,
		arg.MaxRedemptions,
		arg.StartsAt,
		arg.ExpiresAt,
		arg.PriceDiscountType,
		arg.PriceDiscountValue,
		arg.Currency,
		arg.PriceAppliesTo,
		arg.ApplicableLicensePriceIds,
		arg.ApplicableAddonPriceIds,
		arg.ApplicableLicenseIds,
		arg.ApplicableAddonIds,
		arg.RestrictedCustomerID,
		arg.RedemptionRules,
		arg.UserID,
		arg.OrganizationID,
		arg.ID,
	)
	return err
}

const voucherClock = `-- name: VoucherClock :one
SELECT date_trunc('milliseconds', clock_timestamp() AT TIME ZONE 'UTC')::timestamp(3) AS now
`

func (q *Queries) VoucherClock(ctx context.Context) (pgtype.Timestamp, error) {
	row := q.db.QueryRow(ctx, voucherClock)
	var now pgtype.Timestamp
	err := row.Scan(&now)
	return now, err
}
