// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
WITH inserted AS (
  INSERT INTO customer (name, slug, external_customer_id, domain, created_by_id, updated_by_id, organization_id)
  SELECT $1, $2, $3, $4, uo.user_id, uo.user_id, uo.organization_id
  FROM user_on_organization uo
  WHERE uo.organization_id = $5
         AND uo.user_id = $6
         AND uo.deleted_at IS NULL
  RETURNING id, name, slug, external_customer_id, created_by_id, created_at, updated_by_id, updated_at, organization_id, domain
)
SELECT inserted.id, inserted.name, inserted.slug, inserted.external_customer_id, inserted.created_by_id, inserted.created_at, inserted.updated_by_id, inserted.updated_at, inserted.organization_id, inserted.domain,
       creator.name AS created_by_name,
       updater.name AS updated_by_name
FROM inserted
  INNER JOIN "user" creator ON inserted.created_by_id = creator.id
  INNER JOIN "user" updater ON inserted.updated_by_id = updater.id
`

type CreateCustomerParams struct {
	Name               string    `json:"name"`
	Slug               string    `json:"slug"`
	ExternalCustomerID *string   `json:"external_customer_id"`
	Domain             *string   `json:"domain"`
	OrganizationID     uuid.UUID `json:"organization_id"`
	UserID             uuid.UUID `json:"user_id"`
}

type CreateCustomerRow struct {
	ID                 uuid.UUID        `json:"id"`
	Name               string           `json:"name"`
	Slug               string           `json:"slug"`
	ExternalCustomerID *string          `json:"external_customer_id"`
	CreatedByID        uuid.UUID        `json:"created_by_id"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedByID        uuid.UUID        `json:"updated_by_id"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	OrganizationID     uuid.UUID        `json:"organization_id"`
	Domain             *string          `json:"domain"`
	CreatedByName      string           `json:"created_by_name"`
	UpdatedByName      string           `json:"updated_by_name"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (CreateCustomerRow, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.Name,
		arg.Slug,
		arg.ExternalCustomerID,
		arg.Domain,
		arg.OrganizationID,
		arg.UserID,
	)
	var i CreateCustomerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ExternalCustomerID,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedByID,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.Domain,
		&i.CreatedByName,
		&i.UpdatedByName,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :one
WITH deleted AS (
  DELETE
  FROM customer c
  WHERE c.slug = $1
         AND c.organization_id = $2
  RETURNING c.id, c.name, c.slug, c.external_customer_id, c.created_by_id, c.created_at, c.updated_by_id, c.updated_at, c.organization_id, c.domain
)
SELECT deleted.id, deleted.name, deleted.slug, deleted.external_customer_id, deleted.created_by_id, deleted.created_at, deleted.updated_by_id, deleted.updated_at, deleted.organization_id, deleted.domain,
       creator.name AS created_by_name,
       updater.name AS updated_by_name
FROM deleted
  INNER JOIN "user" creator ON deleted.created_by_id = creator.id
  INNER JOIN "user" updater ON deleted.updated_by_id = updater.id
`

type DeleteCustomerParams struct {
	Slug           string    `json:"slug"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type DeleteCustomerRow struct {
	ID                 uuid.UUID        `json:"id"`
	Name               string           `json:"name"`
	Slug               string           `json:"slug"`
	ExternalCustomerID *string          `json:"external_customer_id"`
	CreatedByID        uuid.UUID        `json:"created_by_id"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedByID        uuid.UUID        `json:"updated_by_id"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	OrganizationID     uuid.UUID        `json:"organization_id"`
	Domain             *string          `json:"domain"`
	CreatedByName      string           `json:"created_by_name"`
	UpdatedByName      string           `json:"updated_by_name"`
}

func (q *Queries) DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) (DeleteCustomerRow, error) {
	row := q.db.QueryRow(ctx, deleteCustomer, arg.Slug, arg.OrganizationID)
	var i DeleteCustomerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ExternalCustomerID,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedByID,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.Domain,
		&i.CreatedByName,
		&i.UpdatedByName,
	)
	return i, err
}

const getCustomerExternalIDByID = `-- name: GetCustomerExternalIDByID :one
SELECT c.external_customer_id
FROM customer c
WHERE c.organization_id = $1
  AND c.id = $2
`

type GetCustomerExternalIDByIDParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	CustomerID     uuid.UUID `json:"customer_id"`
}

func (q *Queries) GetCustomerExternalIDByID(ctx context.Context, arg GetCustomerExternalIDByIDParams) (*string, error) {
	row := q.db.QueryRow(ctx, getCustomerExternalIDByID, arg.OrganizationID, arg.CustomerID)
	var external_customer_id *string
	err := row.Scan(&external_customer_id)
	return external_customer_id, err
}

const getCustomerNameByID = `-- name: GetCustomerNameByID :one
SELECT c.name
FROM customer c
WHERE c.organization_id = $1
  AND c.id = $2
`

type GetCustomerNameByIDParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	CustomerID     uuid.UUID `json:"customer_id"`
}

func (q *Queries) GetCustomerNameByID(ctx context.Context, arg GetCustomerNameByIDParams) (string, error) {
	row := q.db.QueryRow(ctx, getCustomerNameByID, arg.OrganizationID, arg.CustomerID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getCustomers = `-- name: GetCustomers :many
SELECT c.id,
       c.name,
       c.slug,
       external_customer_id,
  c.domain,
       c.created_by_id,
       creator.name AS created_by_name,
       c.created_at,
       c.updated_by_id,
       updater.name AS updated_by_name,
       c.updated_at,
       c.organization_id
FROM customer c
  INNER JOIN "user" creator ON c.created_by_id = creator.id
  INNER JOIN "user" updater ON c.updated_by_id = updater.id
WHERE c.organization_id = $1
  AND (
    $2::text IS NULL
    OR EXISTS (
      SELECT 1
      FROM customer_integrations ci
      WHERE ci.customer_id = c.id
        AND ci.organization_id = c.organization_id
        AND ci.adapter = $2::text
        AND ci.external_id <> ''
    )
  )
  AND (
    $3::timestamp IS NULL
    OR (c.created_at, c.id) < ($3::timestamp, $4::uuid)
  )
ORDER BY c.created_at DESC, c.id DESC
LIMIT $5
`

type GetCustomersParams struct {
	OrganizationID  uuid.UUID        `json:"organization_id"`
	Adapter         *string          `json:"adapter"`
	CursorCreatedAt pgtype.Timestamp `json:"cursor_created_at"`
	CursorID        *uuid.UUID       `json:"cursor_id"`
	LimitPlusOne    int32            `json:"limit_plus_one"`
}

type GetCustomersRow struct {
	ID                 uuid.UUID        `json:"id"`
	Name               string           `json:"name"`
	Slug               string           `json:"slug"`
	ExternalCustomerID *string          `json:"external_customer_id"`
	Domain             *string          `json:"domain"`
	CreatedByID        uuid.UUID        `json:"created_by_id"`
	CreatedByName      string           `json:"created_by_name"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedByID        uuid.UUID        `json:"updated_by_id"`
	UpdatedByName      string           `json:"updated_by_name"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	OrganizationID     uuid.UUID        `json:"organization_id"`
}

// Cursor (keyset) pagination: ordered by created_at DESC, id DESC (id
// tie-breaks created_at, which is not guaranteed unique). Pass
// limit_plus_one = requested limit + 1 so the caller can detect whether a
// further page exists without a separate COUNT query. On the first page,
// pass NULL for both cursor_created_at and cursor_id. Pass NULL for
// adapter to page over every customer, or an adapter name to keep only
// the customers synced with that integration (a matching
// customer_integrations row with a non-empty external_id).
func (q *Queries) GetCustomers(ctx context.Context, arg GetCustomersParams) ([]GetCustomersRow, error) {
	rows, err := q.db.Query(ctx, getCustomers,
		arg.OrganizationID,
		arg.Adapter,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitPlusOne,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCustomersRow
	for rows.Next() {
		var i GetCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ExternalCustomerID,
			&i.Domain,
			&i.CreatedByID,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedByID,
			&i.UpdatedByName,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomersByExternalID = `-- name: GetCustomersByExternalID :many
SELECT c.id,
       c.name,
       c.slug,
       external_customer_id,
  c.domain,
       c.created_by_id,
       creator.name AS created_by_name,
       c.created_at,
       c.updated_by_id,
       updater.name AS updated_by_name,
       c.updated_at,
       c.organization_id
FROM customer c
  INNER JOIN "user" creator ON c.created_by_id = creator.id
  INNER JOIN "user" updater ON c.updated_by_id = updater.id
WHERE c.organization_id = $1
  AND c.external_customer_id = $2
`

type GetCustomersByExternalIDParams struct {
	OrganizationID     uuid.UUID `json:"organization_id"`
	ExternalCustomerID *string   `json:"external_customer_id"`
}

type GetCustomersByExternalIDRow struct {
	ID                 uuid.UUID        `json:"id"`
	Name               string           `json:"name"`
	Slug               string           `json:"slug"`
	ExternalCustomerID *string          `json:"external_customer_id"`
	Domain             *string          `json:"domain"`
	CreatedByID        uuid.UUID        `json:"created_by_id"`
	CreatedByName      string           `json:"created_by_name"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedByID        uuid.UUID        `json:"updated_by_id"`
	UpdatedByName      string           `json:"updated_by_name"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	OrganizationID     uuid.UUID        `json:"organization_id"`
}

// `external_customer_id` carries the host's own tenant id and has no unique
// constraint, so this is deliberately :many — the caller decides what an
// ambiguous match means rather than silently getting an arbitrary row.
func (q *Queries) GetCustomersByExternalID(ctx context.Context, arg GetCustomersByExternalIDParams) ([]GetCustomersByExternalIDRow, error) {
	rows, err := q.db.Query(ctx, getCustomersByExternalID, arg.OrganizationID, arg.ExternalCustomerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCustomersByExternalIDRow
	for rows.Next() {
		var i GetCustomersByExternalIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ExternalCustomerID,
			&i.Domain,
			&i.CreatedByID,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedByID,
			&i.UpdatedByName,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomersByIDs = `-- name: GetCustomersByIDs :many
SELECT c.id,
       c.name,
       c.slug,
       external_customer_id,
  c.domain,
       c.created_by_id,
       creator.name AS created_by_name,
       c.created_at,
       c.updated_by_id,
       updater.name AS updated_by_name,
       c.updated_at,
       c.organization_id
FROM customer c
  INNER JOIN "user" creator ON c.created_by_id = creator.id
  INNER JOIN "user" updater ON c.updated_by_id = updater.id
WHERE c.organization_id = $1
  AND c.id = ANY ($2::uuid[])
`

type GetCustomersByIDsParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	CustomerIds    []uuid.UUID `json:"customer_ids"`
}

type GetCustomersByIDsRow struct {
	ID                 uuid.UUID        `json:"id"`
	Name               string           `json:"name"`
	Slug               string           `json:"slug"`
	ExternalCustomerID *string          `json:"external_customer_id"`
	Domain             *string          `json:"domain"`
	CreatedByID        uuid.UUID        `json:"created_by_id"`
	CreatedByName      string           `json:"created_by_name"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedByID        uuid.UUID        `json:"updated_by_id"`
	UpdatedByName      string           `json:"updated_by_name"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	OrganizationID     uuid.UUID        `json:"organization_id"`
}

func (q *Queries) GetCustomersByIDs(ctx context.Context, arg GetCustomersByIDsParams) ([]GetCustomersByIDsRow, error) {
	rows, err := q.db.Query(ctx, getCustomersByIDs, arg.OrganizationID, arg.CustomerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCustomersByIDsRow
	for rows.Next() {
		var i GetCustomersByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ExternalCustomerID,
			&i.Domain,
			&i.CreatedByID,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedByID,
			&i.UpdatedByName,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOneCustomer = `-- name: GetOneCustomer :one
SELECT c.id,
       c.name,
       c.slug,
       external_customer_id,
  c.domain,
       c.created_by_id,
       creator.name AS created_by_name,
       c.created_at,
       c.updated_by_id,
       updater.name AS updated_by_name,
       c.updated_at,
       c.organization_id
FROM customer c
  INNER JOIN "user" creator ON c.created_by_id = creator.id
  INNER JOIN "user" updater ON c.updated_by_id = updater.id
WHERE c.organization_id = $1
  AND c.slug = $2
`

type GetOneCustomerParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Slug           string    `json:"slug"`
}

type GetOneCustomerRow struct {
	ID                 uuid.UUID        `json:"id"`
	Name               string           `json:"name"`
	Slug               string           `json:"slug"`
	ExternalCustomerID *string          `json:"external_customer_id"`
	Domain             *string          `json:"domain"`
	CreatedByID        uuid.UUID        `json:"created_by_id"`
	CreatedByName      string           `json:"created_by_name"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedByID        uuid.UUID        `json:"updated_by_id"`
	UpdatedByName      string           `json:"updated_by_name"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	OrganizationID     uuid.UUID        `json:"organization_id"`
}

func (q *Queries) GetOneCustomer(ctx context.Context, arg GetOneCustomerParams) (GetOneCustomerRow, error) {
	row := q.db.QueryRow(ctx, getOneCustomer, arg.OrganizationID, arg.Slug)
	var i GetOneCustomerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ExternalCustomerID,
		&i.Domain,
		&i.CreatedByID,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedByID,
		&i.UpdatedByName,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const getTargetingFactsByCustomerSlug = `-- name: GetTargetingFactsByCustomerSlug :many

WITH primary_instance AS (
  SELECT i.id, i.license_id
  FROM instance i
         JOIN customer c ON c.id = i.customer_id AND c.organization_id = i.organization_id
  WHERE c.organization_id = $1
    AND c.slug = $2
  -- id breaks a created_at tie, so the choice never depends on row order.
  ORDER BY i.created_at, i.id
  LIMIT 1
)
SELECT l.slug           AS license_slug,
       lf.slug          AS license_family_slug,
       l.type           AS license_type,
       e.slug           AS entitlement_slug,
       iee.value        AS limit_value,
       eu.value         AS usage_value
FROM primary_instance pi
       JOIN "license" l ON l.id = pi.license_id
       JOIN license_family lf ON lf.id = l.family_id AND lf.organization_id = l.organization_id
       -- The instance's effective entitlements, as every reader of an
       -- instance's entitlement value reads them.
       LEFT JOIN instance_effective_entitlement iee
         ON iee.instance_id = pi.id AND iee.organization_id = $1
       LEFT JOIN entitlement e
         ON e.id = iee.entitlement_id AND e.organization_id = $1
       LEFT JOIN entitlement_usage eu
         ON eu.instance_id = pi.id
        AND eu.entitlement_id = e.id
        AND eu.organization_id = $1
ORDER BY e.slug
`

type GetTargetingFactsByCustomerSlugParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	CustomerSlug   string    `json:"customer_slug"`
}

type GetTargetingFactsByCustomerSlugRow struct {
	LicenseSlug       string      `json:"license_slug"`
	LicenseFamilySlug string      `json:"license_family_slug"`
	LicenseType       LicenseType `json:"license_type"`
	EntitlementSlug   *string     `json:"entitlement_slug"`
	LimitValue        []byte      `json:"limit_value"`
	UsageValue        []byte      `json:"usage_value"`
}

// Server-side facts for feature-flag targeting: the licence a customer's
// instance carries, the family that licence is a version of, and every
// entitlement on it with its recorded usage.
// Targeting rules are evaluated against these, never against attributes the
// client sent, or a rule on someone's plan or quota would be spoofable.
//
// One row per entitlement, the licence columns repeated: a single round trip on
// the most-called path of the product, and the caller shapes the rest.
//
// SCOPED TO ONE INSTANCE, and that is a correctness requirement rather than a
// cheap way to return fewer rows. Limits live on the licence
// (license_entitlement.license_id) while usage lives on the instance
// (entitlement_usage PK is entitlement_id + instance_id), so each instance
// consumes its OWN allowance of the licence's threshold. Two instances at half
// their cap are two half-full instances, not one full customer — summing them
// would invent a saturation nobody reached.
//
// Returning every instance's rows instead let the caller key them by
// entitlement slug, where later instances silently overwrote earlier ones: the
// licence came from the oldest instance and the usage from the newest, a
// customer that exists nowhere. The oldest active instance is the customer's
// original one, which is also the licence the previous shape happened to
// report — so single-instance customers, the overwhelming case, are unaffected.
//
// The family's slug is what a rule targets a product by: the licence slug
// names one version and changes with every new one. Every licence has
// a family in its own organization (license_family_id_fkey), so the join never
// drops the row.
func (q *Queries) GetTargetingFactsByCustomerSlug(ctx context.Context, arg GetTargetingFactsByCustomerSlugParams) ([]GetTargetingFactsByCustomerSlugRow, error) {
	rows, err := q.db.Query(ctx, getTargetingFactsByCustomerSlug, arg.OrganizationID, arg.CustomerSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTargetingFactsByCustomerSlugRow
	for rows.Next() {
		var i GetTargetingFactsByCustomerSlugRow
		if err := rows.Scan(
			&i.LicenseSlug,
			&i.LicenseFamilySlug,
			&i.LicenseType,
			&i.EntitlementSlug,
			&i.LimitValue,
			&i.UsageValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCustomerExternalIDByID = `-- name: SetCustomerExternalIDByID :execrows
UPDATE customer c
SET external_customer_id = $1,
    updated_at = now()
WHERE c.organization_id = $2
  AND c.id = $3
`

type SetCustomerExternalIDByIDParams struct {
	ExternalCustomerID *string   `json:"external_customer_id"`
	OrganizationID     uuid.UUID `json:"organization_id"`
	CustomerID         uuid.UUID `json:"customer_id"`
}

func (q *Queries) SetCustomerExternalIDByID(ctx context.Context, arg SetCustomerExternalIDByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCustomerExternalIDByID, arg.ExternalCustomerID, arg.OrganizationID, arg.CustomerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCustomer = `-- name: UpdateCustomer :one
WITH updated AS (
  UPDATE customer c
  SET name          = $1,
      external_customer_id = $2,
    domain = $3,
      updated_by_id = uo.user_id,
      updated_at    = now()
  FROM user_on_organization uo
  WHERE uo.organization_id = $4
     AND uo.user_id = $5
         AND uo.deleted_at IS NULL
         AND c.organization_id = uo.organization_id
         AND c.slug = $6
  RETURNING c.id, c.name, c.slug, c.external_customer_id, c.created_by_id, c.created_at, c.updated_by_id, c.updated_at, c.organization_id, c.domain
)
SELECT updated.id, updated.name, updated.slug, updated.external_customer_id, updated.created_by_id, updated.created_at, updated.updated_by_id, updated.updated_at, updated.organization_id, updated.domain,
       creator.name AS created_by_name,
       updater.name AS updated_by_name
FROM updated
  INNER JOIN "user" creator ON updated.created_by_id = creator.id
  INNER JOIN "user" updater ON updated.updated_by_id = updater.id
`

type UpdateCustomerParams struct {
	Name               string    `json:"name"`
	ExternalCustomerID *string   `json:"external_customer_id"`
	Domain             *string   `json:"domain"`
	OrganizationID     uuid.UUID `json:"organization_id"`
	UserID             uuid.UUID `json:"user_id"`
	Slug               string    `json:"slug"`
}

type UpdateCustomerRow struct {
	ID                 uuid.UUID        `json:"id"`
	Name               string           `json:"name"`
	Slug               string           `json:"slug"`
	ExternalCustomerID *string          `json:"external_customer_id"`
	CreatedByID        uuid.UUID        `json:"created_by_id"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedByID        uuid.UUID        `json:"updated_by_id"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	OrganizationID     uuid.UUID        `json:"organization_id"`
	Domain             *string          `json:"domain"`
	CreatedByName      string           `json:"created_by_name"`
	UpdatedByName      string           `json:"updated_by_name"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (UpdateCustomerRow, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.Name,
		arg.ExternalCustomerID,
		arg.Domain,
		arg.OrganizationID,
		arg.UserID,
		arg.Slug,
	)
	var i UpdateCustomerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ExternalCustomerID,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedByID,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.Domain,
		&i.CreatedByName,
		&i.UpdatedByName,
	)
	return i, err
}
