// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: license_family.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countLicenseVersionsInFamily = `-- name: CountLicenseVersionsInFamily :one
SELECT count(*)::integer AS version_count
FROM license l
WHERE l.organization_id = $1
  AND l.family_id = $2
`

type CountLicenseVersionsInFamilyParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	FamilyID       uuid.UUID `json:"family_id"`
}

// Organization-scoped like every other read here. The family id its callers
// pass already came out of an organization-scoped lookup, so the filter is not
// what stands between one tenant and another's count -- it is here so that
// stays true of the query itself rather than of the two call sites that happen
// to precede it today.
func (q *Queries) CountLicenseVersionsInFamily(ctx context.Context, arg CountLicenseVersionsInFamilyParams) (int32, error) {
	row := q.db.QueryRow(ctx, countLicenseVersionsInFamily, arg.OrganizationID, arg.FamilyID)
	var version_count int32
	err := row.Scan(&version_count)
	return version_count, err
}

const createLicenseFamily = `-- name: CreateLicenseFamily :one
INSERT INTO license_family (organization_id, slug)
VALUES ($1,
        $2)
RETURNING id, organization_id, slug, last_version, created_at, updated_at, is_public
`

type CreateLicenseFamilyParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Slug           string    `json:"slug"`
}

// A family is created with the first version of a product and outlives every
// one of them: it is what a rename cannot move and what a pricing URL can
// point at. It carries no display name -- the current version's own name is
// the display -- so there is nothing to pass here but the slug.
func (q *Queries) CreateLicenseFamily(ctx context.Context, arg CreateLicenseFamilyParams) (LicenseFamily, error) {
	row := q.db.QueryRow(ctx, createLicenseFamily, arg.OrganizationID, arg.Slug)
	var i LicenseFamily
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.LastVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublic,
	)
	return i, err
}

const deleteLicenseFamilyIfEmpty = `-- name: DeleteLicenseFamilyIfEmpty :execrows
DELETE
FROM license_family f
WHERE f.organization_id = $1
  AND f.id = $2
  AND NOT EXISTS (SELECT 1 FROM license l WHERE l.family_id = f.id)
`

type DeleteLicenseFamilyIfEmptyParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	FamilyID       uuid.UUID `json:"family_id"`
}

// A family does not outlive its last version: with nothing left to resolve
// to it would be a listed product with nothing in it, and a slug reserved
// with no way to release it. Conditional on the count so that deleting one
// version of several leaves the family exactly as it was. Only sound under
// the lock LockLicenseFamilyOfLicense takes in the same transaction. The row
// count says whether the family went, which is when the organization's
// licenses usage goes down.
func (q *Queries) DeleteLicenseFamilyIfEmpty(ctx context.Context, arg DeleteLicenseFamilyIfEmptyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLicenseFamilyIfEmpty, arg.OrganizationID, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCurrentLicenseVersionsByFamilyIDs = `-- name: GetCurrentLicenseVersionsByFamilyIDs :many
SELECT DISTINCT ON (l.family_id) l.id, l.name, l.slug, l.description, l.type, l.version, l.version_name, l.is_default, l.features, l.organization_id, l.created_at, l.updated_at, l.family_id, l.lifecycle_state, l.pricing_type, l.trial_period_days, l.requires_payment_method, l.self_serve_cta_url
FROM license l
WHERE l.organization_id = $1
  AND l.family_id = ANY ($2::uuid[])
  AND l.lifecycle_state = 'PUBLISHED'
ORDER BY l.family_id, l.is_default DESC, l.version DESC
`

type GetCurrentLicenseVersionsByFamilyIDsParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	FamilyIds      []uuid.UUID `json:"family_ids"`
}

// Resolves "the current version" for each of the given families, in one query
// rather than one per family.
//
// The rule, in the ORDER BY: the family's default version first, then the
// highest-numbered one, among PUBLISHED versions only. is_default DESC puts
// true ahead of false, and license_default_must_be_published_check guarantees a
// default is always PUBLISHED, so the default -- when there is one -- always
// wins this ordering rather than being filtered out of it.
//
// A family with no PUBLISHED version simply returns no row, which is what makes
// "draft only" representable in a list and what the family endpoint reports as
// GetLicenseFamily.NoPublishedVersion.
func (q *Queries) GetCurrentLicenseVersionsByFamilyIDs(ctx context.Context, arg GetCurrentLicenseVersionsByFamilyIDsParams) ([]License, error) {
	rows, err := q.db.Query(ctx, getCurrentLicenseVersionsByFamilyIDs, arg.OrganizationID, arg.FamilyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []License
	for rows.Next() {
		var i License
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.Version,
			&i.VersionName,
			&i.IsDefault,
			&i.Features,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FamilyID,
			&i.LifecycleState,
			&i.PricingType,
			&i.TrialPeriodDays,
			&i.RequiresPaymentMethod,
			&i.SelfServeCtaUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLicenseFamiliesByIDs = `-- name: GetLicenseFamiliesByIDs :many
SELECT f.id, f.organization_id, f.slug, f.last_version, f.created_at, f.updated_at, f.is_public
FROM license_family f
WHERE f.organization_id = $1
  AND f.id = ANY ($2::uuid[])
`

type GetLicenseFamiliesByIDsParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	FamilyIds      []uuid.UUID `json:"family_ids"`
}

// Batch read for the GraphQL License.family dataloader. Organization-scoped
// like every other read here, so a family id guessed from another tenant
// resolves to nothing rather than to that tenant's family.
func (q *Queries) GetLicenseFamiliesByIDs(ctx context.Context, arg GetLicenseFamiliesByIDsParams) ([]LicenseFamily, error) {
	rows, err := q.db.Query(ctx, getLicenseFamiliesByIDs, arg.OrganizationID, arg.FamilyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LicenseFamily
	for rows.Next() {
		var i LicenseFamily
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Slug,
			&i.LastVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsPublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLicenseFamilyByIDForUpdate = `-- name: GetLicenseFamilyByIDForUpdate :one
SELECT id, organization_id, slug, last_version, created_at, updated_at, is_public
FROM license_family
WHERE organization_id = $1
  AND id = $2
FOR UPDATE
`

type GetLicenseFamilyByIDForUpdateParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

// The identifier form of GetLicenseFamilyForUpdate, for a create that names
// the family by familyId rather than by slug -- the handle the console holds,
// since a license's representation carries its family's id and not its slug.
// Same lock, same reasons.
func (q *Queries) GetLicenseFamilyByIDForUpdate(ctx context.Context, arg GetLicenseFamilyByIDForUpdateParams) (LicenseFamily, error) {
	row := q.db.QueryRow(ctx, getLicenseFamilyByIDForUpdate, arg.OrganizationID, arg.ID)
	var i LicenseFamily
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.LastVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublic,
	)
	return i, err
}

const getLicenseFamilyBySlug = `-- name: GetLicenseFamilyBySlug :one
SELECT f.id, f.organization_id, f.slug, f.last_version, f.created_at, f.updated_at, f.is_public
FROM license_family f
WHERE f.organization_id = $1
  AND f.slug = $2
`

type GetLicenseFamilyBySlugParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Slug           string    `json:"slug"`
}

func (q *Queries) GetLicenseFamilyBySlug(ctx context.Context, arg GetLicenseFamilyBySlugParams) (LicenseFamily, error) {
	row := q.db.QueryRow(ctx, getLicenseFamilyBySlug, arg.OrganizationID, arg.Slug)
	var i LicenseFamily
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.LastVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublic,
	)
	return i, err
}

const getLicenseFamilyForUpdate = `-- name: GetLicenseFamilyForUpdate :one
SELECT id, organization_id, slug, last_version, created_at, updated_at, is_public
FROM license_family
WHERE organization_id = $1
  AND slug = $2
FOR UPDATE
`

type GetLicenseFamilyForUpdateParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Slug           string    `json:"slug"`
}

// Takes a row lock on the family so that concurrent version creations in it
// serialize. The version number itself is assigned by
// update_license_version(), which advances the family's last_version on this
// same row; this lock exists because the caller also needs to *know* that
// number before the INSERT, to derive the version's slug from it. Held to
// commit, it keeps last_version where the caller read it, so last_version + 1
// is the number the trigger then assigns.
func (q *Queries) GetLicenseFamilyForUpdate(ctx context.Context, arg GetLicenseFamilyForUpdateParams) (LicenseFamily, error) {
	row := q.db.QueryRow(ctx, getLicenseFamilyForUpdate, arg.OrganizationID, arg.Slug)
	var i LicenseFamily
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.LastVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublic,
	)
	return i, err
}

const getLicenseIdentityBySlug = `-- name: GetLicenseIdentityBySlug :one
SELECT l.family_id, l.version, l.lifecycle_state
FROM license l
WHERE l.organization_id = $1
  AND l.slug = $2
`

type GetLicenseIdentityBySlugParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Slug           string    `json:"slug"`
}

type GetLicenseIdentityBySlugRow struct {
	FamilyID       uuid.UUID             `json:"family_id"`
	Version        int32                 `json:"version"`
	LifecycleState LicenseLifecycleState `json:"lifecycle_state"`
}

// What an update never changes about a license version and may have to check
// against: its family -- to unset the previous default, and to refuse a
// familyId that is not the row's own -- its version number, which is readOnly,
// and its lifecycle state, which moves only through publish, archive and
// unarchive. The last two are accepted on update only as an echo.
func (q *Queries) GetLicenseIdentityBySlug(ctx context.Context, arg GetLicenseIdentityBySlugParams) (GetLicenseIdentityBySlugRow, error) {
	row := q.db.QueryRow(ctx, getLicenseIdentityBySlug, arg.OrganizationID, arg.Slug)
	var i GetLicenseIdentityBySlugRow
	err := row.Scan(&i.FamilyID, &i.Version, &i.LifecycleState)
	return i, err
}

const getLicenseVersionInFamily = `-- name: GetLicenseVersionInFamily :one
SELECT l.id, l.name, l.slug, l.description, l.type, l.version, l.version_name, l.is_default, l.features, l.organization_id, l.created_at, l.updated_at, l.family_id, l.lifecycle_state, l.pricing_type, l.trial_period_days, l.requires_payment_method, l.self_serve_cta_url
FROM license l
WHERE l.organization_id = $1
  AND l.family_id = $2
  AND l.version = $3
`

type GetLicenseVersionInFamilyParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	FamilyID       uuid.UUID `json:"family_id"`
	Version        int32     `json:"version"`
}

// Explicit historical access: ?version=N on the family endpoint resolves a
// version by number regardless of lifecycle state, archived included. Pinned
// access stays pinned -- that is the whole point of addressing a version rather
// than a family.
func (q *Queries) GetLicenseVersionInFamily(ctx context.Context, arg GetLicenseVersionInFamilyParams) (License, error) {
	row := q.db.QueryRow(ctx, getLicenseVersionInFamily, arg.OrganizationID, arg.FamilyID, arg.Version)
	var i License
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Type,
		&i.Version,
		&i.VersionName,
		&i.IsDefault,
		&i.Features,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FamilyID,
		&i.LifecycleState,
		&i.PricingType,
		&i.TrialPeriodDays,
		&i.RequiresPaymentMethod,
		&i.SelfServeCtaUrl,
	)
	return i, err
}

const listLicenseFamiliesByCursor = `-- name: ListLicenseFamiliesByCursor :many
SELECT f.id, f.organization_id, f.slug, f.last_version, f.created_at, f.updated_at, f.is_public,
       (SELECT count(*) FROM license l WHERE l.family_id = f.id)::integer AS version_count
FROM license_family f
WHERE f.organization_id = $1
  AND (
    $2::timestamp IS NULL
    OR (f.created_at, f.id) < ($2::timestamp, $3::uuid)
  )
ORDER BY f.created_at DESC, f.id DESC
LIMIT $4
`

type ListLicenseFamiliesByCursorParams struct {
	OrganizationID  uuid.UUID        `json:"organization_id"`
	CursorCreatedAt pgtype.Timestamp `json:"cursor_created_at"`
	CursorID        *uuid.UUID       `json:"cursor_id"`
	LimitPlusOne    int32            `json:"limit_plus_one"`
}

type ListLicenseFamiliesByCursorRow struct {
	ID             uuid.UUID        `json:"id"`
	OrganizationID uuid.UUID        `json:"organization_id"`
	Slug           string           `json:"slug"`
	LastVersion    int32            `json:"last_version"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	IsPublic       bool             `json:"is_public"`
	VersionCount   int32            `json:"version_count"`
}

// Cursor (keyset) pagination over the organization's families, ordered by
// created_at DESC, id DESC -- the same key every other list endpoint in this API
// uses, backed by idx_license_family_org_created_at. Pass limit_plus_one =
// requested limit + 1 so the caller can detect a further page without a COUNT.
//
// version_count counts every version, whatever its lifecycle state: it answers
// "how many versions does this product have" for a console rendering the
// family, not "how many can be sold". The current version is resolved
// separately (GetCurrentLicenseVersionsByFamilyIDs) rather than joined here,
// because a LEFT JOIN would make all twelve license columns nullable in this
// row type for the sake of a family that has nothing published.
func (q *Queries) ListLicenseFamiliesByCursor(ctx context.Context, arg ListLicenseFamiliesByCursorParams) ([]ListLicenseFamiliesByCursorRow, error) {
	rows, err := q.db.Query(ctx, listLicenseFamiliesByCursor,
		arg.OrganizationID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitPlusOne,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLicenseFamiliesByCursorRow
	for rows.Next() {
		var i ListLicenseFamiliesByCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Slug,
			&i.LastVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsPublic,
			&i.VersionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLicenseVersionsInFamily = `-- name: ListLicenseVersionsInFamily :many
SELECT l.id, l.name, l.slug, l.description, l.type, l.version, l.version_name, l.is_default, l.features, l.organization_id, l.created_at, l.updated_at, l.family_id, l.lifecycle_state, l.pricing_type, l.trial_period_days, l.requires_payment_method, l.self_serve_cta_url
FROM license l
WHERE l.organization_id = $1
  AND l.family_id = $2
ORDER BY l.version
`

type ListLicenseVersionsInFamilyParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	FamilyID       uuid.UUID `json:"family_id"`
}

// The ?include=versions view: every version of the family, oldest first, with
// its lifecycle state. Unbounded on purpose -- it is the version history of one
// product, which is bounded by how many times a vendor has published it.
func (q *Queries) ListLicenseVersionsInFamily(ctx context.Context, arg ListLicenseVersionsInFamilyParams) ([]License, error) {
	rows, err := q.db.Query(ctx, listLicenseVersionsInFamily, arg.OrganizationID, arg.FamilyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []License
	for rows.Next() {
		var i License
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.Version,
			&i.VersionName,
			&i.IsDefault,
			&i.Features,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FamilyID,
			&i.LifecycleState,
			&i.PricingType,
			&i.TrialPeriodDays,
			&i.RequiresPaymentMethod,
			&i.SelfServeCtaUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLicenseFamilyOfLicense = `-- name: LockLicenseFamilyOfLicense :one
SELECT f.id
FROM license_family f
       JOIN license l ON l.family_id = f.id
WHERE l.organization_id = $1
  AND l.slug = $2
FOR UPDATE OF f
`

type LockLicenseFamilyOfLicenseParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Slug           string    `json:"slug"`
}

// Takes the family row lock on behalf of a version delete, before the version
// row goes. It is the same lock GetLicenseFamilyForUpdate takes before a
// version is added, so the two serialize on it in the same order, and it is
// what lets DeleteLicenseFamilyIfEmpty trust its count: nothing can join the
// family between that count and the delete.
func (q *Queries) LockLicenseFamilyOfLicense(ctx context.Context, arg LockLicenseFamilyOfLicenseParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockLicenseFamilyOfLicense, arg.OrganizationID, arg.Slug)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const setLicenseFamilyPublic = `-- name: SetLicenseFamilyPublic :one
UPDATE license_family
SET is_public = $1
WHERE organization_id = $2
  AND slug = $3
RETURNING id
`

type SetLicenseFamilyPublicParams struct {
	IsPublic       bool      `json:"is_public"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Slug           string    `json:"slug"`
}

// Lists the family in the public catalogue, or takes it out. updated_at is
// left alone: it says when a version was last added.
func (q *Queries) SetLicenseFamilyPublic(ctx context.Context, arg SetLicenseFamilyPublicParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, setLicenseFamilyPublic, arg.IsPublic, arg.OrganizationID, arg.Slug)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
