import {
  Boxes,
  Braces,
  Coins,
  FileText,
  Flag,
  type LucideIcon,
  MapPinned,
  Package,
  Puzzle,
  Receipt,
  Repeat,
  Rocket,
  Server,
  Tag,
  Ticket,
  UserKey,
  Users,
} from 'lucide-react';

export const dataModelIcons = {
  customer: Users,
  instance: Server,
  entitlement: Boxes,
  featureFlag: Flag,
  license: FileText,
  version: Tag,
  release: Rocket,
  component: Package,
  deploymentZone: MapPinned,
  serviceAccount: UserKey,
  token: Braces,
  invoice: Receipt,
  subscription: Repeat,
  price: Coins,
  addon: Puzzle,
  voucher: Ticket,
} as const satisfies Record<string, LucideIcon>;

export type DataModelIconKey = keyof typeof dataModelIcons;
