package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/kaitencloud/kaiten/api/internal/modules/addons/catalogue"
	addonsGraphql "github.com/kaitencloud/kaiten/api/internal/modules/addons/graphql"
	"github.com/kaitencloud/kaiten/api/internal/modules/instances/schema"
)

// Addons is the resolver for the addons field.
func (r *instanceResolver) Addons(ctx context.Context, obj *schema.Instance) ([]catalogue.InstanceAddon, error) {
	return addonsGraphql.LoadInstanceAddons(ctx, obj.ID)
}
