package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"time"

	"github.com/kaitencloud/kaiten/api/internal/infrastructure/http/graphql/generated"
	instancesGraphql "github.com/kaitencloud/kaiten/api/internal/modules/instances/graphql"
	instanceschema "github.com/kaitencloud/kaiten/api/internal/modules/instances/schema"
)

// Payload is the resolver for the payload field.
func (r *auditTrailResolver) Payload(ctx context.Context, obj *instanceschema.AuditTrail) (map[string]any, error) {
	if obj.Payload == nil {
		return nil, nil
	}
	if m, ok := obj.Payload.(map[string]any); ok {
		return m, nil
	}
	return nil, nil
}

// AuditTrails is the resolver for the auditTrails field on Instance.
func (r *instanceResolver) AuditTrails(ctx context.Context, obj *instanceschema.Instance, eventName *string, after *time.Time, before *time.Time, limit *int, cursor *string) (*instanceschema.AuditTrailPage, error) {
	return instancesGraphql.GetAuditTrails(ctx, r.AuditTrailForInstancePort, obj.Slug, eventName, after, before, limit, cursor)
}

// AuditTrails is the resolver for the auditTrails field on Query.
func (r *queryResolver) AuditTrails(ctx context.Context, instanceSlug string, eventName *string, after *time.Time, before *time.Time, limit *int, cursor *string) (*instanceschema.AuditTrailPage, error) {
	return instancesGraphql.GetAuditTrails(ctx, r.AuditTrailForInstancePort, instanceSlug, eventName, after, before, limit, cursor)
}

// OrganizationAuditTrails is the resolver for the organizationAuditTrails field.
func (r *queryResolver) OrganizationAuditTrails(ctx context.Context, eventName *string, after *time.Time, before *time.Time, limit *int, cursor *string) (*instanceschema.OrganizationAuditTrailPage, error) {
	return instancesGraphql.GetOrganizationAuditTrails(ctx, r.AuditTrailForOrgPort, eventName, after, before, limit, cursor)
}

// AuditTrail returns generated.AuditTrailResolver implementation.
func (r *Resolver) AuditTrail() generated.AuditTrailResolver { return &auditTrailResolver{r} }

type auditTrailResolver struct{ *Resolver }
