package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/google/uuid"
	"github.com/kaitencloud/kaiten/api/internal/infrastructure/dogfooding"
	componentsGraphql "github.com/kaitencloud/kaiten/api/internal/modules/components/graphql"
	"github.com/kaitencloud/kaiten/api/internal/modules/components/schema"
)

// Components is the resolver for the components field.
func (r *queryResolver) Components(ctx context.Context, limit *int, cursor *string) (*schema.ComponentPage, error) {
	l := pageLimit(limit)
	components, err := componentsGraphql.GetComponents(ctx, r.ComponentsQueries, l, cursor)
	if err != nil {
		return nil, err
	}

	r.reportIfNeeded(ctx, dogfooding.ComponentReadEntitlementSlug)
	return components, nil
}

// Component is the resolver for the component field.
func (r *queryResolver) Component(ctx context.Context, id *uuid.UUID, slug *string) (*schema.Component, error) {
	component, err := componentsGraphql.GetComponent(ctx, r.ComponentsQueries, id, slug)
	if err != nil {
		return nil, err
	}

	r.reportIfNeeded(ctx, dogfooding.ComponentReadEntitlementSlug)
	return component, nil
}
