package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/kaitencloud/kaiten/api/internal/infrastructure/http/graphql/generated"
	entitlementsGraphql "github.com/kaitencloud/kaiten/api/internal/modules/entitlements/graphql"
	schema1 "github.com/kaitencloud/kaiten/api/internal/modules/entitlements/schema"
	entitlementvalue "github.com/kaitencloud/kaiten/api/internal/modules/entitlements/value"
	licensesGraphql "github.com/kaitencloud/kaiten/api/internal/modules/licenses/graphql"
	"github.com/kaitencloud/kaiten/api/internal/modules/licenses/schema"
)

// Entitlements is the resolver for the entitlements field.
func (r *licenseResolver) Entitlements(ctx context.Context, obj *schema.License) ([]schema.LicenseEntitlement, error) {
	return licensesGraphql.LoadLicenseEntitlements(ctx, obj.ID, obj.Slug)
}

// Value is the resolver for the value field.
func (r *licenseEntitlementResolver) Value(ctx context.Context, obj *schema.LicenseEntitlement) (map[string]any, error) {
	return obj.Value, nil
}

// Unlimited is the resolver for the unlimited field.
func (r *licenseEntitlementResolver) Unlimited(ctx context.Context, obj *schema.LicenseEntitlement) (bool, error) {
	return entitlementvalue.IsUnlimitedValue(obj.Value), nil
}

// Entitlement is the resolver for the entitlement field.
// Usage is billed by the loader (entitlements-read), not here.
func (r *licenseEntitlementResolver) Entitlement(ctx context.Context, obj *schema.LicenseEntitlement) (*schema1.Entitlement, error) {
	return entitlementsGraphql.LoadEntitlementBySlug(ctx, obj.EntitlementSlug)
}

// LicenseEntitlement returns generated.LicenseEntitlementResolver implementation.
func (r *Resolver) LicenseEntitlement() generated.LicenseEntitlementResolver {
	return &licenseEntitlementResolver{r}
}

type licenseEntitlementResolver struct{ *Resolver }
