package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/kaitencloud/kaiten/api/internal/infrastructure/dogfooding"
	metadataFieldsGraphql "github.com/kaitencloud/kaiten/api/internal/modules/metadatafields/graphql"
	metadatafieldsdb "github.com/kaitencloud/kaiten/api/internal/modules/metadatafields/infrastructure/db"
	"github.com/kaitencloud/kaiten/api/internal/modules/metadatafields/schema"
)

// MetadataFields is the resolver for the metadataFields field.
func (r *queryResolver) MetadataFields(ctx context.Context, resourceType metadatafieldsdb.MetadataFieldResourceType, includeArchived *bool, limit *int, cursor *string) (*schema.MetadataFieldPage, error) {
	include := false
	if includeArchived != nil {
		include = *includeArchived
	}
	l := pageLimit(limit)
	page, err := metadataFieldsGraphql.ListMetadataFields(ctx, r.MetadataFieldsQueries, resourceType, include, l, cursor)
	if err != nil {
		return nil, err
	}

	r.reportIfNeeded(ctx, dogfooding.MetadataFieldReadEntitlementSlug)
	return page, nil
}
