package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/google/uuid"
	"github.com/kaitencloud/kaiten/api/internal/infrastructure/dogfooding"
	"github.com/kaitencloud/kaiten/api/internal/infrastructure/http/graphql/generated"
	componentschema "github.com/kaitencloud/kaiten/api/internal/modules/components/schema"
	deploymentzoneschema "github.com/kaitencloud/kaiten/api/internal/modules/deploymentzones/schema"
	instanceschema "github.com/kaitencloud/kaiten/api/internal/modules/instances/schema"
	releasesGraphql "github.com/kaitencloud/kaiten/api/internal/modules/releases/graphql"
	releaseschema "github.com/kaitencloud/kaiten/api/internal/modules/releases/schema"
)

// Releases is the resolver for the releases field.
func (r *queryResolver) Releases(ctx context.Context, limit *int, cursor *string) (*releaseschema.ReleasePage, error) {
	l := pageLimit(limit)
	releases, err := releasesGraphql.GetReleases(ctx, r.ReleasesQueries, l, cursor)
	if err != nil {
		return nil, err
	}

	r.reportIfNeeded(ctx, dogfooding.ReleaseReadEntitlementSlug)
	return releases, nil
}

// Release is the resolver for the release field.
func (r *queryResolver) Release(ctx context.Context, id *uuid.UUID, slug *string) (*releaseschema.Release, error) {
	release, err := releasesGraphql.GetRelease(ctx, r.ReleasesQueries, id, slug)
	if err != nil {
		return nil, err
	}

	r.reportIfNeeded(ctx, dogfooding.ReleaseReadEntitlementSlug)
	return release, nil
}

// Components is the resolver for the components field.
func (r *releaseResolver) Components(ctx context.Context, obj *releaseschema.Release) ([]componentschema.Component, error) {
	return releasesGraphql.LoadComponentsByRelease(ctx, obj.ID)
}

// DeploymentZones is the resolver for the deploymentZones field.
func (r *releaseResolver) DeploymentZones(ctx context.Context, obj *releaseschema.Release) ([]deploymentzoneschema.DeploymentZone, error) {
	return releasesGraphql.LoadDeploymentZonesByRelease(ctx, obj.ID)
}

// Instances is the resolver for the instances field.
func (r *releaseResolver) Instances(ctx context.Context, obj *releaseschema.Release) ([]instanceschema.Instance, error) {
	return releasesGraphql.LoadInstancesByRelease(ctx, obj.ID)
}

// Deployments is the resolver for the deployments field.
func (r *releaseResolver) Deployments(ctx context.Context, obj *releaseschema.Release) ([]deploymentzoneschema.Deployment, error) {
	return releasesGraphql.LoadDeploymentsByRelease(ctx, obj.ID)
}

// Release returns generated.ReleaseResolver implementation.
func (r *Resolver) Release() generated.ReleaseResolver { return &releaseResolver{r} }

type releaseResolver struct{ *Resolver }
